import type { CopyKey } from './en'

// Anrede „Sie“. Begriffe: docs/i18n-glossary.md（Klasseneinteilung, zusammen, trennen）
export const DE_COPY: Record<CopyKey, string> = {
  appEyebrow: 'Mosaic · Klasseneinteilung',
  close: 'Schließen',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  save: 'Speichern',
  edit: 'Bearbeiten',
  add: 'Hinzufügen',
  erase: 'Löschen',
  tabRoster: 'Liste',
  tabRun: 'Einteilen',
  tabResults: 'Ergebnis',
  tabPro: 'Pro',
  privacyTitle: 'Datenschutzerklärung',

  loadTitle: 'Schülerliste laden',
  loadDesc: 'Füllen Sie die Excel-Vorlage aus (gleiches Format wie die Webversion) und wählen Sie die Datei – oder beginnen Sie mit einem Beispiel oder einer leeren Liste. Die Liste bleibt auf diesem Gerät.',
  pickFile: 'Excel-Datei wählen (.xlsx)',
  newRoster: 'Leere Liste anlegen',
  newRosterName: 'Neue Liste',
  trySamples: 'Beispiel ausprobieren',
  getTemplate: 'Excel-Vorlage holen',
  templateHint: 'Die Vorlage enthält die Blätter Einstellungen, Schülerliste, Zusammen und Trennen sowie Beispielmerkmale.',
  privacyLink: 'Umgang mit Ihren Daten (Datenschutz) ›',
  samplePrefix: 'Beispiel: {label}',

  rosterTitle: 'Schülerliste',
  backToRoster: 'Abbrechen (zur aktuellen Liste)',
  rosterSummary: '{n} Schüler · {cols} Merkmale · zusammen {w} · trennen {u}',
  otherRoster: 'Andere Liste',
  saveRosterXlsx: 'Liste als Excel',
  toRun: 'Weiter',
  proFeaturesNote: 'Excel-Export, Drucken und PDF sind Pro-Funktionen (Einmalkauf).',
  loadWarnings: 'Hinweise beim Laden',
  tabStudents: 'Schüler {n}',
  tabColumns: 'Merkmale',
  tabWanted: 'Zusammen {n}',
  tabUnwanted: 'Trennen {n}',

  filterPlaceholder: 'Nach Name, Nr. oder Wert filtern',
  addStudent: 'Schüler hinzufügen',
  countWide: '{shown} / {total} Schüler · Zeile anklicken, um sie rechts zu bearbeiten',
  countNarrow: '{shown} / {total} Schüler · zum Bearbeiten tippen',
  selectToEdit: 'Wählen Sie links einen Schüler aus, um ihn hier zu bearbeiten.',
  editStudentA11y: '{no} {name} bearbeiten',
  noName: '(ohne Namen)',
  colNo: 'Nr.',
  colName: 'Name',

  editStudent: 'Schüler bearbeiten',
  namePlaceholder: 'Vor- und Nachname',
  noInvalid: 'Bitte eine ganze Zahl ab 1 eingeben',
  noTaken: 'Nr. {no} ist bereits vergeben',
  kindFlag: 'Ja/Nein',
  kindCategory: 'Kategorie',
  kindNumeric: 'Zahl',
  blank: 'Leer',
  newValuePlaceholder: 'Neuen Wert eingeben und Enter drücken',
  numberPlaceholder: 'Zahl',
  valueA11y: 'Wert für {col}',
  noColumns: 'Noch keine Merkmale. Fügen Sie sie im Tab „Merkmale“ hinzu.',
  pairingsLabel: 'Wünsche',
  deleteStudent: 'Diesen Schüler löschen',
  deleteStudentTitle: 'Schüler löschen',
  deleteStudentBody: '{who} wird aus der Liste und aus allen Wünschen entfernt.',

  columnsHelp:
    'Merkmale mit höherem Gewicht werden zuerst gleichmäßig auf die Klassen verteilt. Bei Gewicht 0 wird das Merkmal ignoriert. Ein einziger Wert (✓ oder leer) gilt als Ja/Nein, mehrere Werte als Kategorie, 7 oder mehr Zahlen als Zahl (die Klassendurchschnitte werden angeglichen).',
  deleteColumnA11y: 'Merkmal „{name}“ löschen',
  deleteColumnTitle: 'Merkmal löschen',
  deleteColumnBody: '„{name}“ wird für alle Schüler entfernt.',
  weight: 'Gewicht',
  weightA11y: 'Gewicht von {name}',
  decrease: '{label} verringern',
  increase: '{label} erhöhen',
  columnEmpty: 'Alle Einträge sind leer, daher wird dieses Merkmal nicht verwendet. Tragen Sie Werte beim Bearbeiten der Schüler ein.',
  addColumnTitle: 'Merkmal hinzufügen',
  addColumnPlaceholder: 'z. B. Klassensprecher, Klavier, Leseförderung',
  duplicateColumn: 'Ein Merkmal mit diesem Namen gibt es schon',
  blankOnly: '(nur leer)',

  wantedTitle: 'Zusammen',
  unwantedTitle: 'Trennen',
  conditionsCount: '{n}',
  addCondition: 'Hinzufügen',
  addConditionTitle: '„{kind}“ hinzufügen',
  editConditionTitle: '{label} bearbeiten',
  wantedHelp: 'Alle ausgewählten Schüler kommen in dieselbe Klasse (auch 3 oder mehr).',
  unwantedHelp: 'Die ausgewählten Schüler kommen jeweils in verschiedene Klassen.',
  noConditions: 'Noch keine Wünsche.',
  conflict: 'Widersprüchliche Wünsche: {pairs} sind über „zusammen“ verbunden, sollen aber auch getrennt werden.',
  conflictPair: '{a} und {b}',
  selectedNames: 'Ausgewählt: {names} (mindestens 2)',
  selectedNone: 'keine',
  willDelete: 'Mit weniger als 2 Schülern wird dieser Wunsch beim Speichern gelöscht',
  filterNames: 'Nach Name oder Nr. filtern',

  runTitle: 'Einteilen',
  loadFirst: 'Laden Sie zuerst im Tab „Liste“ eine Schülerliste.',
  loadRosterBtn: 'Liste laden',
  classCount: 'Anzahl Klassen (Gruppen)',
  classCountA11y: 'Anzahl Klassen',
  perClass: '{range} Schüler pro Klasse ({n} insgesamt)',
  maxPerClass: 'Höchstzahl pro Klasse',
  maxHint: 'Legt die Anzahl der Klassen automatisch fest',
  searchTime: 'Suchdauer',
  quick: 'Schnell 3 s',
  standard: 'Standard 10 s',
  thorough: 'Gründlich 30 s',
  timeInfo: '{s} s',
  timeInfoStarts: '{s} s · bestes Ergebnis aus {n} Durchläufen',
  balancedItems: 'Auszugleichende Merkmale',
  editAttributes: 'Merkmale bearbeiten',
  noEnabled: 'Keine Merkmale aktiv (nur die Klassengröße wird angeglichen).',
  pairsSummary: 'Zusammen: {w} · Trennen: {u}',
  searching: 'Beste Einteilung wird gesucht … {p} %',
  stop: 'Stopp',
  runBtn: 'Klassen einteilen',
  rerun: 'Neu einteilen',
  lastRun: 'Zuletzt: {k} Klassen · {starts} Durchläufe · {m} Mio. Schritte',
  tooFew: 'Es gibt weniger Schüler ({n}) als Klassen ({k}).',
  discarded: 'Die Liste wurde während der Suche geändert, das Ergebnis wurde verworfen. Bitte erneut starten.',

  resultsTitle: 'Ergebnis',
  notYet: 'Noch keine Einteilung. Starten Sie „Klassen einteilen“ im Tab „Einteilen“.',
  toRunBtn: 'Zu „Einteilen“',
  statClasses: 'Klassen',
  statClassesSub: '{n} Schüler eingeteilt',
  statGap: 'Größenunterschied',
  statGapSub: '{min}–{max} Schüler',
  statBalance: 'Ausgewogen\u00ADheit',
  perfect: 'Perfekt',
  balancePerfectSub: 'Alle Merkmale im Sollbereich',
  balanceSub: 'Schüler außerhalb des Sollbereichs',
  statViolations: 'Nicht erfüllt',
  violationsSub: 'Einige Wünsche sind nicht erfüllt',
  violationsOk: 'Alle Wünsche erfüllt',
  undoMoves: 'Änderungen zurücksetzen',
  shareXlsx: 'Als Excel teilen',
  print: 'Drucken',
  printPdf: 'Drucken / PDF',
  sharePdf: 'Als PDF teilen',
  tabClasses: 'Klassen',
  tabBalance: 'Ausgewogen\u00ADheit',
  tabChecks: 'Prüfung',
  tabChecksN: 'Prüfung ({n})',
  noBalanceItems: 'Keine Merkmale zum Ausgleichen.',
  moveTitle: '{who} verschieben →',
  moveTo: 'In {cls} verschieben',
  boardHintWide: 'Klicken oder tippen Sie auf einen Namen, um ihn in eine andere Klasse zu verschieben. Die Auswertung wird sofort neu berechnet.',
  boardHintNarrow: 'Oben eine Klasse wählen. Auf einen Namen tippen, um ihn zu verschieben. Die Auswertung wird sofort neu berechnet.',
  pairingsHeader: 'Wünsche',
  pairingsMet: '{ok} von {n} erfüllt',
  colorize: '„Zusammen“ farbig',
  studentsN: '{n}',
  classChip: '{cls} · {n}',
  studentA11y: '{no} {name}, {cls}. Tippen, um in eine andere Klasse zu verschieben',
  wantedBadgeA11y: 'Zusammen {label}',
  unwantedBadgeA11y: 'Trennen {label}',
  notMetA11y: ', nicht erfüllt',
  weightN: 'Gewicht {w}',
  average: 'Mittelwert',
  even: 'Ausgeglichen',
  offBy: 'Abweichung {n}',
  target: 'Soll',
  allMet: 'Alle Bedingungen erfüllt',
  allMetBody: 'Alle {w} Wünsche „zusammen“ und {u} Wünsche „trennen“ wurden berücksichtigt.',
  noPairsBody: 'Es wurden keine Wünsche angegeben.',

  proTitle: 'Pro & Einstellungen',
  proName: 'Mosaic Pro',
  active: '✓ Aktiv',
  proIntro: 'Laden, Bearbeiten, Einteilen und Nachbessern sind kostenlos und werbefrei. Pro brauchen Sie erst zum Exportieren und Drucken.',
  feat1Title: 'Ergebnis nach Excel und Google Drive exportieren',
  feat1Body:
    'Klasseneinteilung, Klassenlisten, ein Blatt pro Klasse, Wünsche und Auswertung als .xlsx-Datei – über das Teilen-Menü an Excel, Google Drive oder per E-Mail. Auch die bearbeitete Schülerliste lässt sich im Format der Vorlage speichern (die Webversion öffnet sie ebenfalls).',
  feat2Title: 'Drucken oder als PDF für die Konferenz',
  feat2Body: 'Klassenlisten (mit farbig markierten Wünschen und Legende) sowie Auswertung und Verteilungstabellen auf A4-Hochformat – zum Drucken oder als PDF.',
  feat3Title: 'Einmal kaufen, dauerhaft nutzen',
  feat3Body: 'Einmalkauf, kein Abo – es entstehen keine weiteren Kosten.',
  thanksPro: 'Vielen Dank, dass Sie Pro nutzen. Alle Funktionen sind freigeschaltet.',
  buyWithPrice: 'Pro kaufen ({price}, einmalig)',
  buy: 'Pro kaufen (einmalig)',
  restore: 'Kauf wiederherstellen',
  language: 'Sprache',
  languageHint: 'Standardmäßig wird die Sprache des Geräts verwendet.',
  followDevice: 'Gerätesprache',
  dataTitle: 'Ihre Daten',
  dataBody: 'Schülerlisten und Ergebnisse bleiben auf diesem Gerät und werden nirgendwohin hochgeladen. Beim Export als Excel oder PDF entscheiden Sie selbst, wohin die Datei geht.',
  clearData: 'Liste und Ergebnis auf diesem Gerät löschen',
  clearTitle: 'Liste und Ergebnis löschen',
  clearBody: 'Die auf diesem Gerät gespeicherte Liste und Einteilung werden gelöscht. Das lässt sich nicht rückgängig machen.',
  footer: 'Mosaic · Werkzeug für die Klasseneinteilung (kostenlose Webversion: https://ohru131.github.io/ClassClassify/)',

  purchaseStoreOnly: 'Käufe sind in der iOS- oder Android-App möglich.',
  revenueCatKeyMissing: 'Der öffentliche RevenueCat-SDK-Schlüssel ist nicht konfiguriert.',
  customerInfoFetchFailed: 'Kaufinformationen konnten nicht geladen werden. Bitte später erneut versuchen.',
  purchaseSucceeded: 'Vielen Dank! Pro ist jetzt freigeschaltet. Es ist ein Einmalkauf, weitere Kosten fallen nicht an.',
  purchaseNotApplied:
    'Die Zahlung war erfolgreich, Pro ist aber noch nicht aktiv. Tippen Sie auf „Kauf wiederherstellen“. Falls es weiterhin nicht klappt, wenden Sie sich an den Support – Ihnen wird nichts doppelt berechnet.',
  purchaseFailed: 'Der Kauf konnte nicht abgeschlossen werden. Bitte erneut versuchen.',
  productLoadFailed: 'Pro konnte nicht aus dem Store geladen werden. Bitte Verbindung prüfen und erneut versuchen.',
  proRestored: 'Ihr Pro-Kauf wurde wiederhergestellt.',
  noRestorablePurchase: 'Es wurde kein Pro-Kauf zum Wiederherstellen gefunden.',
  restoreFailed: 'Der Kauf konnte nicht wiederhergestellt werden. Bitte erneut versuchen.',

  parseRosterMissing: 'Das Blatt „{sheet}“ fehlt oder enthält keine Daten',
  parseNoStudents: 'Keine Schüler gefunden (Nr. und Name ab Zeile 3 eintragen)',
  parseNoMissing: '{sheet}, Zeile {row}: „{name}“ hat keine Nr. und wurde übersprungen',
  parseDuplicateNo: 'Nr. {no} kommt mehrfach vor',
  parseUnknownNo: '„{sheet}“, Zeile {row}: Nr. {no} steht nicht in der Liste',
  parseClassCountUnknown: 'Die Anzahl der Klassen in „{sheet}“ war nicht lesbar, daher wurden {k} Klassen verwendet',
  parseMaxTooSmall: 'Mit höchstens {max} Schülern × {k} Klassen passen nicht alle hinein, daher wurde die Höchstzahl ignoriert',
  sharingUnavailable: 'Auf diesem Gerät ist das Teilen von Dateien nicht möglich.',
  popupBlocked: 'Das Pop-up wurde blockiert. Bitte in den Browsereinstellungen erlauben.',
  fileResults: 'Klasseneinteilung',
  fileRoster: 'Schuelerliste',
  fileTemplate: 'Mosaic-Vorlage',

  printTitle: 'Klasseneinteilung',
  printCreated: 'Erstellt: {date}',
  printClasses: 'Klassen ({n} Schüler)',
  printGap: 'Größenunterschied ({min}–{max})',
  printBalance: 'Ausgewogenheit',
  printViolations: 'nicht erfüllt',
  printPairings: 'Wünsche ({ok} von {n} erfüllt)',
  printLegendNote: '{w}N = zusammen (Zeilen gleich eingefärbt), {u}N = trennen. × kennzeichnet einen nicht erfüllten Wunsch.',
  printNotMet: 'nicht erfüllt',
  printClassLists: 'Klassenlisten',
  printColPair: 'Wunsch',
  printColMarks: 'Merkmale',
  printSummary: 'Auswertung',
  printUnmet: 'Nicht erfüllte Wünsche',
}
