// 英語のキー集合が正。他の言語はこのキーを全部持たないと型エラーになる（lib/copy/index.ts）。
// 訳語は docs/i18n-glossary.md に揃える。{name} は format() で埋める。
import { PRIVACY_TITLE } from './privacy'

export const EN_COPY = {
  appEyebrow: 'FairClass · Class placement',
  close: 'Close',
  cancel: 'Cancel',
  delete: 'Delete',
  save: 'Save',
  edit: 'Edit',
  add: 'Add',
  erase: 'Erase',
  tabRoster: 'Roster',
  tabRun: 'Setup & run',
  tabResults: 'Results',
  tabPro: 'Pro',
  privacyTitle: PRIVACY_TITLE['en'],

  loadTitle: 'Load a roster',
  loadDesc: 'Fill in the Excel template (same format as the web version) and pick the file, or start from a sample or a blank roster. Your roster is saved only on this device.',
  pickFile: 'Choose an Excel file (.xlsx)',
  newRoster: 'Create a blank roster',
  newRosterName: 'New roster',
  trySamples: 'Try a sample',
  getTemplate: 'Get the Excel template',
  templateHint: 'The template has the sheets Settings, Roster, Keep together and Keep apart, with example attributes.',
  privacyLink: 'How your data is handled (privacy policy) ›',
  samplePrefix: 'Sample: {label}',

  rosterTitle: 'Roster',
  backToRoster: 'Cancel (back to the current roster)',
  rosterSummary: '{n} students · {cols} attributes · keep together {w} · keep apart {u}',
  otherRoster: 'Other roster',
  saveRosterXlsx: 'Save roster as Excel',
  toRun: 'Go to setup',
  proFeaturesNote: 'Excel export, printing and PDF are Pro features (one-time purchase).',
  loadWarnings: 'Notes from loading',
  tabStudents: 'Students {n}',
  tabColumns: 'Attributes',
  tabWanted: 'Together {n}',
  tabUnwanted: 'Apart {n}',

  filterPlaceholder: 'Filter by name, No. or value',
  addStudent: 'Add student',
  countWide: '{shown} / {total} students · click a row to edit it on the right',
  countNarrow: '{shown} / {total} students · tap to edit',
  selectToEdit: 'Select a student in the list to edit them here.',
  editStudentA11y: 'Edit {no} {name}',
  noName: '(no name)',
  colNo: 'No.',
  colName: 'Name',

  editStudent: 'Edit student',
  namePlaceholder: 'Full name',
  noInvalid: 'Enter a number of 1 or more',
  noTaken: 'No. {no} is already used by another student',
  kindFlag: 'Yes/no',
  kindCategory: 'Category',
  kindNumeric: 'Number',
  blank: 'Blank',
  newValuePlaceholder: 'Type a new value and press Enter',
  numberPlaceholder: 'Number',
  valueA11y: 'Value of {col}',
  noColumns: 'No attributes yet. Add them in the "Attributes" tab.',
  pairingsLabel: 'Pairings',
  deleteStudent: 'Delete this student',
  deleteStudentTitle: 'Delete student',
  deleteStudentBody: '{who} will be removed from the roster and from any pairings.',

  columnsHelp:
    'Attributes with a higher weight are spread across classes first. At weight 0, an attribute is not taken into account. One value (e.g. ✓ or blank) is treated as yes/no, a few values as a category, and 7 or more numbers as a number (class averages are balanced).',
  deleteColumnA11y: 'Delete attribute "{name}"',
  deleteColumnTitle: 'Delete attribute',
  deleteColumnBody: '"{name}" will be removed for every student.',
  weight: 'Weight',
  weightA11y: 'Weight of {name}',
  decrease: '{label}: decrease',
  increase: '{label}: increase',
  columnEmpty: 'Everyone is blank, so this attribute is not used. Enter values when editing students.',
  addColumnTitle: 'Add an attribute',
  addColumnPlaceholder: 'e.g. Leader, Piano, Reading support',
  duplicateColumn: 'An attribute with this name already exists',
  blankOnly: '(blank only)',

  wantedTitle: 'Keep together',
  unwantedTitle: 'Keep apart',
  conditionsCount: '{n}',
  addCondition: 'Add',
  addConditionTitle: 'Add a "{kind}" condition',
  editConditionTitle: 'Edit {label}',
  wantedHelp: 'Everyone you select will be placed in the same class (3 or more is fine).',
  unwantedHelp: 'Everyone you select will be placed in different classes as far as possible.',
  noConditions: 'No conditions yet.',
  conflict: 'These pairings contradict each other: {pairs} are linked by "keep together" but are also set to "keep apart".',
  conflictPair: '{a} and {b}',
  selectedNames: 'Selected: {names} (2 or more)',
  selectedNone: 'none',
  willDelete: 'Saving with fewer than 2 students deletes this condition',
  filterNames: 'Filter by name or No.',

  runTitle: 'Setup & run',
  loadFirst: 'Load a roster in the "Roster" tab first.',
  loadRosterBtn: 'Load a roster',
  classCount: 'Number of classes',
  classCountA11y: 'Number of classes',
  perClass: '{range} students per class ({n} total)',
  maxPerClass: 'Maximum class size',
  maxHint: 'Changing it sets the number of classes for you',
  searchTime: 'Thinking time',
  quick: 'Quick 3 s',
  standard: 'Standard 10 s',
  thorough: 'Thorough 30 s',
  timeInfo: '{s} s',
  timeInfoStarts: '{s} s · compares {n} plans and picks the best',
  balancedItems: 'Attributes to balance',
  editAttributes: 'Edit attributes',
  noEnabled: 'No attributes to balance (only class sizes will be evened out).',
  pairsSummary: 'Keep together: {w} · Keep apart: {u}',
  searching: 'Finding a well-balanced arrangement… {p}%',
  stop: 'Stop',
  runBtn: 'Build classes',
  rerun: 'Build again',
  lastRun: 'Last time: {k} classes · {starts} plans · {m}M combinations tried',
  tooFew: 'There are fewer students ({n}) than classes ({k}).',
  discarded: 'The roster changed while classes were being built, so this result wasn’t used. Please build again.',

  resultsTitle: 'Results',
  notYet: 'No classes yet. Run "Build classes" in Setup & run to see the result here.',
  toRunBtn: 'Go to setup & run',
  statClasses: 'Classes',
  statClassesSub: '{n} students placed',
  statGap: 'Size difference',
  statGapSub: '{min}–{max} students',
  statBalance: 'Balance',
  perfect: 'Perfect',
  balancePerfectSub: 'Every attribute is within its target range',
  balanceSub: 'Students outside target ranges',
  statViolations: 'Pairings not met',
  violationsSub: 'Some pairings couldn’t be met',
  violationsOk: 'All pairings are met',
  undoMoves: 'Undo my changes',
  shareXlsx: 'Share results as Excel',
  saveToFile: 'Save to Drive or device',
  print: 'Print',
  printPdf: 'Print / PDF',
  sharePdf: 'Share as PDF',
  tabClasses: 'Classes',
  tabBalance: 'Balance',
  tabChecks: 'Checks',
  tabChecksN: 'Checks ({n})',
  noBalanceItems: 'No attributes to balance.',
  moveTitle: 'Move {who} →',
  moveTo: 'Move to {cls}',
  boardHintWide: 'Click or tap a student to move them to another class. Totals update instantly.',
  boardHintNarrow: 'Swipe left or right, or pick a class above. Tap a student to move them to another class. Totals update instantly.',
  prevClass: 'Previous class',
  nextClass: 'Next class',
  classPositionA11y: '{cls}, {i} of {n}',
  pairingsHeader: 'Pairings',
  pairingsMet: '{ok} / {n} met',
  colorize: 'Color "keep together"',
  studentsN: '{n}',
  classChip: '{cls} · {n}',
  studentA11y: '{no} {name}, {cls}. Tap to move to another class',
  wantedBadgeA11y: 'Keep together {label}',
  unwantedBadgeA11y: 'Keep apart {label}',
  notMetA11y: ', not met',
  weightN: 'Weight {w}',
  average: 'Average',
  even: 'Even',
  offBy: 'Off by {n}',
  target: 'Target',
  allMet: 'All pairings were met',
  allMetBody: 'All {w} keep-together and {u} keep-apart pairings were applied.',
  noPairsBody: 'No pairings were set.',

  proTitle: 'Pro & settings',
  proName: 'FairClass Pro',
  active: '✓ Active',
  proIntro: 'Loading, editing, building and adjusting classes is free, with no ads. Get Pro when you need to export or print.',
  feat1Title: 'Export results to Excel and Google Drive',
  feat1Body:
    'Placement, class lists, one sheet per class, pairings and summary as an .xlsx file — send it to Excel, Google Drive or email from the share sheet. You can also save your edited roster in the template format (it opens in the web version too).',
  feat2Title: 'Print or save as PDF for staff meetings',
  feat2Body: 'Class lists (with color-coded pairings and a legend) plus the summary and balance tables on A4 portrait pages, ready to print or save as PDF.',
  feat3Title: 'Buy once, use it for good',
  feat3Body: 'A one-time purchase, not a subscription — you will never be charged again.',
  thanksPro: 'Thank you for using Pro. All features are unlocked.',
  buyWithPrice: 'Get Pro ({price}, one-time)',
  buy: 'Get Pro (one-time)',
  restore: 'Restore purchase',
  language: 'Language',
  languageHint: 'By default the app follows your device language.',
  followDevice: 'Device setting',
  dataTitle: 'About your data',
  dataBody: 'Your rosters and results are saved only on this device and are never uploaded. When you export an Excel file or PDF, you choose where to send it.',
  clearData: 'Erase roster and results on this device',
  clearTitle: 'Erase roster and results',
  clearBody: 'This deletes the roster, results and saved placements on this device. It cannot be undone.',
  footer: 'FairClass · class placement helper (free web version: https://ohru131.github.io/ClassClassify/)',

  purchaseStoreOnly: 'Purchases are available in the iOS or Android app.',
  revenueCatKeyMissing: 'Purchases aren’t ready yet. Please try again later.',
  customerInfoFetchFailed: 'Could not load your purchase information. Please try again later.',
  purchaseSucceeded: 'Thank you! Pro is now unlocked. It is a one-time purchase, so there are no further charges.',
  purchaseNotApplied:
    'Your payment went through, but Pro is not active yet. Tap "Restore purchase". If it still does not activate, please contact support — you will not be charged twice.',
  purchaseFailed: 'The purchase could not be completed. Please try again.',
  productLoadFailed: 'Could not load Pro from the store. Check your connection and try again.',
  proRestored: 'Your Pro purchase has been restored.',
  noRestorablePurchase: 'No Pro purchase to restore was found.',
  restoreFailed: 'Could not restore your purchase. Please try again.',

  parseRosterMissing: 'The "{sheet}" sheet is missing or has no data',
  parseNoStudents: 'No students found (enter No. and name from row 3 on)',
  parseNoMissing: '{sheet}, row {row}: "{name}" has no No., so it was skipped',
  parseDuplicateNo: 'No. {no} appears more than once',
  parseUnknownNo: '"{sheet}", row {row}: No. {no} is not in the roster',
  parseClassCountUnknown: 'The number of classes in "{sheet}" could not be read, so {k} classes were used',
  parseMaxTooSmall: 'A maximum of {max} students × {k} classes can’t fit everyone, so the maximum class size was not used',
  sharingUnavailable: 'Sharing is not available on this device.',
  popupBlocked: 'Your browser couldn’t open a new window. Please allow pop-ups for this site.',
  fileResults: 'class-placement',
  fileRoster: 'roster',
  fileTemplate: 'fairclass-template',

  printTitle: 'Class placement results',
  printCreated: 'Created: {date}',
  printClasses: 'classes ({n} students)',
  printGap: 'size difference ({min}–{max})',
  printBalance: 'balance',
  printViolations: 'pairings not met',
  printPairings: 'Pairings ({ok} / {n} met)',
  printLegendNote: '{w}N = keep together (rows share a color), {u}N = keep apart. × marks a pairing that couldn’t be met.',
  printNotMet: 'not met',
  printClassLists: 'Class lists',
  printColPair: 'Pairing',
  printColMarks: 'Attributes',
  printSummary: 'Summary & balance',
  printUnmet: 'Pairings not met',

  // 名前を付けて保存・保存した編成・前回とできるだけ入れ替える
  savedTitle: 'Saved placements',
  savedEmpty: 'Nothing saved yet. On the Results tab, tap “Save with a name” to keep a placement here.',
  savedMeta: '{date} · {n} students · {k} classes',
  openSaved: 'Open',
  deleteSavedTitle: 'Delete saved placement',
  deleteSavedBody: 'Delete “{name}” from this device? This can’t be undone.',
  saveNamed: 'Save with a name',
  saveNameLabel: 'Name',
  savedDone: 'Saved as “{name}”. You can open it any time from the Roster tab.',
  saveFailed: 'Couldn’t save. Please try again.',
  openFailed: 'Couldn’t open this saved placement.',
  mixTitle: 'Mix up from last time',
  mixHelp: 'Students who were in the same class last time are spread across the new classes as far as possible.',
  mixPick: 'Which placement was last time?',
  mixMatched: 'Found last time’s class for {m} of {n} students.',
  mixNoSaved: 'Save a placement with a name on the Results tab, and you can choose it here next time.',
  prevClassColumn: 'Last class',
  mixFrom: 'Last time: {name}',
  featSaveTitle: 'Unlimited saved placements',
  featSaveBody: 'The free version keeps up to {max}. With Pro, keep every class placement and group arrangement, open them any time and use them to mix up from last time.',
  saveLimitReached: 'The free version keeps up to {max} saved placements. Delete an older one, or get Pro to save as many as you like.',
  savedCount: '{n} of {max} saved (free version)',
  manageSaved: 'See saved placements',
  seePro: 'See Pro',
  eraseFailed: 'Couldn’t erase everything. Please try again.',
}

export type CopyKey = keyof typeof EN_COPY
