// 英語のキー集合が正。他の言語はこのキーを全部持たないと型エラーになる（lib/copy/index.ts）。
// 訳語は docs/i18n-glossary.md に揃える。{name} は format() で埋める。
export const EN_COPY = {
  appEyebrow: 'Mosaic · Class placement',
  close: 'Close',
  cancel: 'Cancel',
  delete: 'Delete',
  save: 'Save',
  edit: 'Edit',
  add: 'Add',
  erase: 'Erase',
  tabRoster: 'Roster',
  tabRun: 'Setup & run',
  tabResults: 'Results',
  tabPro: 'Pro',
  privacyTitle: 'Privacy policy',

  loadTitle: 'Load a roster',
  loadDesc: 'Fill in the Excel template (same format as the web version) and pick the file, or start from a sample or a blank roster. Your roster is saved only on this device.',
  pickFile: 'Choose an Excel file (.xlsx)',
  newRoster: 'Create a blank roster',
  newRosterName: 'New roster',
  trySamples: 'Try a sample',
  getTemplate: 'Get the Excel template',
  templateHint: 'The template has the sheets Settings, Roster, Keep together and Keep apart, with example attributes.',
  privacyLink: 'How your data is handled (privacy policy) ›',
  samplePrefix: 'Sample: {label}',

  rosterTitle: 'Roster',
  backToRoster: 'Cancel (back to the current roster)',
  rosterSummary: '{n} students · {cols} attributes · keep together {w} · keep apart {u}',
  otherRoster: 'Other roster',
  saveRosterXlsx: 'Save roster as Excel',
  toRun: 'Go to setup',
  proFeaturesNote: 'Excel export, printing and PDF are Pro features (one-time purchase).',
  loadWarnings: 'Notes from loading',
  tabStudents: 'Students {n}',
  tabColumns: 'Attributes',
  tabWanted: 'Together {n}',
  tabUnwanted: 'Apart {n}',

  filterPlaceholder: 'Filter by name, No. or value',
  addStudent: 'Add student',
  countWide: '{shown} / {total} students · click a row to edit it on the right',
  countNarrow: '{shown} / {total} students · tap to edit',
  selectToEdit: 'Select a student in the list to edit them here.',
  editStudentA11y: 'Edit {no} {name}',
  noName: '(no name)',
  colNo: 'No.',
  colName: 'Name',

  editStudent: 'Edit student',
  namePlaceholder: 'Full name',
  noInvalid: 'Enter a whole number of 1 or more',
  noTaken: 'No. {no} is already used by another student',
  kindFlag: 'Yes/no',
  kindCategory: 'Category',
  kindNumeric: 'Number',
  blank: 'Blank',
  newValuePlaceholder: 'Type a new value and press Enter',
  numberPlaceholder: 'Number',
  valueA11y: 'Value of {col}',
  noColumns: 'No attributes yet. Add them in the "Attributes" tab.',
  pairingsLabel: 'Pairings',
  deleteStudent: 'Delete this student',
  deleteStudentTitle: 'Delete student',
  deleteStudentBody: '{who} will be removed from the roster and from any pairings.',

  columnsHelp:
    'Attributes with a higher weight are spread across classes first. Weight 0 ignores the attribute. One value (e.g. ✓ or blank) is treated as yes/no, a few values as a category, and 7 or more numbers as a number (class averages are balanced).',
  deleteColumnA11y: 'Delete attribute "{name}"',
  deleteColumnTitle: 'Delete attribute',
  deleteColumnBody: '"{name}" will be removed for every student.',
  weight: 'Weight',
  weightA11y: 'Weight of {name}',
  decrease: '{label}: decrease',
  increase: '{label}: increase',
  columnEmpty: 'Everyone is blank, so this attribute is not used. Enter values when editing students.',
  addColumnTitle: 'Add an attribute',
  addColumnPlaceholder: 'e.g. Leader, Piano, Reading support',
  duplicateColumn: 'An attribute with this name already exists',
  blankOnly: '(blank only)',

  wantedTitle: 'Keep together',
  unwantedTitle: 'Keep apart',
  conditionsCount: '{n}',
  addCondition: 'Add',
  addConditionTitle: 'Add a "{kind}" condition',
  editConditionTitle: 'Edit {label}',
  wantedHelp: 'Everyone you select will be placed in the same class (3 or more is fine).',
  unwantedHelp: 'Everyone you select will be placed in different classes from each other.',
  noConditions: 'No conditions yet.',
  conflict: 'Conflicting conditions: {pairs} are linked by "keep together" but are also set to "keep apart".',
  conflictPair: '{a} and {b}',
  selectedNames: 'Selected: {names} (2 or more)',
  selectedNone: 'none',
  willDelete: 'Saving with fewer than 2 students deletes this condition',
  filterNames: 'Filter by name or No.',

  runTitle: 'Setup & run',
  loadFirst: 'Load a roster in the "Roster" tab first.',
  loadRosterBtn: 'Load a roster',
  classCount: 'Number of classes',
  classCountA11y: 'Number of classes',
  perClass: '{range} students per class ({n} total)',
  maxPerClass: 'Maximum class size',
  maxHint: 'Changing it sets the number of classes for you',
  searchTime: 'Search time',
  quick: 'Quick 3 s',
  standard: 'Standard 10 s',
  thorough: 'Thorough 30 s',
  timeInfo: '{s} s',
  timeInfoStarts: '{s} s · best of {n} runs',
  balancedItems: 'Attributes to balance',
  editAttributes: 'Edit attributes',
  noEnabled: 'No attributes are active (only class sizes will be balanced).',
  pairsSummary: 'Keep together: {w} · Keep apart: {u}',
  searching: 'Finding the best combination… {p}%',
  stop: 'Stop',
  runBtn: 'Build classes',
  rerun: 'Build again',
  lastRun: 'Last run: {k} classes · {starts} runs · {m}M iterations',
  tooFew: 'There are fewer students ({n}) than classes ({k}).',
  discarded: 'The roster changed during the run, so the result was discarded. Please run again.',

  resultsTitle: 'Results',
  notYet: 'No classes yet. Run "Build classes" in Setup & run to see the result here.',
  toRunBtn: 'Go to setup & run',
  statClasses: 'Classes',
  statClassesSub: '{n} students placed',
  statGap: 'Size difference',
  statGapSub: '{min}–{max} students',
  statBalance: 'Balance',
  perfect: 'Perfect',
  balancePerfectSub: 'Every attribute is within its target range',
  balanceSub: 'Students outside target ranges',
  statViolations: 'Unmet conditions',
  violationsSub: 'Some pairings are not met',
  violationsOk: 'All pairings are met',
  undoMoves: 'Undo manual changes',
  shareXlsx: 'Share results as Excel',
  print: 'Print',
  printPdf: 'Print / PDF',
  sharePdf: 'Share as PDF',
  tabClasses: 'Classes',
  tabBalance: 'Balance',
  tabChecks: 'Checks',
  tabChecksN: 'Checks ({n})',
  noBalanceItems: 'No attributes to balance.',
  moveTitle: 'Move {who} →',
  moveTo: 'Move to {cls}',
  boardHintWide: 'Click or tap a student to move them to another class. Totals update instantly.',
  boardHintNarrow: 'Pick a class above. Tap a student to move them to another class. Totals update instantly.',
  pairingsHeader: 'Pairings',
  pairingsMet: '{ok} / {n} met',
  colorize: 'Color "keep together"',
  studentsN: '{n}',
  classChip: '{cls} · {n}',
  studentA11y: '{no} {name}, {cls}. Tap to move to another class',
  wantedBadgeA11y: 'Keep together {label}',
  unwantedBadgeA11y: 'Keep apart {label}',
  notMetA11y: ', not met',
  weightN: 'Weight {w}',
  average: 'Average',
  even: 'Even',
  offBy: 'Off by {n}',
  target: 'Target',
  allMet: 'All conditions are met',
  allMetBody: 'All {w} keep-together and {u} keep-apart conditions were applied.',
  noPairsBody: 'No pairings were set.',

  proTitle: 'Pro & settings',
  proName: 'Mosaic Pro',
  active: '✓ Active',
  proIntro: 'Loading, editing, building and adjusting classes is free, with no ads. Get Pro when you need to export or print.',
  feat1Title: 'Export results to Excel and Google Drive',
  feat1Body:
    'Placement, class lists, one sheet per class, pairings and summary as an .xlsx file — send it to Excel, Google Drive or email from the share sheet. You can also save your edited roster in the template format (it opens in the web version too).',
  feat2Title: 'Print or save as PDF for staff meetings',
  feat2Body: 'Class lists (with color-coded pairings and a legend) plus the summary and balance tables on A4 portrait pages, ready to print or save as PDF.',
  feat3Title: 'Buy once, use it for good',
  feat3Body: 'A one-time purchase, not a subscription — you will never be charged again.',
  thanksPro: 'Thank you for using Pro. All features are unlocked.',
  buyWithPrice: 'Get Pro ({price}, one-time)',
  buy: 'Get Pro (one-time)',
  restore: 'Restore purchase',
  language: 'Language',
  languageHint: 'By default the app follows your device language.',
  followDevice: 'Device setting',
  dataTitle: 'About your data',
  dataBody: 'Your rosters and results are saved only on this device and are never uploaded. When you export an Excel file or PDF, you choose where to send it.',
  clearData: 'Erase roster and results on this device',
  clearTitle: 'Erase roster and results',
  clearBody: 'This deletes the roster and results saved on this device. It cannot be undone.',
  footer: 'Mosaic · class placement optimizer (free web version: https://ohru131.github.io/ClassClassify/)',

  purchaseStoreOnly: 'Purchases are available in the iOS or Android app.',
  revenueCatKeyMissing: 'The RevenueCat public SDK key is not configured.',
  customerInfoFetchFailed: 'Could not load your purchase information. Please try again later.',
  purchaseSucceeded: 'Thank you! Pro is now unlocked. It is a one-time purchase, so there are no further charges.',
  purchaseNotApplied:
    'Your payment went through, but Pro is not active yet. Tap "Restore purchase". If it still does not activate, please contact support — you will not be charged twice.',
  purchaseFailed: 'The purchase could not be completed. Please try again.',
  productLoadFailed: 'Could not load Pro from the store. Check your connection and try again.',
  proRestored: 'Your Pro purchase has been restored.',
  noRestorablePurchase: 'No Pro purchase to restore was found.',
  restoreFailed: 'Could not restore your purchase. Please try again.',

  parseRosterMissing: 'The "{sheet}" sheet is missing or has no data',
  parseNoStudents: 'No students found (enter No. and name from row 3 on)',
  parseNoMissing: '{sheet}, row {row}: "{name}" has no No., so it was skipped',
  parseDuplicateNo: 'No. {no} appears more than once',
  parseUnknownNo: '"{sheet}", row {row}: No. {no} is not in the roster',
  parseClassCountUnknown: 'The number of classes in "{sheet}" could not be read, so {k} classes were used',
  parseMaxTooSmall: 'A maximum of {max} students × {k} classes cannot fit everyone, so the maximum was ignored',
  sharingUnavailable: 'Sharing is not available on this device.',
  popupBlocked: 'The pop-up was blocked. Please allow pop-ups for this site.',
  fileResults: 'class-placement',
  fileRoster: 'roster',
  fileTemplate: 'mosaic-template',

  printTitle: 'Class placement results',
  printCreated: 'Created: {date}',
  printClasses: 'classes ({n} students)',
  printGap: 'size difference ({min}–{max})',
  printBalance: 'balance',
  printViolations: 'unmet conditions',
  printPairings: 'Pairings ({ok} / {n} met)',
  printLegendNote: '{w}N = keep together (rows share a color), {u}N = keep apart. × marks a condition that is not met.',
  printNotMet: 'not met',
  printClassLists: 'Class lists',
  printColPair: 'Pairing',
  printColMarks: 'Attributes',
  printSummary: 'Summary & balance',
  printUnmet: 'Unmet conditions',
}

export type CopyKey = keyof typeof EN_COPY
