import { PRIVACY_TITLE } from './privacy'
import type { CopyKey } from './en'

// Español con vocabulario latinoamericano (tú, “grupo”, “estudiantes”). Términos: docs/i18n-glossary.md
export const ES_COPY: Record<CopyKey, string> = {
  appEyebrow: 'FairClass · Distribución de grupos',
  close: 'Cerrar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  save: 'Guardar',
  edit: 'Editar',
  add: 'Agregar',
  erase: 'Borrar',
  tabRoster: 'Lista',
  tabRun: 'Configurar',
  tabResults: 'Resultados',
  tabPro: 'Pro',
  privacyTitle: PRIVACY_TITLE['es'],

  loadTitle: 'Cargar una lista',
  loadDesc: 'Completa la plantilla de Excel (el mismo formato que la versión web) y elige el archivo, o empieza con un ejemplo o una lista vacía. La lista se guarda solo en este dispositivo.',
  pickFile: 'Elegir archivo de Excel (.xlsx)',
  newRoster: 'Crear una lista vacía',
  newRosterName: 'Nueva lista',
  trySamples: 'Probar con un ejemplo',
  getTemplate: 'Obtener la plantilla de Excel',
  templateHint: 'La plantilla trae las hojas Configuración, Lista de estudiantes, Mantener juntos y Separar, con criterios de ejemplo. Si eliges un archivo de Excel exportado desde Resultados, se abre con su distribución.',
  privacyLink: 'Cómo se tratan tus datos (política de privacidad) ›',
  samplePrefix: 'Ejemplo: {label}',

  rosterTitle: 'Lista',
  backToRoster: 'Cancelar (volver a la lista actual)',
  rosterSummary: '{n} estudiantes · {cols} criterios · juntos {w} · separar {u}',
  otherRoster: 'Abrir otra lista',
  saveRosterXlsx: 'Exportar lista a Excel',
  toRun: 'Ir a Configurar',
  proFeaturesNote: 'Exportar a Excel es una función Pro (pago único).',
  loadWarnings: 'Avisos al cargar',
  tabStudents: 'Estudiantes {n}',
  tabColumns: 'Criterios',
  tabWanted: 'Juntos {n}',
  tabUnwanted: 'Separar {n}',

  filterPlaceholder: 'Filtrar por nombre, N.º o valor',
  addStudent: 'Agregar estudiante',
  countWide: '{shown} / {total} estudiantes · haz clic en una fila para editarla a la derecha',
  countNarrow: '{shown} / {total} estudiantes · toca para editar',
  selectToEdit: 'Elige un estudiante de la lista para editarlo aquí.',
  editStudentA11y: 'Editar a {no} {name}',
  noName: '(sin nombre)',
  colNo: 'N.º',
  colName: 'Nombre',

  editStudent: 'Editar estudiante',
  namePlaceholder: 'Nombre completo',
  noInvalid: 'Escribe un número de 1 en adelante',
  noTaken: 'El N.º {no} ya lo usa otro estudiante',
  kindFlag: 'Casilla',
  kindCategory: 'Lista',
  kindDegree: 'Nivel (1–5)',
  kindNumeric: 'Número',
  blank: 'Vacío',
  newValuePlaceholder: 'Escribe una opción nueva y presiona Enter',
  numberPlaceholder: 'Número',
  valueA11y: 'Valor de {col}',
  noColumns: 'Todavía no hay criterios. Agrégalos en la pestaña “Criterios”.',
  pairingsLabel: 'Condiciones',
  deleteStudent: 'Eliminar a este estudiante',
  deleteStudentTitle: 'Eliminar estudiante',
  deleteStudentBody: '{who} se quitará de la lista y de todas las condiciones.',

  columnsHelp:
    'Los criterios con más peso se reparten primero de forma pareja entre los grupos. Con peso 0 el criterio no se toma en cuenta. Una casilla equilibra cuántos estudiantes la tienen marcada, una lista o un nivel (1–5) equilibra cada opción o nivel, y un número (7 o más valores distintos) equilibra los promedios.',
  deleteColumnA11y: 'Eliminar el criterio “{name}”',
  deleteColumnTitle: 'Eliminar criterio',
  deleteColumnBody: '“{name}” se eliminará para todos los estudiantes.',
  weight: 'Peso',
  weightA11y: 'Peso de {name}',
  decrease: '{label}: bajar',
  increase: '{label}: subir',
  columnEmpty: 'Todos están vacíos, así que este criterio no se usa. Ingresa valores al editar a los estudiantes.',
  addColumnTitle: 'Agregar un criterio',
  addColumnPlaceholder: 'p. ej. Liderazgo, Piano, Apoyo en lectura',
  duplicateColumn: 'Ya existe un criterio con ese nombre',
  blankOnly: '(solo vacíos)',
  listOptions: 'Opciones',
  addOptionChip: '+ Agregar opción',
  editOptionA11y: 'Renombrar la opción {v}',
  deleteOptionA11y: 'Eliminar la opción {v}',
  deleteOptionTitle: 'Eliminar opción',
  deleteOptionBody: 'Se eliminará "{v}" de la lista. Los {n} estudiantes que la tenían quedarán vacíos.',
  duplicateOption: 'Esa opción ya existe',
  listOptionsHint: 'Las opciones que nadie eligió no se guardan al exportar a Excel.',
  sampleExcelA11y: 'Obtener "{label}" en Excel',
  samplesExcelHint: 'Toca ⬇ para obtener un ejemplo en Excel. Edítalo y cárgalo con "Elegir un archivo de Excel".',
  currentRoster: 'Lista abierta',

  wantedTitle: 'Mantener juntos',
  unwantedTitle: 'Separar',
  conditionsCount: '{n}',
  addCondition: 'Agregar',
  addConditionTitle: 'Agregar condición “{kind}”',
  editConditionTitle: 'Editar {label}',
  wantedHelp: 'Todos los estudiantes que elijas quedarán en el mismo grupo (pueden ser 3 o más).',
  unwantedHelp: 'Los estudiantes que elijas quedarán en grupos distintos entre sí, en la medida de lo posible.',
  noConditions: 'Todavía no hay condiciones.',
  conflict: 'Hay condiciones contradictorias: {pairs} están unidos por “mantener juntos” pero también marcados para “separar”.',
  conflictPair: '{a} y {b}',
  selectedNames: 'Seleccionados: {names} (2 o más)',
  selectedNone: 'ninguno',
  willDelete: 'Si guardas con menos de 2 estudiantes, esta condición se elimina',
  filterNames: 'Filtrar por nombre o N.º',

  runTitle: 'Configurar y armar',
  loadFirst: 'Primero carga una lista en la pestaña “Lista”.',
  loadRosterBtn: 'Cargar una lista',
  classCount: 'Número de grupos',
  classCountA11y: 'Número de grupos',
  perClass: '{range} estudiantes por grupo ({n} en total)',
  maxPerClass: 'Máximo por grupo',
  maxHint: 'Al cambiarlo se calcula el número de grupos',
  searchTime: 'Tiempo para armar',
  quick: 'Rápido 3 s',
  standard: 'Estándar 10 s',
  thorough: 'A fondo 30 s',
  timeInfo: '{s} s',
  timeInfoStarts: '{s} s · compara {n} propuestas y elige la mejor',
  balancedItems: 'Criterios a equilibrar',
  editAttributes: 'Editar criterios',
  noEnabled: 'No hay criterios para equilibrar (solo se igualará el tamaño de los grupos).',
  pairsSummary: 'Mantener juntos: {w} · Separar: {u}',
  searching: 'Buscando una distribución equilibrada… {p} %',
  stop: 'Detener',
  runBtn: 'Armar grupos',
  rerun: 'Armar de nuevo',
  lastRun: 'La última vez: {k} grupos · {starts} propuestas · {m} M combinaciones probadas',
  tooFew: 'Hay menos estudiantes ({n}) que grupos ({k}).',
  discarded: 'La lista cambió mientras se armaban los grupos, así que no se usó este resultado. Vuelve a armarlos.',

  resultsTitle: 'Resultados',
  notYet: 'Todavía no hay grupos. Toca “Armar grupos” en la pestaña Configurar para ver el resultado aquí.',
  toRunBtn: 'Ir a Configurar',
  statClasses: 'Grupos',
  statClassesSub: '{n} estudiantes distribuidos',
  statGap: 'Diferencia de tamaño',
  statGapSub: '{min}–{max} estudiantes',
  statBalance: 'Equilibrio',
  perfect: 'Perfecto',
  balancePerfectSub: 'Todos los criterios están en su rango ideal',
  balanceSub: 'Estudiantes fuera del rango ideal',
  statViolations: 'Condiciones no cumplidas',
  violationsSub: 'Hay condiciones que no se pudieron cumplir',
  violationsOk: 'Se cumplen todas las condiciones',
  undoMoves: 'Deshacer mis cambios',
  saveToFile: 'Guardar como archivo',
  keepTitle: 'Guardar esta distribución',
  exportTitle: 'Exportar como archivo',
  exportExcel: 'Excel',
  exportPdf: 'PDF',
  exportSheetTitle: '¿Adónde enviar el archivo {format}?',
  shareVia: 'Compartir',
  shareViaSub: 'Envíalo por WhatsApp, correo u otra app',
  saveToFileSub: 'Guárdalo en Google Drive o en una carpeta del dispositivo',
  exportProNote: 'Excel, PDF e impresión vienen con Pro (pago único). Toca uno para ver más.',
  print: 'Imprimir',
  printPdf: 'Imprimir / PDF',
  tabClasses: 'Grupos',
  tabBalance: 'Equilibrio',
  tabChecks: 'Revisión',
  tabChecksN: 'Revisión ({n})',
  noBalanceItems: 'No hay criterios a equilibrar.',
  moveTitle: 'Mover a {who} →',
  moveTo: 'Mover a {cls}',
  boardHintWide: 'Haz clic o toca a un estudiante para moverlo a otro grupo. Los totales se actualizan al instante.',
  boardHintNarrow: 'Desliza a izquierda o derecha, o elige un grupo arriba. Toca a un estudiante para moverlo a otro grupo. Los totales se actualizan al instante.',
  prevClass: 'Grupo anterior',
  nextClass: 'Grupo siguiente',
  classPositionA11y: '{cls}, {i} de {n}',
  pairingsHeader: 'Condiciones',
  pairingsMet: '{ok} de {n} cumplidas',
  colorize: 'Colorear “juntos”',
  studentsN: '{n}',
  classChip: '{cls} · {n}',
  studentA11y: '{no} {name}, {cls}. Toca para moverlo a otro grupo',
  wantedBadgeA11y: 'Mantener juntos {label}',
  unwantedBadgeA11y: 'Separar {label}',
  notMetA11y: ', no se cumple',
  weightN: 'Peso {w}',
  average: 'Promedio',
  even: 'Parejo',
  offBy: 'Desvío {n}',
  target: 'Meta',
  allMet: 'Se cumplen todas las condiciones',
  allMetBody: 'Se aplicaron las {w} condiciones de “mantener juntos” y las {u} de “separar”.',
  noPairsBody: 'No se indicaron condiciones.',

  proTitle: 'Pro y ajustes',
  proName: 'FairClass Pro',
  active: '✓ Activo',
  proIntro: 'Cargar, editar, armar y ajustar los grupos es gratis y sin anuncios. Consigue Pro cuando necesites exportar o imprimir.',
  feat1Title: 'Exportar resultados a Excel y Google Drive',
  feat1Body:
    'Distribución, listas por grupo, una hoja por grupo, condiciones y resumen en un archivo .xlsx que puedes enviar a Excel, Google Drive o correo desde el menú de compartir. También puedes guardar tu lista editada con el formato de la plantilla (se abre igual en la versión web).',
  feat2Title: 'Imprimir o guardar en PDF para el consejo de profesores',
  feat2Body: 'Listas por grupo (con las condiciones en colores y una leyenda), más el resumen y las tablas de equilibrio, en hojas A4 verticales listas para imprimir o guardar en PDF.',
  feat3Title: 'Pagas una vez y es tuyo',
  feat3Body: 'Es un pago único, no una suscripción: nunca se te volverá a cobrar.',
  thanksPro: 'Gracias por usar Pro. Todas las funciones están disponibles.',
  buyWithPrice: 'Obtener Pro ({price}, pago único)',
  buy: 'Obtener Pro (pago único)',
  restore: 'Restaurar compra',
  language: 'Idioma',
  languageHint: 'De forma predeterminada se usa el idioma del dispositivo.',
  followDevice: 'Idioma del dispositivo',
  dataTitle: 'Sobre tus datos',
  dataBody: 'Las listas y los resultados se guardan solo en este dispositivo y nunca se suben a internet. Cuando exportas un Excel o un PDF, tú eliges a dónde enviarlo.',
  clearData: 'Borrar la lista y los resultados de este dispositivo',
  clearTitle: 'Borrar lista y resultados',
  clearBody: 'Se eliminarán la lista, los resultados y las distribuciones guardadas en este dispositivo. No se puede deshacer.',
  footer: 'FairClass · ayuda para armar grupos (versión web gratuita: https://ohru131.github.io/ClassClassify/)',

  purchaseStoreOnly: 'Las compras están disponibles en la app de Android (Google Play).',
  purchaseStatusFailed: 'No se pudo cargar la información de compra. Inténtalo más tarde.',
  purchaseSucceeded: '¡Gracias! Pro ya está activo. Es un pago único, así que no habrá más cobros.',
  purchasePending: 'Esperando a que se complete el pago. Pro se activará automáticamente cuando se confirme (algunos métodos de pago tardan un poco).',
  purchaseFailed: 'No se pudo completar la compra. Inténtalo de nuevo.',
  productLoadFailed: 'No se pudo cargar Pro desde la tienda. Revisa tu conexión e inténtalo de nuevo.',
  proRestored: 'Se restauró tu compra de Pro.',
  noRestorablePurchase: 'No se encontró ninguna compra de Pro para restaurar.',
  restoreFailed: 'No se pudo restaurar la compra. Inténtalo de nuevo.',

  parseRosterMissing: 'No se encontró la hoja “{sheet}” o no tiene datos',
  parseNoStudents: 'No hay estudiantes (escribe el N.º y el nombre desde la fila 3)',
  parseNoMissing: '{sheet}, fila {row}: “{name}” no tiene N.º y no se cargó',
  parseDuplicateNo: 'El N.º {no} está repetido',
  parseUnknownNo: '“{sheet}”, fila {row}: el N.º {no} no está en la lista',
  parseClassCountUnknown: 'No se pudo leer el número de grupos en “{sheet}”; se usaron {k} grupos',
  parseMaxTooSmall: 'Con un máximo de {max} estudiantes × {k} grupos no caben todos, así que no se aplicó el máximo',
  sharingUnavailable: 'No se pueden compartir archivos en este dispositivo.',
  popupBlocked: 'El navegador no pudo abrir una ventana nueva. Permite las ventanas emergentes en la configuración del navegador.',
  fileResults: 'distribucion-grupos',
  fileRoster: 'lista',
  fileTemplate: 'plantilla-fairclass',

  printTitle: 'Distribución de estudiantes en grupos',
  printCreated: 'Fecha: {date}',
  printClasses: 'grupos ({n} estudiantes)',
  printGap: 'diferencia de tamaño ({min}–{max})',
  printBalance: 'equilibrio',
  printViolations: 'condiciones no cumplidas',
  printPairings: 'Condiciones ({ok} de {n} cumplidas)',
  printLegendNote: '{w}N = mantener juntos (filas del mismo color), {u}N = separar. × indica una condición que no se pudo cumplir.',
  printNotMet: 'no se cumple',
  printClassLists: 'Listas por grupo',
  printColPair: 'Condición',
  printColMarks: 'Criterios',
  printSummary: 'Resumen y equilibrio',
  printUnmet: 'Condiciones no cumplidas',

  // アプリに保存（名前を付けて端末に保存）・保存した編成・前回とできるだけ入れ替える
  savedTitle: 'Distribuciones guardadas',
  savedEmpty: 'Todavía no hay nada guardado. En Resultados, toca “Guardar en la app” para conservar una distribución aquí.',
  savedMeta: '{date} · {n} estudiantes · {k} grupos',
  openSaved: 'Abrir',
  deleteSavedTitle: 'Eliminar distribución guardada',
  deleteSavedBody: '¿Eliminar “{name}” de este dispositivo? No se puede deshacer.',
  saveNamed: 'Guardar en la app',
  saveNamedHint: 'Se guarda con un nombre en este dispositivo. Ábrela cuando quieras desde “Distribuciones guardadas”, en la pestaña Lista.',
  saveNamedLeft: 'Versión gratuita: te quedan {n} de {max}.',
  saveNameLabel: 'Nombre',
  savedDone: 'Se guardó como “{name}”. Puedes abrirla cuando quieras desde la pestaña Lista.',
  saveFailed: 'No se pudo guardar. Inténtalo de nuevo.',
  fileSavedDone: 'Se guardó el archivo.',
  savedFromExcel: 'Datos al exportar a Excel ({file})',
  savedExcelHint: '“Datos al exportar a Excel” es la distribución en el momento de exportar. Si editaste el archivo de Excel exportado, cárgalo con “Elegir archivo de Excel” arriba.',
  savedExcelChip: '{name} (exportado a Excel)',
  exportKept: 'La distribución exportada también se guardó en Distribuciones guardadas (datos al exportar a Excel). Puedes abrirla desde la pestaña Lista.',
  resultUnplaced: '{n} estudiantes no tenían grupo en la hoja Distribución, así que solo se cargó la lista.',
  openFailed: 'No se pudo abrir esta distribución.',
  mixTitle: 'Mezclar respecto a la vez anterior',
  mixHelp: 'Quienes estuvieron en el mismo grupo la vez anterior quedan en grupos distintos, en la medida de lo posible.',
  mixPick: '¿Cuál fue la distribución anterior?',
  mixMatched: 'Se encontró el grupo anterior de {m} de {n} estudiantes.',
  mixNoSaved: 'Si tocas “Guardar en la app” en Resultados, la próxima vez podrás elegir esa distribución aquí. También puedes elegir un archivo de Excel exportado desde Resultados.',
  mixPickFile: 'Elegir un Excel exportado',
  mixFileInvalid: 'No se pudo leer una distribución de este archivo. Elige un archivo de Excel exportado desde Resultados.',
  mixNoMatch: 'No se encontró a ningún estudiante de esta lista en “{name}”.',
  prevClassColumn: 'Grupo anterior',
  mixFrom: 'Anterior: {name}',
  featSaveTitle: 'Distribuciones guardadas sin límite',
  featSaveBody: 'La versión gratuita guarda hasta {max}. Con Pro guardas todas las distribuciones de grupos y equipos, y puedes abrirlas cuando quieras o usarlas para mezclar respecto a la vez anterior.',
  saveLimitReached: 'La versión gratuita guarda hasta {max} distribuciones. Borra una anterior o consigue Pro para guardar todas las que quieras.',
  savedCount: '{n} de {max} guardadas (versión gratuita)',
  manageSaved: 'Ver distribuciones guardadas',
  seePro: 'Ver Pro',
  eraseFailed: 'No se pudo borrar todo. Inténtalo de nuevo.',
}
