import { PRIVACY_TITLE } from './privacy'
import type { CopyKey } from './en'

export const JA_COPY: Record<CopyKey, string> = {
  appEyebrow: 'FairClass · クラス編成',
  close: '閉じる',
  cancel: 'キャンセル',
  delete: '削除',
  save: '保存',
  edit: '編集',
  add: '追加',
  erase: '消去',
  tabRoster: '名簿',
  tabRun: '設定・実行',
  tabResults: '結果',
  tabPro: 'Pro・設定',
  privacyTitle: PRIVACY_TITLE['ja'],

  loadTitle: '名簿を読み込む',
  loadDesc: 'ひな形の Excel（Web 版と同じ形式）に生徒の様子を書き込んで選ぶか、サンプルや新しい名簿から始められます。名簿はこの端末の中だけに保存されます。',
  pickFile: 'Excel ファイルを選ぶ（.xlsx）',
  newRoster: '新しい名簿を作る',
  newRosterName: '新しい名簿',
  trySamples: 'サンプルで試す',
  getTemplate: 'Excel のひな形を入手',
  templateHint: 'ひな形には「設定」「生徒名簿」「同じ組ペア」「別の組ペア」のシートと項目の例が入っています。',
  privacyLink: 'データの扱い（プライバシーポリシー）›',
  samplePrefix: 'サンプル: {label}',

  rosterTitle: '名簿',
  backToRoster: 'キャンセル（今の名簿に戻る）',
  rosterSummary: '{n} 名 · 項目 {cols} · 同じ組 {w} 件 · 別の組 {u} 件',
  otherRoster: '別の名簿',
  saveRosterXlsx: '名簿を Excel で保存',
  toRun: '設定・実行へ',
  proFeaturesNote: 'Excel・印刷・PDF は Pro（買い切り）の機能です。',
  loadWarnings: '読み込み時の注意',
  tabStudents: '生徒 {n}',
  tabColumns: '項目・重み',
  tabWanted: '同じ組 {n}',
  tabUnwanted: '別の組 {n}',

  filterPlaceholder: '名前・NO・値で絞り込み',
  addStudent: '生徒を追加',
  countWide: '{shown} / {total} 名 · 生徒を押すと右側で編集できます',
  countNarrow: '{shown} / {total} 名 · 押して編集',
  selectToEdit: '一覧から生徒を選ぶと、ここで編集できます。',
  editStudentA11y: '{no} {name} を編集',
  noName: '（名前なし）',
  colNo: 'NO',
  colName: '名前',

  editStudent: '生徒の編集',
  namePlaceholder: '氏名',
  noInvalid: 'NO は 1 以上の数字で入れてください',
  noTaken: 'NO {no} は他の生徒が使っています',
  kindFlag: '該当',
  kindCategory: 'カテゴリ',
  kindNumeric: '数値',
  blank: '空欄',
  newValuePlaceholder: '新しい値を入れて決定',
  numberPlaceholder: '数値',
  valueA11y: '{col}の値',
  noColumns: 'まだ項目がありません。「項目・重み」タブから追加できます。',
  pairingsLabel: 'ペア指定',
  deleteStudent: 'この生徒を削除',
  deleteStudentTitle: '生徒を削除',
  deleteStudentBody: '{who} を名簿から削除します。ペア指定からも外れます。',

  columnsHelp:
    '重みが大きい項目ほど、各クラスに均等に分かれるよう優先します。0 にするとその項目は考えに入れません。値が1種類（○ と空欄）なら「該当」、数種類なら「カテゴリ」、7種類以上の数値は「数値」（平均をそろえる）として扱います。',
  deleteColumnA11y: '項目「{name}」を削除',
  deleteColumnTitle: '項目を削除',
  deleteColumnBody: '「{name}」を全員の名簿から削除します。',
  weight: '重み',
  weightA11y: '{name}の重み',
  decrease: '{label}を減らす',
  increase: '{label}を増やす',
  columnEmpty: '全員が空欄なので、この項目はまだ使われません。生徒の編集で値を入れてください。',
  addColumnTitle: '項目を追加',
  addColumnPlaceholder: '例: リーダー、ピアノ、通級',
  duplicateColumn: '同じ名前の項目があります',
  blankOnly: '（空欄のみ）',

  wantedTitle: '同じ組にする',
  unwantedTitle: '別の組にする',
  conditionsCount: '{n} 件',
  addCondition: '指定を追加',
  addConditionTitle: '「{kind}」指定を追加',
  editConditionTitle: '{label} を編集',
  wantedHelp: '選んだ生徒全員を同じ組にします（3人以上でも指定できます）。',
  unwantedHelp: '選んだ生徒どうしを、できる限り別々の組にします。',
  noConditions: '指定はありません。',
  conflict: '指定が食い違っています: {pairs} は「同じ組」でつながっているのに「別の組」にも指定されています。',
  conflictPair: '{a} と {b}',
  selectedNames: '選択中: {names}（2人以上）',
  selectedNone: 'なし',
  willDelete: '2人未満で保存するとこの指定は削除されます',
  filterNames: '名前・NO で絞り込み',

  runTitle: '設定・実行',
  loadFirst: 'まずは「名簿」タブで名簿を読み込んでください。',
  loadRosterBtn: '名簿を読み込む',
  classCount: 'クラス（グループ）数',
  classCountA11y: 'クラス数',
  perClass: '1組あたり {range} 名（{n} 名）',
  maxPerClass: '1クラスの最大人数',
  maxHint: '変えるとクラス数を自動で決めます',
  searchTime: '考える時間',
  quick: 'さっと 3秒',
  standard: 'ふつう 10秒',
  thorough: 'じっくり 30秒',
  timeInfo: '{s} 秒',
  timeInfoStarts: '{s} 秒 · {n} 通りの案からいちばん良い案を選びます',
  balancedItems: '均等にする項目',
  editAttributes: '項目・重みを編集',
  noEnabled: '均等にする項目がありません（人数だけをそろえます）。',
  pairsSummary: '同じ組にする {w} 件 · 別の組にする {u} 件',
  searching: 'バランスの良い組み合わせを考えています… {p}%',
  stop: 'やめる',
  runBtn: 'クラスを編成する',
  rerun: 'もう一度編成する',
  lastRun: '前回: {k} クラス · {starts} 通りの案 · {m}M 通りの組み合わせを試しました',
  tooFew: '生徒数（{n}名）がクラス数（{k}）より少ないので、編成できません。',
  discarded: '編成している間に名簿が変わったため、今回の結果は使えませんでした。もう一度編成してください。',

  resultsTitle: '結果',
  notYet: 'まだ編成していません。「設定・実行」タブで編成すると、ここに結果が出ます。',
  toRunBtn: '設定・実行へ',
  statClasses: 'クラス',
  statClassesSub: '{n} 名を編成',
  statGap: '人数差',
  statGapSub: '{min}〜{max} 名',
  statBalance: 'バランス',
  perfect: '完全',
  balancePerfectSub: '全項目が理想の範囲内',
  balanceSub: '理想の範囲からのずれ（人）',
  statViolations: '守れなかった指定',
  violationsSub: '守れなかったペア指定があります',
  violationsOk: 'ペア指定はすべて守れています',
  undoMoves: '手直しを元に戻す',
  shareXlsx: '結果を Excel で共有',
  saveToFile: 'ドライブ等に保存',
  print: '印刷',
  printPdf: '印刷・PDF',
  sharePdf: 'PDF で共有',
  tabClasses: 'クラス一覧',
  tabBalance: 'バランスの内訳',
  tabChecks: '指定の確認',
  tabChecksN: '指定の確認 ({n})',
  noBalanceItems: '均等にする項目がありません。',
  moveTitle: '{who} の移動先 →',
  moveTo: '{cls}へ移す',
  boardHintWide: '生徒を押すと別の組へ移せます。集計もすぐに変わります。',
  boardHintNarrow: '左右にスワイプするか、上の組を選んで切り替えます。生徒を押すと別の組へ移せます。集計もすぐに変わります。',
  prevClass: '前の組',
  nextClass: '次の組',
  classPositionA11y: '{cls}（{n} 組中 {i} 番目）',
  pairingsHeader: 'ペア指定',
  pairingsMet: '{ok} / {n} 件を満たしています',
  colorize: '同じ組を色分け',
  studentsN: '{n} 名',
  classChip: '{cls} {n}名',
  studentA11y: '{no} {name}、{cls}。タップして別の組へ移動',
  wantedBadgeA11y: '同じ組指定 {label}',
  unwantedBadgeA11y: '別の組指定 {label}',
  notMetA11y: '、満たせていません',
  weightN: '重み {w}',
  average: '平均値',
  even: '均等',
  offBy: 'ずれ {n}',
  target: '理想',
  allMet: 'すべての指定を守れています',
  allMetBody: '同じ組 {w} 件・別の組 {u} 件の指定をすべて反映できました。',
  noPairsBody: 'ペアの指定はありません。',

  proTitle: 'Pro・設定',
  proName: 'FairClass Pro',
  active: '✓ 利用中',
  proIntro: '名簿の読み込み・編集・編成・手直しは無料で、広告もありません。書き出しと印刷が必要になったら Pro をどうぞ。',
  feat1Title: '結果を Excel・Google ドライブへ書き出し',
  feat1Body:
    '組分け・クラス別名簿・各組・ペア指定・集計のシートを .xlsx にして、共有画面から Excel・Google ドライブ・メールなどへ送れます。編集した名簿もひな形と同じ形式で保存できます（Web 版でもそのまま読み込めます）。',
  feat2Title: '会議用に印刷・PDF',
  feat2Body: 'クラスごとの名簿（ペア指定の色分けと凡例つき）と集計・バランス表を A4 縦にまとめ、印刷または PDF にできます。',
  feat3Title: '一度の購入でずっと使える',
  feat3Body: '買い切りです。定期購入（サブスクリプション）ではないので、継続して請求されることはありません。',
  thanksPro: 'Pro をご利用いただきありがとうございます。すべての機能が使えます。',
  buyWithPrice: 'Pro を購入（{price}・買い切り）',
  buy: 'Pro を購入（買い切り）',
  restore: '購入を復元',
  language: '言語',
  languageHint: '既定では端末の言語に合わせます。',
  followDevice: '端末の設定',
  dataTitle: 'データについて',
  dataBody: '名簿と編成結果はこの端末の中だけに保存され、どこにも送信されません。書き出した Excel・PDF をどこへ送るかは、共有先をご自身で選べます。',
  clearData: 'この端末の名簿と結果を消去',
  clearTitle: '名簿と結果を消去',
  clearBody: 'この端末に保存している名簿・編成結果・保存した編成をすべて削除します。元には戻せません。',
  footer: 'FairClass · クラス編成のお手伝い（Web 版は無料・https://ohru131.github.io/ClassClassify/）',

  purchaseStoreOnly: '購入は iOS / Android のアプリ版でご利用いただけます。',
  revenueCatKeyMissing: '購入の準備がまだできていません。時間をおいてもう一度お試しください。',
  customerInfoFetchFailed: '購入の情報を確かめられませんでした。少し時間をおいて、もう一度お試しください。',
  purchaseSucceeded: 'ご購入ありがとうございます。Pro が有効になりました（買い切りのため、今後の請求はありません）。',
  purchaseNotApplied:
    'お支払いは完了しましたが、Pro をまだ有効にできていません。「購入を復元」を押してください。それでも有効にならない場合はサポートへご連絡ください（二重に請求されることはありません）。',
  purchaseFailed: '購入を完了できませんでした。もう一度お試しください。',
  productLoadFailed: 'ストアから Pro の情報を読み込めませんでした。インターネットにつながっているか確かめて、もう一度お試しください。',
  proRestored: 'Pro の購入を復元しました。',
  noRestorablePurchase: '復元できる Pro の購入が見つかりませんでした。',
  restoreFailed: '購入を復元できませんでした。もう一度お試しください。',

  parseRosterMissing: '「{sheet}」シートが見つからないか、データがありません',
  parseNoStudents: '生徒のデータがありません（3行目から下に NO と名前を入れてください）',
  parseNoMissing: '{sheet} {row}行目: 「{name}」の NO が空欄だったため、読み込んでいません',
  parseDuplicateNo: '出席番号 {no} が2人以上に付いています',
  parseUnknownNo: '「{sheet}」{row}行目: 出席番号 {no} は名簿にありません',
  parseClassCountUnknown: '「{sheet}」シートのクラス数が読み取れなかったので、{k} クラスにしました',
  parseMaxTooSmall: '1クラス最大 {max} 人 × {k} クラスでは全員が入りきらないため、最大人数の設定は使いませんでした',
  sharingUnavailable: 'この端末ではファイルの共有を利用できません。',
  popupBlocked: 'ブラウザが新しいウィンドウを開けませんでした。ブラウザの設定で許可してください。',
  fileResults: 'クラス編成結果',
  fileRoster: '名簿',
  fileTemplate: 'ひな形',

  printTitle: 'クラス編成結果',
  printCreated: '作成日: {date}',
  printClasses: 'クラス（{n} 名）',
  printGap: '人数差（{min}〜{max} 名）',
  printBalance: 'バランス',
  printViolations: '守れなかった指定',
  printPairings: 'ペア指定（{ok} / {n} 件を満たしています）',
  printLegendNote: '「{w}N」は同じ組にする指定（行を同じ色で塗り分け）、「{u}N」は別の組にする指定です。× は満たせていない指定です。',
  printNotMet: '満たせていません',
  printClassLists: 'クラス別名簿',
  printColPair: '指定',
  printColMarks: '該当',
  printSummary: '集計・バランス',
  printUnmet: '守れなかった指定',

  // 名前を付けて保存・保存した編成・前回とできるだけ入れ替える
  savedTitle: '保存した編成',
  savedEmpty: 'まだ保存した編成はありません。結果画面の「名前を付けて保存」で、ここに残せます。',
  savedMeta: '{date} · {n} 名 · {k} 組',
  openSaved: '開く',
  deleteSavedTitle: '保存した編成を削除',
  deleteSavedBody: '「{name}」をこの端末から削除します。元には戻せません。',
  saveNamed: '名前を付けて保存',
  saveNameLabel: '名前',
  savedDone: '「{name}」として保存しました。「名簿」タブからいつでも開けます。',
  saveFailed: '保存できませんでした。もう一度お試しください。',
  openFailed: 'この編成を開けませんでした。',
  mixTitle: '前回とできるだけ入れ替える',
  mixHelp: '前回同じ組だった子が、新しい組ではできるだけ別々になるようにします。',
  mixPick: '前回の編成を選んでください',
  mixMatched: '{n} 名中 {m} 名の前回の組が分かりました。',
  mixNoSaved: '結果画面で「名前を付けて保存」しておくと、次回ここで前回の編成として選べます。',
  prevClassColumn: '前回の組',
  mixFrom: '前回: {name}',
}
