import { PRIVACY_TITLE } from './privacy'
import type { CopyKey } from './en'

// 합니다체로 통일. 용어는 docs/i18n-glossary.md（반 편성・같은 반 배정・분리 배정）
export const KO_COPY: Record<CopyKey, string> = {
  appEyebrow: 'FairClass · 반 편성',
  close: '닫기',
  cancel: '취소',
  delete: '삭제',
  save: '저장',
  edit: '편집',
  add: '추가',
  erase: '지우기',
  tabRoster: '명단',
  tabRun: '설정·실행',
  tabResults: '결과',
  tabPro: 'Pro·설정',
  privacyTitle: PRIVACY_TITLE['ko'],

  loadTitle: '명단 불러오기',
  loadDesc: '엑셀 양식(웹 버전과 같은 형식)에 학생 특성을 입력해 선택하거나, 예시나 빈 명단으로 시작하십시오. 명단은 이 기기에만 저장됩니다.',
  pickFile: '엑셀 파일 선택(.xlsx)',
  newRoster: '빈 명단 만들기',
  newRosterName: '새 명단',
  trySamples: '예시로 해 보기',
  getTemplate: '엑셀 양식 받기',
  templateHint: '양식에는 설정, 학생 명단, 같은 반 배정, 분리 배정 시트와 항목 예시가 들어 있습니다.',
  privacyLink: '데이터 처리 방식(개인정보 처리방침) ›',
  samplePrefix: '예시: {label}',

  rosterTitle: '명단',
  backToRoster: '취소(현재 명단으로 돌아가기)',
  rosterSummary: '학생 {n}명 · 항목 {cols}개 · 같은 반 {w}건 · 분리 {u}건',
  otherRoster: '다른 명단',
  saveRosterXlsx: '명단을 엑셀로 저장',
  toRun: '설정으로',
  proFeaturesNote: '엑셀 내보내기, 인쇄, PDF는 Pro(1회 구매) 기능입니다.',
  loadWarnings: '불러올 때의 안내',
  tabStudents: '학생 {n}',
  tabColumns: '항목·가중치',
  tabWanted: '같은 반 {n}',
  tabUnwanted: '분리 {n}',

  filterPlaceholder: '이름·번호·값으로 찾기',
  addStudent: '학생 추가',
  countWide: '{shown} / {total}명 · 행을 누르면 오른쪽에서 편집할 수 있습니다',
  countNarrow: '{shown} / {total}명 · 눌러서 편집',
  selectToEdit: '목록에서 학생을 선택하면 여기에서 편집할 수 있습니다.',
  editStudentA11y: '{no} {name} 편집',
  noName: '(이름 없음)',
  colNo: '번호',
  colName: '이름',

  editStudent: '학생 편집',
  namePlaceholder: '이름',
  noInvalid: '1 이상의 정수를 입력하십시오',
  noTaken: '번호 {no}은(는) 다른 학생이 사용 중입니다',
  kindFlag: '해당',
  kindCategory: '범주',
  kindNumeric: '숫자',
  blank: '빈칸',
  newValuePlaceholder: '새 값을 입력하고 Enter',
  numberPlaceholder: '숫자',
  valueA11y: '{col} 값',
  noColumns: '항목이 없습니다. "항목·가중치" 탭에서 추가하십시오.',
  pairingsLabel: '배정 조건',
  deleteStudent: '이 학생 삭제',
  deleteStudentTitle: '학생 삭제',
  deleteStudentBody: '{who} 학생을 명단과 배정 조건에서 삭제합니다.',

  columnsHelp:
    '가중치가 큰 항목일수록 먼저 각 반에 고르게 나눕니다. 0이면 그 항목은 반영하지 않습니다. 값이 한 종류(✓와 빈칸)면 "해당", 몇 종류면 "범주", 7종류 이상의 숫자는 "숫자"(반 평균을 맞춤)로 처리합니다.',
  deleteColumnA11y: '항목 "{name}" 삭제',
  deleteColumnTitle: '항목 삭제',
  deleteColumnBody: '모든 학생의 명단에서 "{name}" 항목을 삭제합니다.',
  weight: '가중치',
  weightA11y: '{name} 가중치',
  decrease: '{label} 줄이기',
  increase: '{label} 늘리기',
  columnEmpty: '모든 학생이 빈칸이라 이 항목은 사용되지 않습니다. 학생 편집에서 값을 입력하십시오.',
  addColumnTitle: '항목 추가',
  addColumnPlaceholder: '예: 반장, 피아노, 학습 지원',
  duplicateColumn: '같은 이름의 항목이 있습니다',
  blankOnly: '(빈칸만)',

  wantedTitle: '같은 반 배정',
  unwantedTitle: '분리 배정',
  conditionsCount: '{n}건',
  addCondition: '조건 추가',
  addConditionTitle: '"{kind}" 조건 추가',
  editConditionTitle: '{label} 편집',
  wantedHelp: '선택한 학생 모두를 같은 반에 배정합니다(3명 이상도 가능).',
  unwantedHelp: '선택한 학생들을 서로 다른 반에 배정합니다.',
  noConditions: '조건이 없습니다.',
  conflict: '서로 맞지 않는 조건이 있습니다: {pairs} 학생은 "같은 반 배정"으로 이어져 있지만 "분리 배정"에도 지정되어 있습니다.',
  conflictPair: '{a}, {b}',
  selectedNames: '선택: {names}(2명 이상)',
  selectedNone: '없음',
  willDelete: '2명 미만으로 저장하면 이 조건은 삭제됩니다',
  filterNames: '이름·번호로 찾기',

  runTitle: '설정·실행',
  loadFirst: '먼저 "명단" 탭에서 명단을 불러오십시오.',
  loadRosterBtn: '명단 불러오기',
  classCount: '반(모둠) 수',
  classCountA11y: '반 수',
  perClass: '반마다 {range}명(총 {n}명)',
  maxPerClass: '반별 최대 인원',
  maxHint: '바꾸면 반 수를 자동으로 정합니다',
  searchTime: '탐색 시간',
  quick: '빠르게 3초',
  standard: '표준 10초',
  thorough: '꼼꼼하게 30초',
  timeInfo: '{s}초',
  timeInfoStarts: '{s}초 · {n}번 탐색해 가장 좋은 안을 선택',
  balancedItems: '고르게 나눌 항목',
  editAttributes: '항목 편집',
  noEnabled: '사용 중인 항목이 없습니다(인원만 맞춥니다).',
  pairsSummary: '같은 반 배정 {w}건 · 분리 배정 {u}건',
  searching: '가장 좋은 조합을 찾는 중… {p}%',
  stop: '중지',
  runBtn: '반 편성 실행',
  rerun: '다시 편성',
  lastRun: '이전: {k}개 반 · {starts}번 · {m}M회 탐색',
  tooFew: '학생 수({n}명)가 반 수({k}개)보다 적어 편성할 수 없습니다.',
  discarded: '실행 중에 명단이 바뀌어 결과를 버렸습니다. 다시 실행하십시오.',

  resultsTitle: '결과',
  notYet: '아직 편성하지 않았습니다. "설정·실행" 탭에서 실행하면 여기에 결과가 표시됩니다.',
  toRunBtn: '설정·실행으로',
  statClasses: '반',
  statClassesSub: '학생 {n}명 편성',
  statGap: '인원 차',
  statGapSub: '{min}~{max}명',
  statBalance: '균형',
  perfect: '완벽',
  balancePerfectSub: '모든 항목이 목표 범위 안',
  balanceSub: '목표 범위를 벗어난 인원',
  statViolations: '충족하지 못한 조건',
  violationsSub: '충족하지 못한 배정 조건이 있습니다',
  violationsOk: '배정 조건을 모두 충족합니다',
  undoMoves: '직접 옮긴 것 되돌리기',
  shareXlsx: '결과를 엑셀로 공유',
  saveToFile: '드라이브·기기에 저장',
  print: '인쇄',
  printPdf: '인쇄 / PDF',
  sharePdf: 'PDF로 공유',
  tabClasses: '반별 명단',
  tabBalance: '균형 분석',
  tabChecks: '조건 확인',
  tabChecksN: '조건 확인 ({n})',
  noBalanceItems: '고르게 나눌 항목이 없습니다.',
  moveTitle: '{who} 이동 →',
  moveTo: '{cls}(으)로 이동',
  boardHintWide: '학생을 누르면 다른 반으로 옮길 수 있습니다. 집계는 바로 다시 계산됩니다.',
  boardHintNarrow: '좌우로 밀거나 위에서 반을 고르십시오. 학생을 누르면 다른 반으로 옮길 수 있습니다. 집계는 바로 다시 계산됩니다.',
  prevClass: '이전 반',
  nextClass: '다음 반',
  classPositionA11y: '{cls}, {n}개 반 중 {i}번째',
  pairingsHeader: '배정 조건',
  pairingsMet: '{n}건 중 {ok}건 충족',
  colorize: '같은 반 배정 색 표시',
  studentsN: '{n}명',
  classChip: '{cls} {n}명',
  studentA11y: '{no} {name}, {cls}. 눌러서 다른 반으로 이동',
  wantedBadgeA11y: '같은 반 배정 {label}',
  unwantedBadgeA11y: '분리 배정 {label}',
  notMetA11y: ', 충족하지 못함',
  weightN: '가중치 {w}',
  average: '평균',
  even: '균등',
  offBy: '차이 {n}',
  target: '목표',
  allMet: '모든 조건을 충족합니다',
  allMetBody: '같은 반 배정 {w}건, 분리 배정 {u}건을 모두 반영했습니다.',
  noPairsBody: '배정 조건이 없습니다.',

  proTitle: 'Pro·설정',
  proName: 'FairClass Pro',
  active: '✓ 사용 중',
  proIntro: '명단 불러오기·편집·반 편성·수정은 무료이며 광고도 없습니다. 내보내기와 인쇄가 필요할 때 Pro를 이용하십시오.',
  feat1Title: '결과를 엑셀·Google 드라이브로 내보내기',
  feat1Body:
    '반 편성, 반별 명단, 반마다의 시트, 배정 조건, 집계를 .xlsx 파일로 만들어 공유 화면에서 엑셀, Google 드라이브, 메일 등으로 보낼 수 있습니다. 편집한 명단도 양식과 같은 형식으로 저장할 수 있습니다(웹 버전에서도 그대로 열 수 있습니다).',
  feat2Title: '회의용 인쇄·PDF',
  feat2Body: '반별 명단(배정 조건 색 구분과 범례 포함)과 집계·균형 표를 A4 세로로 정리해 인쇄하거나 PDF로 만들 수 있습니다.',
  feat3Title: '한 번 구매로 계속 사용',
  feat3Body: '1회 구매입니다. 정기 결제(구독)가 아니므로 추가 요금이 청구되지 않습니다.',
  thanksPro: 'Pro를 이용해 주셔서 감사합니다. 모든 기능을 사용할 수 있습니다.',
  buyWithPrice: 'Pro 구매({price}, 1회 구매)',
  buy: 'Pro 구매(1회 구매)',
  restore: '구매 복원',
  language: '언어',
  languageHint: '기본적으로 기기 언어를 따릅니다.',
  followDevice: '기기 설정',
  dataTitle: '데이터 안내',
  dataBody: '명단과 편성 결과는 이 기기에만 저장되며 어디에도 전송되지 않습니다. 엑셀이나 PDF로 내보낼 때는 보낼 곳을 직접 선택합니다.',
  clearData: '이 기기의 명단과 결과 지우기',
  clearTitle: '명단과 결과 지우기',
  clearBody: '이 기기에 저장된 명단과 편성 결과를 삭제합니다. 되돌릴 수 없습니다.',
  footer: 'FairClass · 반 편성 최적화 도구(웹 버전 무료: https://ohru131.github.io/ClassClassify/)',

  purchaseStoreOnly: '구매는 iOS / Android 앱에서 이용할 수 있습니다.',
  revenueCatKeyMissing: 'RevenueCat 공개 SDK 키가 설정되지 않았습니다.',
  customerInfoFetchFailed: '구매 정보를 불러오지 못했습니다. 잠시 후 다시 시도하십시오.',
  purchaseSucceeded: '구매해 주셔서 감사합니다. Pro가 활성화되었습니다(1회 구매라 추가 요금은 없습니다).',
  purchaseNotApplied:
    '결제는 완료되었지만 아직 Pro가 활성화되지 않았습니다. "구매 복원"을 눌러 주십시오. 그래도 활성화되지 않으면 지원팀에 문의하십시오(이중으로 청구되지 않습니다).',
  purchaseFailed: '구매를 완료하지 못했습니다. 다시 시도하십시오.',
  productLoadFailed: '스토어에서 Pro 상품을 불러오지 못했습니다. 네트워크를 확인하고 다시 시도하십시오.',
  proRestored: 'Pro 구매를 복원했습니다.',
  noRestorablePurchase: '복원할 Pro 구매 내역이 없습니다.',
  restoreFailed: '구매를 복원하지 못했습니다. 다시 시도하십시오.',

  parseRosterMissing: '"{sheet}" 시트가 없거나 데이터가 없습니다',
  parseNoStudents: '학생 데이터가 없습니다(3행부터 번호와 이름을 입력하십시오)',
  parseNoMissing: '{sheet} {row}행: "{name}" 학생의 번호가 비어 있어 불러오지 않았습니다',
  parseDuplicateNo: '번호 {no}이(가) 중복되었습니다',
  parseUnknownNo: '"{sheet}" {row}행: 번호 {no}은(는) 명단에 없습니다',
  parseClassCountUnknown: '"{sheet}" 시트의 반 수를 읽을 수 없어 {k}개 반으로 정했습니다',
  parseMaxTooSmall: '반별 최대 {max}명 × {k}개 반으로는 모두 들어가지 않아 최대 인원은 무시했습니다',
  sharingUnavailable: '이 기기에서는 파일 공유를 사용할 수 없습니다.',
  popupBlocked: '팝업이 차단되었습니다. 브라우저 설정에서 허용하십시오.',
  fileResults: '반편성_결과',
  fileRoster: '명단',
  fileTemplate: '양식',

  printTitle: '반 편성 결과',
  printCreated: '작성일: {date}',
  printClasses: '개 반(학생 {n}명)',
  printGap: '인원 차({min}~{max}명)',
  printBalance: '균형',
  printViolations: '충족하지 못한 조건',
  printPairings: '배정 조건({n}건 중 {ok}건 충족)',
  printLegendNote: '"{w}N"은 같은 반 배정(같은 색으로 표시), "{u}N"은 분리 배정입니다. ×는 충족하지 못한 조건입니다.',
  printNotMet: '충족하지 못함',
  printClassLists: '반별 명단',
  printColPair: '조건',
  printColMarks: '해당 항목',
  printSummary: '집계·균형',
  printUnmet: '충족하지 못한 조건',
}
