import { PRIVACY_TITLE } from './privacy'
import type { CopyKey } from './en'

// Português do Brasil, tratamento “você”. Termos: docs/i18n-glossary.md（turma, manter juntos, separar）
export const PT_BR_COPY: Record<CopyKey, string> = {
  appEyebrow: 'FairClass · Enturmação',
  close: 'Fechar',
  cancel: 'Cancelar',
  delete: 'Excluir',
  save: 'Salvar',
  edit: 'Editar',
  add: 'Adicionar',
  erase: 'Apagar',
  tabRoster: 'Lista',
  tabRun: 'Configurar',
  tabResults: 'Resultado',
  tabPro: 'Pro',
  privacyTitle: PRIVACY_TITLE['pt-BR'],

  loadTitle: 'Carregar lista de alunos',
  loadDesc: 'Preencha o modelo de Excel (mesmo formato da versão web) e escolha o arquivo, ou comece com um exemplo ou uma lista em branco. A lista fica salva só neste aparelho.',
  pickFile: 'Escolher arquivo do Excel (.xlsx)',
  newRoster: 'Criar lista em branco',
  newRosterName: 'Nova lista',
  trySamples: 'Testar com um exemplo',
  getTemplate: 'Baixar o modelo de Excel',
  templateHint: 'O modelo tem as abas Configurações, Lista de alunos, Manter juntos e Separar, com critérios de exemplo. Ao escolher um arquivo do Excel exportado em Resultado, ele abre com a enturmação.',
  privacyLink: 'Como seus dados são tratados (política de privacidade) ›',
  samplePrefix: 'Exemplo: {label}',

  rosterTitle: 'Lista de alunos',
  backToRoster: 'Cancelar (voltar à lista atual)',
  rosterSummary: '{n} alunos · {cols} critérios · juntos {w} · separar {u}',
  otherRoster: 'Abrir outra lista',
  saveRosterXlsx: 'Exportar lista para Excel',
  toRun: 'Ir para Configurar',
  proFeaturesNote: 'Exportar para Excel é um recurso Pro (compra única).',
  loadWarnings: 'Avisos ao carregar',
  tabStudents: 'Alunos {n}',
  tabColumns: 'Critérios',
  tabWanted: 'Juntos {n}',
  tabUnwanted: 'Separar {n}',

  filterPlaceholder: 'Filtrar por nome, nº ou valor',
  addStudent: 'Adicionar aluno',
  countWide: '{shown} / {total} alunos · clique em uma linha para editar à direita',
  countNarrow: '{shown} / {total} alunos · toque para editar',
  selectToEdit: 'Escolha um aluno na lista para editar aqui.',
  editStudentA11y: 'Editar {no} {name}',
  noName: '(sem nome)',
  colNo: 'Nº',
  colName: 'Nome',

  editStudent: 'Editar aluno',
  namePlaceholder: 'Nome completo',
  noInvalid: 'Digite um número a partir de 1',
  noTaken: 'O nº {no} já é de outro aluno',
  kindFlag: 'Caixa de seleção',
  kindCategory: 'Lista',
  kindDegree: 'Nível (1–5)',
  kindNumeric: 'Número',
  blank: 'Vazio',
  newValuePlaceholder: 'Digite uma nova opção e tecle Enter',
  numberPlaceholder: 'Número',
  valueA11y: 'Valor de {col}',
  noColumns: 'Ainda não há critérios. Adicione na aba “Critérios”.',
  pairingsLabel: 'Condições',
  deleteStudent: 'Excluir este aluno',
  deleteStudentTitle: 'Excluir aluno',
  deleteStudentBody: '{who} será removido da lista e de todas as condições.',

  columnsHelp:
    'Critérios com peso maior são distribuídos primeiro de forma equilibrada entre as turmas. Com peso 0, o critério não é levado em conta. A caixa de seleção equilibra quantos alunos estão marcados, a lista ou o nível (1–5) equilibra cada opção ou nível, e o número (7 ou mais valores diferentes) equilibra as médias das turmas.',
  deleteColumnA11y: 'Excluir o critério “{name}”',
  deleteColumnTitle: 'Excluir critério',
  deleteColumnBody: '“{name}” será removido de todos os alunos.',
  weight: 'Peso',
  weightA11y: 'Peso de {name}',
  decrease: '{label}: diminuir',
  increase: '{label}: aumentar',
  columnEmpty: 'Todos estão vazios, então este critério não é usado. Preencha os valores ao editar os alunos.',
  addColumnTitle: 'Adicionar critério',
  addColumnPlaceholder: 'ex.: Líder, Piano, Apoio na leitura',
  duplicateColumn: 'Já existe um critério com esse nome',
  blankOnly: '(só vazios)',
  listOptions: 'Opções',
  addOptionChip: '+ Adicionar opção',
  editOptionA11y: 'Renomear a opção {v}',
  deleteOptionA11y: 'Excluir a opção {v}',
  deleteOptionTitle: 'Excluir opção',
  deleteOptionBody: '"{v}" será excluída da lista. Os {n} alunos que a escolheram ficarão vazios.',
  duplicateOption: 'Essa opção já existe',
  listOptionsHint: 'Opções que ninguém escolheu não são mantidas ao exportar para Excel.',
  sampleExcelA11y: 'Baixar "{label}" em Excel',
  samplesExcelHint: 'Toque em ⬇ para baixar um exemplo em Excel. Edite e carregue com "Escolher arquivo do Excel".',
  currentRoster: 'Lista aberta',

  wantedTitle: 'Manter juntos',
  unwantedTitle: 'Separar',
  conditionsCount: '{n}',
  addCondition: 'Adicionar',
  addConditionTitle: 'Adicionar condição “{kind}”',
  editConditionTitle: 'Editar {label}',
  wantedHelp: 'Todos os alunos escolhidos ficam na mesma turma (pode ser 3 ou mais).',
  unwantedHelp: 'Os alunos escolhidos ficam em turmas diferentes entre si, na medida do possível.',
  noConditions: 'Ainda não há condições.',
  conflict: 'Há condições contraditórias: {pairs} estão ligados por “manter juntos”, mas também marcados para “separar”.',
  conflictPair: '{a} e {b}',
  selectedNames: 'Selecionados: {names} (2 ou mais)',
  selectedNone: 'nenhum',
  willDelete: 'Salvar com menos de 2 alunos exclui esta condição',
  filterNames: 'Filtrar por nome ou nº',

  runTitle: 'Configurar e montar',
  loadFirst: 'Primeiro carregue uma lista na aba “Lista”.',
  loadRosterBtn: 'Carregar lista',
  classCount: 'Número de turmas',
  classCountA11y: 'Número de turmas',
  perClass: '{range} alunos por turma ({n} no total)',
  maxPerClass: 'Máximo por turma',
  maxHint: 'Ao mudar, o número de turmas é calculado',
  searchTime: 'Tempo para montar',
  quick: 'Rápido 3 s',
  standard: 'Padrão 10 s',
  thorough: 'Completo 30 s',
  timeInfo: '{s} s',
  timeInfoStarts: '{s} s · compara {n} opções e escolhe a melhor',
  balancedItems: 'Critérios a equilibrar',
  editAttributes: 'Editar critérios',
  noEnabled: 'Nenhum critério para equilibrar (só o tamanho das turmas será equilibrado).',
  pairsSummary: 'Manter juntos: {w} · Separar: {u}',
  searching: 'Procurando uma distribuição equilibrada… {p}%',
  stop: 'Parar',
  runBtn: 'Montar turmas',
  rerun: 'Montar de novo',
  lastRun: 'Da última vez: {k} turmas · {starts} opções · {m} mi combinações testadas',
  tooFew: 'Há menos alunos ({n}) do que turmas ({k}).',
  discarded: 'A lista mudou enquanto as turmas eram montadas, então este resultado não foi usado. Monte de novo.',

  resultsTitle: 'Resultado',
  notYet: 'Ainda não há turmas. Toque em “Montar turmas” na aba Configurar para ver o resultado aqui.',
  toRunBtn: 'Ir para Configurar',
  statClasses: 'Turmas',
  statClassesSub: '{n} alunos distribuídos',
  statGap: 'Diferença de tamanho',
  statGapSub: '{min}–{max} alunos',
  statBalance: 'Equilíbrio',
  perfect: 'Perfeito',
  balancePerfectSub: 'Todos os critérios na faixa ideal',
  balanceSub: 'Alunos fora da faixa ideal',
  statViolations: 'Condições não atendidas',
  violationsSub: 'Algumas condições não puderam ser atendidas',
  violationsOk: 'Todas as condições atendidas',
  undoMoves: 'Desfazer minhas mudanças',
  saveToFile: 'Salvar como arquivo',
  keepTitle: 'Guardar esta enturmação',
  exportTitle: 'Exportar como arquivo',
  exportExcel: 'Excel',
  exportPdf: 'PDF',
  exportSheetTitle: 'Para onde enviar o arquivo {format}?',
  shareVia: 'Compartilhar',
  shareViaSub: 'Envie por WhatsApp, e-mail ou outro app',
  saveToFileSub: 'Salve no Google Drive ou numa pasta do aparelho',
  exportProNote: 'Excel, PDF e impressão vêm com o Pro (compra única). Toque em um deles para saber mais.',
  print: 'Imprimir',
  printPdf: 'Imprimir / PDF',
  tabClasses: 'Turmas',
  tabBalance: 'Equilíbrio',
  tabChecks: 'Verificação',
  tabChecksN: 'Verificação ({n})',
  noBalanceItems: 'Não há critérios a equilibrar.',
  moveTitle: 'Mover {who} →',
  moveTo: 'Mover para {cls}',
  boardHintWide: 'Clique ou toque em um aluno para movê-lo para outra turma. Os totais se atualizam na hora.',
  boardHintNarrow: 'Deslize para os lados ou escolha uma turma acima. Toque em um aluno para movê-lo para outra turma. Os totais se atualizam na hora.',
  prevClass: 'Turma anterior',
  nextClass: 'Próxima turma',
  classPositionA11y: '{cls}, {i} de {n}',
  pairingsHeader: 'Condições',
  pairingsMet: '{ok} de {n} atendidas',
  colorize: 'Colorir “juntos”',
  studentsN: '{n}',
  classChip: '{cls} · {n}',
  studentA11y: '{no} {name}, {cls}. Toque para mover para outra turma',
  wantedBadgeA11y: 'Manter juntos {label}',
  unwantedBadgeA11y: 'Separar {label}',
  notMetA11y: ', não atendida',
  weightN: 'Peso {w}',
  average: 'Média',
  even: 'Equilibrado',
  offBy: 'Desvio {n}',
  target: 'Meta',
  allMet: 'Todas as condições atendidas',
  allMetBody: 'As {w} condições de “manter juntos” e as {u} de “separar” foram aplicadas.',
  noPairsBody: 'Nenhuma condição foi definida.',

  proTitle: 'Pro e ajustes',
  proName: 'FairClass Pro',
  active: '✓ Ativo',
  proIntro: 'Carregar, editar, montar e ajustar turmas é grátis e sem anúncios. Adquira o Pro quando precisar exportar ou imprimir.',
  feat1Title: 'Exportar resultados para Excel e Google Drive',
  feat1Body:
    'Enturmação, listas por turma, uma aba por turma, condições e resumo em um arquivo .xlsx para enviar ao Excel, Google Drive ou e-mail pelo menu de compartilhar. Você também pode salvar a lista editada no formato do modelo (abre igual na versão web).',
  feat2Title: 'Imprimir ou salvar em PDF para o conselho de classe',
  feat2Body: 'Listas por turma (com as condições coloridas e legenda), além do resumo e das tabelas de equilíbrio, em páginas A4 retrato prontas para imprimir ou salvar em PDF.',
  feat3Title: 'Compre uma vez, use para sempre',
  feat3Body: 'É uma compra única, não uma assinatura: você não será cobrado de novo.',
  thanksPro: 'Obrigado por usar o Pro. Todos os recursos estão liberados.',
  buyWithPrice: 'Adquirir Pro ({price}, compra única)',
  buy: 'Adquirir Pro (compra única)',
  restore: 'Restaurar compra',
  language: 'Idioma',
  languageHint: 'Por padrão, o app segue o idioma do aparelho.',
  followDevice: 'Idioma do aparelho',
  dataTitle: 'Sobre seus dados',
  dataBody: 'As listas e os resultados ficam salvos só neste aparelho e nunca são enviados para a internet. Ao exportar um Excel ou PDF, você escolhe para onde enviar.',
  clearData: 'Apagar a lista e o resultado deste aparelho',
  clearTitle: 'Apagar lista e resultado',
  clearBody: 'A lista, o resultado e as enturmações salvas neste aparelho serão apagados. Não é possível desfazer.',
  footer: 'FairClass · ajuda para montar turmas (versão web gratuita: https://ohru131.github.io/ClassClassify/)',

  purchaseStoreOnly: 'As compras estão disponíveis no app para iOS ou Android.',
  revenueCatKeyMissing: 'As compras ainda não estão disponíveis. Tente mais tarde.',
  customerInfoFetchFailed: 'Não foi possível carregar as informações de compra. Tente mais tarde.',
  purchaseSucceeded: 'Obrigado! O Pro está ativo. É uma compra única, sem novas cobranças.',
  purchaseNotApplied:
    'O pagamento foi concluído, mas o Pro ainda não está ativo. Toque em “Restaurar compra”. Se continuar sem ativar, fale com o suporte — você não será cobrado duas vezes.',
  purchaseFailed: 'Não foi possível concluir a compra. Tente de novo.',
  productLoadFailed: 'Não foi possível carregar o Pro da loja. Verifique a conexão e tente de novo.',
  proRestored: 'Sua compra do Pro foi restaurada.',
  noRestorablePurchase: 'Nenhuma compra do Pro para restaurar foi encontrada.',
  restoreFailed: 'Não foi possível restaurar a compra. Tente de novo.',

  parseRosterMissing: 'A aba “{sheet}” não foi encontrada ou está vazia',
  parseNoStudents: 'Nenhum aluno encontrado (preencha nº e nome a partir da linha 3)',
  parseNoMissing: '{sheet}, linha {row}: “{name}” está sem nº e não foi carregado',
  parseDuplicateNo: 'O nº {no} está repetido',
  parseUnknownNo: '“{sheet}”, linha {row}: o nº {no} não está na lista',
  parseClassCountUnknown: 'Não foi possível ler o número de turmas em “{sheet}”; foram usadas {k} turmas',
  parseMaxTooSmall: 'Com no máximo {max} alunos × {k} turmas não cabem todos, então o máximo não foi aplicado',
  sharingUnavailable: 'Não é possível compartilhar arquivos neste aparelho.',
  popupBlocked: 'O navegador não conseguiu abrir uma nova janela. Permita pop-ups nas configurações do navegador.',
  fileResults: 'enturmacao',
  fileRoster: 'lista-de-alunos',
  fileTemplate: 'modelo-fairclass',

  printTitle: 'Enturmação',
  printCreated: 'Criado em: {date}',
  printClasses: 'turmas ({n} alunos)',
  printGap: 'diferença de tamanho ({min}–{max})',
  printBalance: 'equilíbrio',
  printViolations: 'condições não atendidas',
  printPairings: 'Condições ({ok} de {n} atendidas)',
  printLegendNote: '{w}N = manter juntos (linhas da mesma cor), {u}N = separar. × indica condição que não pôde ser atendida.',
  printNotMet: 'não atendida',
  printClassLists: 'Listas por turma',
  printColPair: 'Condição',
  printColMarks: 'Critérios',
  printSummary: 'Resumo e equilíbrio',
  printUnmet: 'Condições não atendidas',

  // アプリに保存（名前を付けて端末に保存）・保存した編成・前回とできるだけ入れ替える
  savedTitle: 'Enturmações salvas',
  savedEmpty: 'Ainda não há nada salvo. Em Resultado, toque em “Salvar no app” para guardar uma enturmação aqui.',
  savedMeta: '{date} · {n} alunos · {k} turmas',
  openSaved: 'Abrir',
  deleteSavedTitle: 'Excluir enturmação salva',
  deleteSavedBody: 'Excluir “{name}” deste aparelho? Não dá para desfazer.',
  saveNamed: 'Salvar no app',
  saveNamedHint: 'Fica salva com um nome neste aparelho. Abra quando quiser em “Enturmações salvas”, na aba Lista.',
  saveNamedLeft: 'Versão gratuita: restam {n} de {max}.',
  saveNameLabel: 'Nome',
  savedDone: 'Salvo como “{name}”. Você pode abrir quando quiser na aba Lista.',
  saveFailed: 'Não foi possível salvar. Tente de novo.',
  fileSavedDone: 'Arquivo salvo.',
  savedFromExcel: 'Dados da exportação para Excel ({file})',
  savedExcelHint: '“Dados da exportação para Excel” é a enturmação no momento da exportação. Se você editou o arquivo do Excel exportado, carregue esse arquivo em “Escolher arquivo do Excel” acima.',
  savedExcelChip: '{name} (exportado para Excel)',
  exportKept: 'A enturmação exportada também foi guardada em Enturmações salvas (dados da exportação para Excel). Você pode abrir na aba Lista.',
  resultUnplaced: '{n} alunos estavam sem turma na aba Enturmação, então só a lista foi carregada.',
  openFailed: 'Não foi possível abrir esta enturmação.',
  mixTitle: 'Misturar em relação à última vez',
  mixHelp: 'Quem esteve na mesma turma da última vez fica em turmas diferentes, na medida do possível.',
  mixPick: 'Qual foi a enturmação anterior?',
  mixMatched: 'Encontramos a turma anterior de {m} de {n} alunos.',
  mixNoSaved: 'Se você tocar em “Salvar no app” em Resultado, poderá escolher essa enturmação aqui da próxima vez. Você também pode escolher um arquivo do Excel exportado em Resultado.',
  mixPickFile: 'Escolher um Excel exportado',
  mixFileInvalid: 'Não foi possível ler uma enturmação deste arquivo. Escolha um arquivo do Excel exportado em Resultado.',
  mixNoMatch: 'Nenhum aluno desta lista foi encontrado em “{name}”.',
  prevClassColumn: 'Turma anterior',
  mixFrom: 'Anterior: {name}',
  featSaveTitle: 'Enturmações salvas sem limite',
  featSaveBody: 'A versão gratuita guarda até {max}. Com o Pro, você guarda todas as enturmações e divisões em grupos, abre quando quiser e usa para misturar em relação à última vez.',
  saveLimitReached: 'A versão gratuita guarda até {max} enturmações. Apague uma mais antiga ou use o Pro para salvar quantas quiser.',
  savedCount: '{n} de {max} salvas (versão gratuita)',
  manageSaved: 'Ver enturmações salvas',
  seePro: 'Ver o Pro',
  eraseFailed: 'Não foi possível apagar tudo. Tente de novo.',
}
