import type { WebCopyKey } from './en'

// Anrede „Sie“. Begriffe: docs/i18n-glossary.md（Klasseneinteilung, zusammen, trennen）
export const DE_COPY: Record<WebCopyKey, string> = {
  docTitle: 'Mosaic — Klasseneinteilung optimieren',
  metaDescription: 'Mosaic verteilt die Merkmale der Schülerinnen und Schüler automatisch gleichmäßig auf die Klassen. Die Daten werden nur im Browser verarbeitet.',
  tagline: 'Klasseneinteilung optimieren',
  language: 'Sprache',
  close: 'Schließen',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  edit: 'Bearbeiten',
  add: 'Hinzufügen',

  heroBadge: 'Simulated Annealing × parallele Suche',
  heroTitle1: 'Jedes Kind zählt:',
  heroTitle2a: 'ausgewogene Klassen',
  heroTitle2b: 'in Sekunden.',
  heroDesc:
    'Mosaic verteilt Geschlecht, Leistung, Förderbedarf und weitere Merkmale gleichmäßig auf die Klassen. Freundschaftswünsche und Trennungen werden berücksichtigt, und Sie können das Ergebnis sofort nachbessern.',
  heroLocal: 'Daten werden nur im Browser verarbeitet',
  heroFree: 'Ohne Konto und Token, völlig kostenlos',
  warningsTitle: 'Hinweise beim Laden',

  step1Title: 'Schülerliste laden',
  step1Desc: 'Tragen Sie die Merkmale in die Excel-Vorlage ein und laden Sie sie hoch. Die Daten verlassen den Browser nicht.',
  step1DescGoogle: 'Füllen Sie die Vorlage aus und laden Sie sie aus Excel oder Google Tabellen. Daten werden nur zwischen Browser und Google ausgetauscht.',
  dropTitle: 'Excel-Datei hierher ziehen',
  dropSub: 'oder klicken und auswählen (.xlsx)',
  dropAgain: 'Klicken, um eine andere Datei zu wählen',
  googleSheets: 'Google Tabellen',
  googleSelect: 'Mit Google-Konto auswählen',
  templateExcel: 'Excel-Vorlage',
  templateDownload: 'Vorlage herunterladen',
  openTemplate: 'Erstellte Vorlage öffnen',
  createTemplate: 'Vorlage in Google Tabellen erstellen',
  trySamples: 'Beispiel ausprobieren',
  samplePrefix: 'Beispiel: {label}',
  sample1: 'Klassen (80 Schüler, 4 Klassen)',
  sample2: 'Klassen (80 Schüler, einfach)',
  sampleGroup: 'Gruppenarbeit (30 Schüler, 6 Gruppen)',

  step2Title: 'Bedingungen anpassen',
  step2Desc: 'Merkmale mit höherem Gewicht werden zuerst ausgeglichen. Gewicht 0 ignoriert das Merkmal.',
  studentsLabel: 'Schüler',
  openRoster: 'Liste öffnen',
  personUnit: 'Schüler',
  rosterHint: 'Liste, Filter, Bearbeiten',
  classCount: 'Anzahl Klassen (Gruppen)',
  decrease: 'Weniger',
  increase: 'Mehr',
  perClass: '{range} Schüler pro Klasse',
  searchTime: 'Suchdauer',
  quick: 'Schnell',
  standard: 'Standard',
  thorough: 'Gründlich',
  timeInfo: '{s} s × parallele Suche',
  colItem: 'Merkmal',
  colKind: 'Art / Werte',
  colWeight: 'Gewicht',
  kindFlag: 'Ja/Nein',
  kindCategory: 'Kategorie',
  kindNumeric: 'Zahl',
  blankOnly: '(nur leer)',
  pairWanted: 'Zusammen',
  pairUnwanted: 'Trennen',
  countItems: '{n}',
  noPairsAdd: 'Keine — zum Hinzufügen klicken',

  runTitle: 'Einteilen',
  runDesc: 'Mosaic sucht auf mehreren CPU-Kernen gleichzeitig und übernimmt die ausgewogenste Einteilung.',
  searching: 'Beste Einteilung wird gesucht … {p} %',
  stop: 'Stopp',
  runBtn: 'Klassen einteilen',
  rerun: 'Neu einteilen',
  lastRun: 'Zuletzt: {workers} parallel · {m} Mio. Schritte',
  discarded: 'Die Liste wurde während der Suche geändert, das Ergebnis wurde verworfen. Bitte erneut starten.',
  googleResultTitle: 'Klasseneinteilung {date}',
  googleSave: 'In Google Tabellen speichern',
  googleWriteBack: 'In die Originaltabelle schreiben',
  savedToSheet: 'In die Tabelle geschrieben',
  fileResults: 'Klasseneinteilung',
  fileRoster: 'Schuelerliste',
  footer: 'Mosaic · Klasseneinteilung optimieren — MIT License',

  statClasses: 'Klassen',
  statClassesSub: '{n} Schüler eingeteilt',
  statGap: 'Größen\u00ADunterschied',
  statGapSub: '{min}–{max} Schüler',
  statBalance: 'Ausgewogen\u00ADheit',
  perfect: 'Perfekt',
  balancePerfectSub: 'Alle Merkmale im Sollbereich',
  balanceSub: 'Schüler außerhalb des Sollbereichs',
  statViolations: 'Nicht erfüllt',
  violationsSub: 'Einige Wünsche sind nicht erfüllt',
  violationsOk: 'Alle Wünsche erfüllt',
  tabClasses: 'Klassen',
  tabBalance: 'Auswertung',
  tabChecks: 'Prüfung',
  tabChecksN: 'Prüfung ({n})',
  undoMoves: 'Änderungen zurücksetzen',
  saveExcel: 'Als Excel speichern',
  moveTitle: '{who} verschieben →',
  boardHintDesktop: 'Ziehen oder klicken Sie auf einen Schüler, um ihn in eine andere Klasse zu verschieben.',
  boardHintMobile: 'Wischen Sie, um die Klasse zu wechseln. Tippen Sie auf einen Schüler, um ihn zu verschieben.',
  boardHintTail: ' Die Auswertung wird sofort neu berechnet.',
  classChip: '{cls} · {n}',
  studentsN: '{n} Schüler',
  wantedBadgeTitle: 'Zusammen {label}',
  unwantedBadgeTitle: 'Trennen {label}',
  unmetSuffix: ' (nicht erfüllt)',
  pairings: 'Wünsche',
  pairingsMet: '{ok} von {n} erfüllt',
  clickToHighlight: 'Klicken, um die Schüler hervorzuheben',
  colorize: '„Zusammen“ farbig',
  weightN: 'Gewicht {w}',
  average: 'Mittelwert',
  averageLevel: 'Mittelwert',
  even: 'Ausgeglichen',
  offBy: 'Abweichung {n}',
  ideal: 'Soll',
  allMet: 'Alle Bedingungen erfüllt',
  allMetBody: 'Alle {w} Wünsche „zusammen“ und {u} Wünsche „trennen“ wurden berücksichtigt.',
  noPairsBody: 'Es wurden keine Wünsche angegeben.',

  rosterEditorAria: 'Schülerliste bearbeiten',
  rosterTitle: 'Schülerliste',
  tabStudentsList: 'Schüler',
  tabWanted: 'Zusammen',
  tabUnwanted: 'Trennen',
  saveRosterTitle: 'Im Format der Vorlage speichern (lässt sich wieder laden)',
  saveRoster: 'Liste speichern',
  saveShort: 'Speichern',
  conflict: 'Widersprüchliche Wünsche (über „zusammen“ verbundene Schüler sollen auch getrennt werden): ',
  searchPlaceholder: 'Nr. oder Name suchen',
  pairFilter: 'Wünsche',
  clearFilters: 'Filter löschen',
  reapplyTitle: 'Filter und Sortierung an die Änderungen anpassen',
  reapply: 'Filter neu anwenden',
  countAll: '{n} Schüler',
  countSome: '{shown} / {total} Schüler',
  newColPlaceholder: 'Name des Merkmals (z. B. Klassensprecher)',
  kindTitle: 'Art der Werte',
  kindOptFlag: '✓ / leer',
  kindOptCategory: 'Stufen / Kategorien',
  kindOptNumeric: 'Zahl (Noten usw.)',
  cancelShort: 'Abbrechen',
  addColumn: 'Merkmal',
  addStudent: 'Schüler',
  selectAllVisible: 'Alle angezeigten auswählen',
  noTaken: 'Nr. {no} ist bereits vergeben',
  namePlaceholder: 'Namen eingeben',
  confirmDeleteStudent: '{who} aus der Liste entfernen?',
  colNo: 'Nr.',
  colName: 'Name',
  deleteColumnTitle: 'Spalte „{name}“ löschen',
  confirmDeleteColumn: 'Spalte „{name}“ löschen?',
  colPair: 'Wünsche',
  wantedTitleAttr: 'Zusammen: {names}',
  unwantedTitleAttr: 'Trennen: {names}',
  noMatch: 'Keine Schüler entsprechen den Filtern.',
  selectedN: '{n} ausgewählt',
  hiddenSelected: ' ({n} ausgeblendete nicht enthalten)',
  makeWanted: 'Zusammen',
  makeUnwanted: 'Trennen',
  confirmDeleteN: '{n} Schüler aus der Liste entfernen?',
  bulkHint: 'Bei Auswahl gelten Änderungen an einer Zelle für alle ausgewählten Schüler',
  clearSelection: 'Auswahl aufheben',
  pairAll: 'Alle',
  pairAny: 'Mit Wunsch',
  pairWantedF: 'Mit „zusammen“',
  pairUnwantedF: 'Mit „trennen“',
  pairNone: 'Ohne Wunsch',
  avg: 'Mittelwert {v}',
  notEntered: 'Leer',
  newValuePrompt: 'Neuen Wert eingeben',
  newValueOption: '+ Neuer Wert …',
  bulkSet: 'Merkmal setzen',
  setBlankTitle: 'Leeren',
  blankShort: 'Leer',
  blankLabel: '(leer)',
  blankName: 'leer',
  filterNo: 'nein',
  filterYes: 'ja',
  filterCount: '{n} Werte',
  flagOption: '{v} (ja)',
  clearThis: 'Diesen Filter löschen',
  groupsWantedTitle: 'Gruppen „zusammen“',
  groupsUnwantedTitle: 'Gruppen „trennen“',
  groupsWantedDesc: 'Schüler einer Gruppe kommen immer in dieselbe Klasse.',
  groupsUnwantedDesc: 'Schüler einer Gruppe kommen nach Möglichkeit in verschiedene Klassen (ab 3 Schülern alle getrennt).',
  groupsBulkHint: ' Sie können Schüler auch in der Liste auswählen und so eine Gruppe anlegen.',
  newGroup: 'Neue Gruppe',
  newGroupLabel: 'Neue Gruppe (mindestens 2)',
  create: 'Anlegen',
  confirmDeleteGroup: 'Gruppe {label} löschen?',
  deleteGroup: 'Gruppe löschen',
  confirmGroupDissolve: 'Es bliebe nur ein Schüler übrig, daher wird diese Gruppe gelöscht. Fortfahren?',
  noGroups: 'Noch keine Wünsche',
  noName: '(ohne Namen)',
  removeMember: 'Entfernen',
  addMemberPlaceholder: '+ Per Nr. oder Name hinzufügen',
  noInvalid: 'Bitte als Nr. eine ganze Zahl ab 1 eingeben',
  flagMark: '✓',

  googleScriptFailed: '{src} konnte nicht geladen werden',
  googleAuthFailed: 'Google-Anmeldung fehlgeschlagen: {msg}',
  googleApiError: 'Google-API-Fehler: {msg}',
  googlePickerTitle: 'Tabelle mit der Schülerliste auswählen',
  googleTemplateTitle: 'Mosaic-Vorlage Schülerliste',

  parseRosterMissing: 'Das Blatt „{sheet}“ fehlt oder enthält keine Daten',
  parseNoStudents: 'Keine Schüler gefunden (Nr. und Name ab Zeile 3 eintragen)',
  parseNoMissing: '{sheet}, Zeile {row}: „{name}“ hat keine Nr. und wurde übersprungen',
  parseDuplicateNo: 'Nr. {no} kommt mehrfach vor',
  parseUnknownNo: '„{sheet}“, Zeile {row}: Nr. {no} steht nicht in der Liste',
  parseClassCountUnknown: 'Die Anzahl der Klassen in „{sheet}“ war nicht lesbar, daher wurden {k} Klassen verwendet',
  parseMaxTooSmall: 'Mit höchstens {max} × {k} Klassen passen nicht alle hinein, die Höchstzahl wurde ignoriert',
}
