// Web 版の UI 文言。英語のキー集合が正（他の言語はこのキーを全部持たないと型エラー。src/copy/index.ts）。
// 訳語は docs/i18n-glossary.md（スマホ版と同じ語）に揃える。{name} は format() で埋める。
export const EN_COPY = {
  docTitle: 'FairClass — Balanced class placement',
  metaDescription: 'FairClass helps you place students in well-balanced classes, so their strengths and needs are spread fairly. Your data stays in your browser.',
  tagline: 'Class placement helper',
  language: 'Language',
  close: 'Close',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  add: 'Add',

  heroBadge: 'The best plan from many combinations',
  heroTitle1: 'Every student in the mix,',
  heroTitle2a: 'balanced classes',
  heroTitle2b: 'in seconds.',
  heroDesc:
    'FairClass spreads student attributes — gender, academics, support needs and more — evenly across classes. It also takes into account who you’d like to keep together or apart, and you can fine-tune the result right away. And it’s not just for next year’s classes: use it all year for table groups, project teams, field-trip groups and more.',
  heroLocal: 'Your data stays in your browser',
  heroFree: 'No sign-up, no account, completely free',
  warningsTitle: 'Notes from loading',

  step1Title: 'Load a roster',
  step1Desc: 'Fill in the Excel template with your students’ attributes and open it here. Your data never leaves the browser.',
  step1DescGoogle: 'Fill in the template and load it from Excel or Google Sheets. Data is exchanged only between your browser and Google.',
  dropTitle: 'Drop an Excel file',
  dropSub: 'or click to choose (.xlsx)',
  googleSheets: 'Google Sheets',
  googleSelect: 'Choose with your Google account',
  templateExcel: 'Excel template',
  templateDownload: 'Download template',
  openTemplate: 'Open the created template',
  createTemplate: 'Create template in Google Sheets',
  trySamples: 'Try a sample',
  samplePrefix: 'Sample: {label}',
  sample1: 'Class placement (80 students, 4 classes)',
  sample2: 'Class placement (80 students, simple)',
  sampleGroup: 'Group work (30 students, 6 groups)',
  sampleExcelTitle: 'Download "{label}" as Excel',
  samplesExcelHint: 'Click ⬇ to download a sample as Excel (free). Edit it and load it in the box above.',
  currentRoster: 'Open roster',
  otherRoster: 'Open another roster',
  backToRoster: 'Cancel (back to the current roster)',
  rosterSummary: '{n} students · {cols} attributes · keep together {w} · keep apart {u}',
  editRoster: 'Edit roster',

  step2Title: 'Adjust the conditions',
  step2Desc: 'Attributes with a higher weight are balanced first. At weight 0, an attribute is not taken into account.',
  studentsLabel: 'Students',
  openRoster: 'Open roster',
  personUnit: 'students',
  rosterHint: 'List, filter, edit',
  classCount: 'Number of classes (groups)',
  decrease: 'Decrease',
  increase: 'Increase',
  perClass: '{range} students per class',
  searchTime: 'Thinking time',
  quick: 'Quick',
  standard: 'Standard',
  thorough: 'Thorough',
  timeInfo: 'Takes {s} seconds',
  colItem: 'Attribute',
  colKind: 'Type / values',
  colWeight: 'Weight',
  kindFlag: 'Checkbox',
  kindCategory: 'List',
  kindDegree: 'Scale (1–5)',
  kindNumeric: 'Number',
  blankOnly: '(blank only)',
  pairWanted: 'Keep together',
  pairUnwanted: 'Keep apart',
  countItems: '{n}',
  noPairsAdd: 'None — click to add',

  runTitle: 'Build classes',
  runDesc: 'FairClass tries many combinations at once and picks the best-balanced plan.',
  searching: 'Finding a well-balanced arrangement… {p}%',
  stop: 'Stop',
  runBtn: 'Build classes',
  rerun: 'Build again',
  lastRun: 'Last time: tried {m}M combinations, {workers} at a time',
  discarded: 'The roster changed while classes were being built, so this result wasn’t used. Please build again.',
  googleResultTitle: 'Class placement results {date}',
  googleSave: 'Save to Google Sheets',
  googleWriteBack: 'Write to the original sheet',
  savedToSheet: 'Written to the spreadsheet',
  fileResults: 'class-placement',
  fileRoster: 'roster',
  footer: 'FairClass · class placement helper — MIT License',

  statClasses: 'Classes',
  statClassesSub: '{n} students placed',
  statGap: 'Size difference',
  statGapSub: '{min}–{max} students',
  statBalance: 'Balance',
  perfect: 'Perfect',
  balancePerfectSub: 'Every attribute is within its target range',
  balanceSub: 'Students outside target ranges',
  statViolations: 'Pairings not met',
  violationsSub: 'Some pairings couldn’t be met',
  violationsOk: 'All pairings are met',
  tabClasses: 'Classes',
  tabBalance: 'Balance',
  tabChecks: 'Checks',
  tabChecksN: 'Checks ({n})',
  undoMoves: 'Undo my changes',
  saveExcel: 'Save as Excel',
  moveTitle: 'Move {who} →',
  boardHintDesktop: 'Drag a student, or click one, to move them to another class.',
  boardHintMobile: 'Swipe to switch classes. Tap a student to move them to another class.',
  boardHintTail: ' Totals update instantly.',
  classChip: '{cls} · {n}',
  studentsN: '{n} students',
  wantedBadgeTitle: 'Keep together {label}',
  unwantedBadgeTitle: 'Keep apart {label}',
  unmetSuffix: ' (not met)',
  pairings: 'Pairings',
  pairingsMet: '{ok} / {n} met',
  clickToHighlight: 'Click to highlight the students',
  colorize: 'Color “keep together”',
  weightN: 'Weight {w}',
  average: 'Average',
  averageLevel: 'Average',
  even: 'Even',
  offBy: 'Off by {n}',
  ideal: 'Target',
  allMet: 'All pairings were met',
  allMetBody: 'All {w} keep-together and {u} keep-apart pairings were applied.',
  noPairsBody: 'No pairings were set.',

  rosterEditorAria: 'Edit roster',
  rosterTitle: 'Roster',
  tabStudentsList: 'Students',
  tabWanted: 'Together',
  tabUnwanted: 'Apart',
  saveRosterTitle: 'Save in the template format (can be loaded again)',
  saveRoster: 'Save roster',
  saveShort: 'Save',
  conflict: 'Some pairings contradict each other (students linked by “keep together” are also set to “keep apart”): ',
  searchPlaceholder: 'Search No. or name',
  pairFilter: 'Pairings',
  clearFilters: 'Clear filters',
  reapplyTitle: 'Apply the filters and sorting again to reflect your edits',
  reapply: 'Reapply filters',
  countAll: '{n} students',
  countSome: '{shown} / {total} students',
  newColPlaceholder: 'Attribute name (e.g. Leader)',
  kindTitle: 'Type of values',
  kindOptFlag: 'Checkbox (✓ / blank)',
  kindOptCategory: 'List (pick one option)',
  kindOptDegree: 'Scale (1–5)',
  kindOptNumeric: 'Number (scores etc.)',
  cancelShort: 'Cancel',
  addColumn: 'Attribute',
  addStudent: 'Student',
  selectAllVisible: 'Select all shown',
  noTaken: 'No. {no} is already used by another student',
  namePlaceholder: 'Enter a name',
  confirmDeleteStudent: 'Remove {who} from the roster?',
  colNo: 'No.',
  colName: 'Name',
  deleteColumnTitle: 'Delete the “{name}” column',
  confirmDeleteColumn: 'Delete the “{name}” column?',
  colPair: 'Pairings',
  wantedTitleAttr: 'Keep together: {names}',
  unwantedTitleAttr: 'Keep apart: {names}',
  noMatch: 'No students match the filters.',
  selectedN: '{n} selected',
  hiddenSelected: ' ({n} hidden students are not included)',
  makeWanted: 'Keep together',
  makeUnwanted: 'Keep apart',
  confirmDeleteN: 'Remove {n} students from the roster?',
  bulkHint: 'While students are selected, cell edits apply to all of them',
  clearSelection: 'Clear selection',
  pairAll: 'All',
  pairAny: 'Any pairing',
  pairWantedF: 'Keep together',
  pairUnwantedF: 'Keep apart',
  pairNone: 'No pairing',
  avg: 'Average {v}',
  notEntered: 'Empty',
  newOptionPlaceholder: 'Type a new option and press Enter',
  addOption: '+ Add option',
  listOptions: 'Options',
  noOptions: 'No options yet. Add one below.',
  editOption: 'Rename option {v}',
  deleteOption: 'Delete option {v}',
  confirmDeleteOption: 'Delete "{v}" from the list? The {n} students who chose it will become blank.',
  duplicateOption: 'This option already exists',
  listOptionsHint: 'Options that no one has chosen are not kept when saving to Excel.',
  columnSettings: 'Settings for "{name}"',
  bulkSet: 'Set attribute',
  setBlankTitle: 'Make blank',
  blankShort: 'Blank',
  blankLabel: '(blank)',
  blankName: 'blank',
  filterNo: 'no',
  filterYes: 'yes',
  filterCount: '{n} values',
  flagOption: '{v} (yes)',
  clearThis: 'Clear this filter',
  groupsWantedTitle: 'Groups to keep together',
  groupsUnwantedTitle: 'Groups to keep apart',
  groupsWantedDesc: 'Students in a group are always placed in the same class.',
  groupsUnwantedDesc: 'Students in a group are placed in different classes from each other whenever possible (with 3 or more, all apart).',
  groupsBulkHint: ' You can also select students in the list and create a group at once.',
  newGroup: 'New group',
  newGroupLabel: 'New group (2 or more students)',
  create: 'Create',
  confirmDeleteGroup: 'Delete group {label}?',
  deleteGroup: 'Delete group',
  confirmGroupDissolve: 'Only one student would be left, so this group will be deleted. Continue?',
  noGroups: 'No groups yet',
  noName: '(no name)',
  removeMember: 'Remove',
  addMemberPlaceholder: '+ Add by No. or name',
  noInvalid: 'No. must be a number of 1 or more',
  flagMark: '✓',

  googleScriptFailed: 'Could not load {src}',
  googleAuthFailed: 'Google sign-in failed: {msg}',
  googleApiError: 'Something went wrong while talking to Google: {msg}',
  googlePickerTitle: 'Choose the roster spreadsheet',
  googleTemplateTitle: 'FairClass roster template',

  parseRosterMissing: 'The "{sheet}" sheet is missing or has no data',
  parseNoStudents: 'No students found (enter No. and name from row 3 on)',
  parseNoMissing: '{sheet}, row {row}: "{name}" has no No., so it was skipped',
  parseDuplicateNo: 'No. {no} appears more than once',
  parseUnknownNo: '"{sheet}", row {row}: No. {no} is not in the roster',
  parseClassCountUnknown: 'The number of classes in "{sheet}" could not be read, so {k} classes were used',
  parseMaxTooSmall: 'A maximum of {max} students × {k} classes can’t fit everyone, so the maximum class size was not used',
}

export type WebCopyKey = keyof typeof EN_COPY
