import type { WebCopyKey } from './en'

// Español con vocabulario latinoamericano (tú, «grupo», «estudiantes»). Términos: docs/i18n-glossary.md
export const ES_COPY: Record<WebCopyKey, string> = {
  docTitle: 'Mosaic — Distribución de estudiantes en grupos',
  metaDescription: 'Mosaic reparte a los estudiantes en grupos equilibrados de forma automática. Los datos se procesan solo en tu navegador.',
  tagline: 'Optimizador de grupos',
  language: 'Idioma',
  close: 'Cerrar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  edit: 'Editar',
  add: 'Agregar',

  heroBadge: 'Recocido simulado × búsqueda paralela',
  heroTitle1: 'Cada estudiante cuenta:',
  heroTitle2a: 'grupos equilibrados',
  heroTitle2b: 'en segundos.',
  heroDesc:
    'Mosaic reparte de forma pareja entre los grupos el género, el desempeño, las necesidades de apoyo y otros criterios. También respeta a quiénes mantener juntos o separar, y puedes ajustar el resultado al momento.',
  heroLocal: 'Los datos se procesan solo en tu navegador',
  heroFree: 'Sin registro ni tokens, totalmente gratis',
  warningsTitle: 'Avisos al cargar',

  step1Title: 'Cargar la lista',
  step1Desc: 'Completa la plantilla de Excel con los criterios de tus estudiantes y súbela. Los datos no salen del navegador.',
  step1DescGoogle: 'Completa la plantilla y cárgala desde Excel o Google Sheets. Los datos solo se intercambian entre tu navegador y Google.',
  dropTitle: 'Suelta un archivo de Excel',
  dropSub: 'o haz clic para elegirlo (.xlsx)',
  dropAgain: 'Haz clic para elegir otro archivo',
  googleSheets: 'Google Sheets',
  googleSelect: 'Elegir con tu cuenta de Google',
  templateExcel: 'Plantilla de Excel',
  templateDownload: 'Descargar plantilla',
  openTemplate: 'Abrir la plantilla creada',
  createTemplate: 'Crear plantilla en Google Sheets',
  trySamples: 'Probar con un ejemplo',
  samplePrefix: 'Ejemplo: {label}',
  sample1: 'Grupos (80 estudiantes, 4 grupos)',
  sample2: 'Grupos (80 estudiantes, simple)',
  sampleGroup: 'Equipos de trabajo (30, 6 equipos)',

  step2Title: 'Ajustar las condiciones',
  step2Desc: 'Los criterios con más peso se equilibran primero. Con peso 0 no se toman en cuenta.',
  studentsLabel: 'Estudiantes',
  openRoster: 'Abrir la lista',
  personUnit: 'estudiantes',
  rosterHint: 'Lista, filtros y edición',
  classCount: 'Número de grupos',
  decrease: 'Bajar',
  increase: 'Subir',
  perClass: '{range} estudiantes por grupo',
  searchTime: 'Tiempo de búsqueda',
  quick: 'Rápido',
  standard: 'Estándar',
  thorough: 'A fondo',
  timeInfo: '{s} s × búsqueda paralela',
  colItem: 'Criterio',
  colKind: 'Tipo / valores',
  colWeight: 'Peso',
  kindFlag: 'Sí/no',
  kindCategory: 'Categoría',
  kindNumeric: 'Número',
  blankOnly: '(solo vacíos)',
  pairWanted: 'Mantener juntos',
  pairUnwanted: 'Separar',
  countItems: '{n}',
  noPairsAdd: 'Sin condiciones — haz clic para agregar',

  runTitle: 'Armar grupos',
  runDesc: 'Busca en varios núcleos de CPU a la vez y se queda con la opción más equilibrada.',
  searching: 'Buscando la mejor combinación… {p} %',
  stop: 'Detener',
  runBtn: 'Armar grupos',
  rerun: 'Armar de nuevo',
  lastRun: 'Última vez: {workers} en paralelo · {m} M iteraciones',
  discarded: 'La lista cambió durante la búsqueda, así que se descartó el resultado. Vuelve a intentarlo.',
  googleResultTitle: 'Distribución de grupos {date}',
  googleSave: 'Guardar en Google Sheets',
  googleWriteBack: 'Escribir en la hoja original',
  savedToSheet: 'Se escribió en la hoja de cálculo',
  fileResults: 'distribucion-grupos',
  fileRoster: 'lista',
  footer: 'Mosaic · optimizador de grupos — MIT License',

  statClasses: 'Grupos',
  statClassesSub: '{n} estudiantes distribuidos',
  statGap: 'Diferencia de tamaño',
  statGapSub: '{min}–{max} estudiantes',
  statBalance: 'Equilibrio',
  perfect: 'Perfecto',
  balancePerfectSub: 'Todos los criterios están en su rango ideal',
  balanceSub: 'Estudiantes fuera del rango ideal',
  statViolations: 'Condiciones no cumplidas',
  violationsSub: 'Hay condiciones que no se cumplen',
  violationsOk: 'Se cumplen todas las condiciones',
  tabClasses: 'Grupos',
  tabBalance: 'Equilibrio',
  tabChecks: 'Revisión',
  tabChecksN: 'Revisión ({n})',
  undoMoves: 'Deshacer cambios manuales',
  saveExcel: 'Guardar en Excel',
  moveTitle: 'Mover a {who} →',
  boardHintDesktop: 'Arrastra o haz clic en un estudiante para moverlo a otro grupo.',
  boardHintMobile: 'Desliza para cambiar de grupo. Toca a un estudiante para moverlo a otro grupo.',
  boardHintTail: ' Los totales se recalculan al instante.',
  classChip: '{cls} · {n}',
  studentsN: '{n} estudiantes',
  wantedBadgeTitle: 'Mantener juntos {label}',
  unwantedBadgeTitle: 'Separar {label}',
  unmetSuffix: ' (no se cumple)',
  pairings: 'Condiciones',
  pairingsMet: '{ok} de {n} cumplidas',
  clickToHighlight: 'Haz clic para resaltar a los estudiantes',
  colorize: 'Colorear «juntos»',
  weightN: 'Peso {w}',
  average: 'Promedio',
  averageLevel: 'Promedio',
  even: 'Parejo',
  offBy: 'Desvío {n}',
  ideal: 'Meta',
  allMet: 'Se cumplen todas las condiciones',
  allMetBody: 'Se aplicaron las {w} condiciones de «mantener juntos» y las {u} de «separar».',
  noPairsBody: 'No se indicaron condiciones.',

  rosterEditorAria: 'Editor de la lista',
  rosterTitle: 'Lista',
  tabStudentsList: 'Estudiantes',
  tabWanted: 'Juntos',
  tabUnwanted: 'Separar',
  saveRosterTitle: 'Guardar con el formato de la plantilla (se puede volver a cargar)',
  saveRoster: 'Guardar lista',
  saveShort: 'Guardar',
  conflict: 'Hay condiciones contradictorias (estudiantes unidos por «mantener juntos» también están marcados para «separar»): ',
  searchPlaceholder: 'Buscar por N.º o nombre',
  pairFilter: 'Condiciones',
  clearFilters: 'Quitar filtros',
  reapplyTitle: 'Volver a aplicar filtros y orden según tus cambios',
  reapply: 'Aplicar filtros de nuevo',
  countAll: '{n} estudiantes',
  countSome: '{shown} / {total} estudiantes',
  newColPlaceholder: 'Nombre del criterio (p. ej. Liderazgo)',
  kindTitle: 'Tipo de valores',
  kindOptFlag: '✓ / vacío',
  kindOptCategory: 'Niveles / categorías',
  kindOptNumeric: 'Número (notas, etc.)',
  cancelShort: 'Cancelar',
  addColumn: 'Criterio',
  addStudent: 'Estudiante',
  selectAllVisible: 'Seleccionar todos los visibles',
  noTaken: 'El N.º {no} ya lo usa otro estudiante',
  namePlaceholder: 'Escribe un nombre',
  confirmDeleteStudent: '¿Quitar a {who} de la lista?',
  colNo: 'N.º',
  colName: 'Nombre',
  deleteColumnTitle: 'Eliminar la columna «{name}»',
  confirmDeleteColumn: '¿Eliminar la columna «{name}»?',
  colPair: 'Condiciones',
  wantedTitleAttr: 'Mantener juntos: {names}',
  unwantedTitleAttr: 'Separar: {names}',
  noMatch: 'Ningún estudiante coincide con los filtros.',
  selectedN: '{n} seleccionados',
  hiddenSelected: ' (no se incluyen {n} ocultos)',
  makeWanted: 'Mantener juntos',
  makeUnwanted: 'Separar',
  confirmDeleteN: '¿Quitar a {n} estudiantes de la lista?',
  bulkHint: 'Con estudiantes seleccionados, los cambios en una celda se aplican a todos',
  clearSelection: 'Quitar selección',
  pairAll: 'Todos',
  pairAny: 'Con condición',
  pairWantedF: 'Con «mantener juntos»',
  pairUnwantedF: 'Con «separar»',
  pairNone: 'Sin condición',
  avg: 'Promedio {v}',
  notEntered: 'Sin datos',
  newValuePrompt: 'Escribe un valor nuevo',
  newValueOption: '+ Valor nuevo…',
  bulkSet: 'Asignar criterio',
  setBlankTitle: 'Dejar vacío',
  blankShort: 'Vacío',
  blankLabel: '(vacío)',
  blankName: 'vacío',
  filterNo: 'no',
  filterYes: 'sí',
  filterCount: '{n} valores',
  flagOption: '{v} (sí)',
  clearThis: 'Quitar este filtro',
  groupsWantedTitle: 'Estudiantes que van juntos',
  groupsUnwantedTitle: 'Estudiantes que se separan',
  groupsWantedDesc: 'Los estudiantes de un conjunto siempre quedan en el mismo grupo.',
  groupsUnwantedDesc: 'Los estudiantes de un conjunto quedan en grupos distintos entre sí siempre que se pueda (con 3 o más, todos separados).',
  groupsBulkHint: ' También puedes seleccionarlos en la lista y crear el conjunto de una vez.',
  newGroup: 'Nuevo conjunto',
  newGroupLabel: 'Nuevo conjunto (2 o más estudiantes)',
  create: 'Crear',
  confirmDeleteGroup: '¿Eliminar el conjunto {label}?',
  deleteGroup: 'Eliminar conjunto',
  confirmGroupDissolve: 'Quedaría un solo estudiante, así que este conjunto se eliminará. ¿Continuar?',
  noGroups: 'Todavía no hay condiciones',
  noName: '(sin nombre)',
  removeMember: 'Quitar',
  addMemberPlaceholder: '+ Agregar por N.º o nombre',
  noInvalid: 'El N.º debe ser un número entero mayor o igual a 1',
  flagMark: '✓',

  googleScriptFailed: 'No se pudo cargar {src}',
  googleAuthFailed: 'Falló el inicio de sesión con Google: {msg}',
  googleApiError: 'Error de la API de Google: {msg}',
  googlePickerTitle: 'Elige la hoja de cálculo con la lista',
  googleTemplateTitle: 'Plantilla de lista de Mosaic',

  parseRosterMissing: 'No se encontró la hoja «{sheet}» o no tiene datos',
  parseNoStudents: 'No hay estudiantes (escribe el N.º y el nombre desde la fila 3)',
  parseNoMissing: '{sheet}, fila {row}: «{name}» no tiene N.º y no se cargó',
  parseDuplicateNo: 'El N.º {no} está repetido',
  parseUnknownNo: '«{sheet}», fila {row}: el N.º {no} no está en la lista',
  parseClassCountUnknown: 'No se pudo leer el número de grupos en «{sheet}»; se usaron {k} grupos',
  parseMaxTooSmall: 'Con un máximo de {max} × {k} grupos no caben todos, así que se ignoró el máximo',
}
