import type { WebCopyKey } from './en'

// Español con vocabulario latinoamericano (tú, “grupo”, “estudiantes”). Términos: docs/i18n-glossary.md
export const ES_COPY: Record<WebCopyKey, string> = {
  docTitle: 'FairClass — Distribución de estudiantes en grupos',
  metaDescription: 'FairClass te ayuda a repartir a los estudiantes en grupos equilibrados. Los datos se quedan solo en tu navegador.',
  tagline: 'Ayuda para armar grupos',
  language: 'Idioma',
  close: 'Cerrar',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  edit: 'Editar',
  add: 'Agregar',

  heroBadge: 'La mejor opción entre muchas combinaciones',
  heroTitle1: 'Cada estudiante cuenta:',
  heroTitle2a: 'grupos equilibrados',
  heroTitle2b: 'en segundos.',
  heroDesc:
    'FairClass reparte de forma pareja entre los grupos el género, el desempeño, las necesidades de apoyo y otros criterios. También tiene en cuenta a quiénes mantener juntos o separar, y puedes ajustar el resultado al momento. Y no solo al inicio del ciclo: te sirve todo el año para armar equipos de trabajo, grupos por mesa o grupos para salidas.',
  heroLocal: 'Los datos se quedan solo en tu navegador',
  heroFree: 'Sin registro ni cuenta, totalmente gratis',
  warningsTitle: 'Avisos al cargar',

  step1Title: 'Cargar la lista',
  step1Desc: 'Completa la plantilla de Excel con los criterios de tus estudiantes y ábrela aquí. Los datos no salen del navegador.',
  step1DescGoogle: 'Completa la plantilla y cárgala desde Excel o Google Sheets. Los datos solo se intercambian entre tu navegador y Google.',
  dropTitle: 'Suelta un archivo de Excel',
  dropSub: 'o haz clic para elegirlo (.xlsx)',
  googleSheets: 'Google Sheets',
  googleSelect: 'Elegir con tu cuenta de Google',
  templateExcel: 'Plantilla de Excel',
  templateDownload: 'Descargar plantilla',
  openTemplate: 'Abrir la plantilla creada',
  createTemplate: 'Crear plantilla en Google Sheets',
  trySamples: 'Probar con un ejemplo',
  samplePrefix: 'Ejemplo: {label}',
  sample1: 'Grupos (80 estudiantes, 4 grupos)',
  sample2: 'Grupos (80 estudiantes, simple)',
  sampleGroup: 'Equipos de trabajo (30 estudiantes, 6 equipos)',
  sampleExcelTitle: 'Descargar "{label}" en Excel',
  samplesExcelHint: 'Haz clic en ⬇ para descargar un ejemplo en Excel (gratis). Edítalo y cárgalo en el recuadro de arriba.',
  currentRoster: 'Lista abierta',
  otherRoster: 'Abrir otra lista',
  backToRoster: 'Cancelar (volver a la lista actual)',
  rosterSummary: '{n} estudiantes · {cols} criterios · juntos {w} · separar {u}',
  editRoster: 'Editar lista',

  step2Title: 'Ajustar las condiciones',
  step2Desc: 'Los criterios con más peso se equilibran primero. Con peso 0 no se toman en cuenta.',
  studentsLabel: 'Estudiantes',
  openRoster: 'Abrir la lista',
  personUnit: 'estudiantes',
  rosterHint: 'Lista, filtros y edición',
  classCount: 'Número de grupos',
  decrease: 'Bajar',
  increase: 'Subir',
  perClass: '{range} estudiantes por grupo',
  searchTime: 'Tiempo para armar',
  quick: 'Rápido',
  standard: 'Estándar',
  thorough: 'A fondo',
  timeInfo: 'Tarda {s} segundos',
  colItem: 'Criterio',
  colKind: 'Tipo / valores',
  colWeight: 'Peso',
  kindFlag: 'Casilla',
  kindCategory: 'Lista',
  kindDegree: 'Nivel (1–5)',
  kindNumeric: 'Número',
  blankOnly: '(solo vacíos)',
  pairWanted: 'Mantener juntos',
  pairUnwanted: 'Separar',
  countItems: '{n}',
  noPairsAdd: 'Sin condiciones — haz clic para agregar',

  runTitle: 'Armar grupos',
  runDesc: 'Prueba muchas combinaciones a la vez y elige la opción más equilibrada.',
  searching: 'Buscando una distribución equilibrada… {p} %',
  stop: 'Detener',
  runBtn: 'Armar grupos',
  rerun: 'Armar de nuevo',
  lastRun: 'La última vez: se probaron {m} M combinaciones, {workers} a la vez',
  discarded: 'La lista cambió mientras se armaban los grupos, así que no se usó este resultado. Vuelve a armarlos.',
  googleResultTitle: 'Distribución de grupos {date}',
  googleSave: 'Guardar en Google Sheets',
  googleWriteBack: 'Escribir en la hoja original',
  savedToSheet: 'Se escribió en la hoja de cálculo',
  fileResults: 'distribucion-grupos',
  fileRoster: 'lista',
  footer: 'FairClass · ayuda para armar grupos — MIT License',

  statClasses: 'Grupos',
  statClassesSub: '{n} estudiantes distribuidos',
  statGap: 'Diferencia de tamaño',
  statGapSub: '{min}–{max} estudiantes',
  statBalance: 'Equilibrio',
  perfect: 'Perfecto',
  balancePerfectSub: 'Todos los criterios están en su rango ideal',
  balanceSub: 'Estudiantes fuera del rango ideal',
  statViolations: 'Condiciones no cumplidas',
  violationsSub: 'Hay condiciones que no se pudieron cumplir',
  violationsOk: 'Se cumplen todas las condiciones',
  tabClasses: 'Grupos',
  tabBalance: 'Equilibrio',
  tabChecks: 'Revisión',
  tabChecksN: 'Revisión ({n})',
  undoMoves: 'Deshacer mis cambios',
  saveExcel: 'Guardar en Excel',
  moveTitle: 'Mover a {who} →',
  boardHintDesktop: 'Arrastra o haz clic en un estudiante para moverlo a otro grupo.',
  boardHintMobile: 'Desliza para cambiar de grupo. Toca a un estudiante para moverlo a otro grupo.',
  boardHintTail: ' Los totales se actualizan al instante.',
  classChip: '{cls} · {n}',
  studentsN: '{n} estudiantes',
  wantedBadgeTitle: 'Mantener juntos {label}',
  unwantedBadgeTitle: 'Separar {label}',
  unmetSuffix: ' (no se cumple)',
  pairings: 'Condiciones',
  pairingsMet: '{ok} de {n} cumplidas',
  clickToHighlight: 'Haz clic para resaltar a los estudiantes',
  colorize: 'Colorear “juntos”',
  weightN: 'Peso {w}',
  average: 'Promedio',
  averageLevel: 'Promedio',
  even: 'Parejo',
  offBy: 'Desvío {n}',
  ideal: 'Meta',
  allMet: 'Se cumplen todas las condiciones',
  allMetBody: 'Se aplicaron las {w} condiciones de “mantener juntos” y las {u} de “separar”.',
  noPairsBody: 'No se indicaron condiciones.',

  rosterEditorAria: 'Editar lista',
  rosterTitle: 'Lista',
  tabStudentsList: 'Estudiantes',
  tabWanted: 'Juntos',
  tabUnwanted: 'Separar',
  saveRosterTitle: 'Guardar con el formato de la plantilla (se puede volver a cargar)',
  saveRoster: 'Guardar lista',
  saveShort: 'Guardar',
  conflict: 'Hay condiciones contradictorias (estudiantes unidos por “mantener juntos” también están marcados para “separar”): ',
  searchPlaceholder: 'Buscar por N.º o nombre',
  pairFilter: 'Condiciones',
  clearFilters: 'Quitar filtros',
  reapplyTitle: 'Volver a aplicar filtros y orden según tus cambios',
  reapply: 'Aplicar filtros de nuevo',
  countAll: '{n} estudiantes',
  countSome: '{shown} / {total} estudiantes',
  newColPlaceholder: 'Nombre del criterio (p. ej. Liderazgo)',
  kindTitle: 'Tipo de valores',
  kindOptFlag: 'Casilla (✓ / vacío)',
  kindOptCategory: 'Lista (elegir una opción)',
  kindOptDegree: 'Nivel (1–5)',
  kindOptNumeric: 'Número (notas, etc.)',
  cancelShort: 'Cancelar',
  addColumn: 'Criterio',
  addStudent: 'Estudiante',
  selectAllVisible: 'Seleccionar todos los visibles',
  noTaken: 'El N.º {no} ya lo usa otro estudiante',
  namePlaceholder: 'Escribe un nombre',
  confirmDeleteStudent: '¿Quitar a {who} de la lista?',
  colNo: 'N.º',
  colName: 'Nombre',
  deleteColumnTitle: 'Eliminar la columna “{name}”',
  confirmDeleteColumn: '¿Eliminar la columna “{name}”?',
  colPair: 'Condiciones',
  wantedTitleAttr: 'Mantener juntos: {names}',
  unwantedTitleAttr: 'Separar: {names}',
  noMatch: 'Ningún estudiante coincide con los filtros.',
  selectedN: '{n} seleccionados',
  hiddenSelected: ' (no se incluyen {n} ocultos)',
  makeWanted: 'Mantener juntos',
  makeUnwanted: 'Separar',
  confirmDeleteN: '¿Quitar a {n} estudiantes de la lista?',
  bulkHint: 'Con estudiantes seleccionados, los cambios en una celda se aplican a todos',
  clearSelection: 'Quitar selección',
  pairAll: 'Todos',
  pairAny: 'Con condición',
  pairWantedF: 'Con “mantener juntos”',
  pairUnwantedF: 'Con “separar”',
  pairNone: 'Sin condición',
  avg: 'Promedio {v}',
  notEntered: 'Sin datos',
  newOptionPlaceholder: 'Escribe una opción nueva y presiona Enter',
  addOption: '+ Agregar opción',
  listOptions: 'Opciones',
  noOptions: 'Todavía no hay opciones. Agrega una abajo.',
  editOption: 'Renombrar la opción {v}',
  deleteOption: 'Eliminar la opción {v}',
  confirmDeleteOption: '¿Eliminar "{v}" de la lista? Los {n} estudiantes que la tenían quedarán vacíos.',
  duplicateOption: 'Esa opción ya existe',
  listOptionsHint: 'Las opciones que nadie eligió no se guardan al guardar en Excel.',
  columnSettings: 'Ajustes de “{name}”',
  bulkSet: 'Asignar criterio',
  setBlankTitle: 'Dejar vacío',
  blankShort: 'Vacío',
  blankLabel: '(vacío)',
  blankName: 'vacío',
  filterNo: 'no',
  filterYes: 'sí',
  filterCount: '{n} valores',
  flagOption: '{v} (sí)',
  clearThis: 'Quitar este filtro',
  groupsWantedTitle: 'Estudiantes que van juntos',
  groupsUnwantedTitle: 'Estudiantes que se separan',
  groupsWantedDesc: 'Los estudiantes de un conjunto siempre quedan en el mismo grupo.',
  groupsUnwantedDesc: 'Los estudiantes de un conjunto quedan en grupos distintos entre sí siempre que se pueda (con 3 o más, todos separados).',
  groupsBulkHint: ' También puedes seleccionarlos en la lista y crear el conjunto de una vez.',
  newGroup: 'Nuevo conjunto',
  newGroupLabel: 'Nuevo conjunto (2 o más estudiantes)',
  create: 'Crear',
  confirmDeleteGroup: '¿Eliminar el conjunto {label}?',
  deleteGroup: 'Eliminar conjunto',
  confirmGroupDissolve: 'Quedaría un solo estudiante, así que este conjunto se eliminará. ¿Continuar?',
  noGroups: 'Todavía no hay condiciones',
  noName: '(sin nombre)',
  removeMember: 'Quitar',
  addMemberPlaceholder: '+ Agregar por N.º o nombre',
  noInvalid: 'El N.º debe ser un número de 1 en adelante',
  flagMark: '✓',

  googleScriptFailed: 'No se pudo cargar {src}',
  googleAuthFailed: 'Falló el inicio de sesión con Google: {msg}',
  googleApiError: 'Hubo un problema al comunicarse con Google: {msg}',
  googlePickerTitle: 'Elige la hoja de cálculo con la lista',
  googleTemplateTitle: 'Plantilla de lista de FairClass',

  parseRosterMissing: 'No se encontró la hoja “{sheet}” o no tiene datos',
  parseNoStudents: 'No hay estudiantes (escribe el N.º y el nombre desde la fila 3)',
  parseNoMissing: '{sheet}, fila {row}: “{name}” no tiene N.º y no se cargó',
  parseDuplicateNo: 'El N.º {no} está repetido',
  parseUnknownNo: '“{sheet}”, fila {row}: el N.º {no} no está en la lista',
  parseClassCountUnknown: 'No se pudo leer el número de grupos en “{sheet}”; se usaron {k} grupos',
  parseMaxTooSmall: 'Con un máximo de {max} estudiantes × {k} grupos no caben todos, así que no se aplicó el máximo',
}
