import type { WebCopyKey } from './en'

// 先生向けのアプリなので、技術用語を避けたやわらかい言い回しにする（訳語は docs/i18n-glossary.md）
export const JA_COPY: Record<WebCopyKey, string> = {
  docTitle: 'FairClass — バランスの良いクラス編成',
  metaDescription: 'FairClass — 生徒一人ひとりの個性がバランスよく分かれるよう、クラス編成をお手伝いします。データはブラウザの中だけで扱います。',
  tagline: 'クラス編成のお手伝い',
  language: '言語',
  close: '閉じる',
  cancel: 'キャンセル',
  delete: '削除',
  edit: '編集',
  add: '追加',

  heroBadge: 'たくさんの組み合わせから、いちばん良い案を',
  heroTitle1: '個性が響き合う、',
  heroTitle2a: 'バランスの良い',
  heroTitle2b: 'クラスを。',
  heroDesc:
    '性別・学力・支援の必要性など、生徒の特性が各クラスに均等に分かれるよう自動で編成します。「同じ組にしたい」「別の組にしたい」組み合わせも考えに入れます。結果はその場で手直しできます。年度はじめのクラス編成だけでなく、授業の班分けや席替え、行事のグループ分けにも、一年を通して何度でも使えます。',
  heroLocal: 'データはブラウザの中だけで扱います',
  heroFree: 'アカウント登録なし・無料で使えます',
  warningsTitle: '読み込み時の注意',

  step1Title: '名簿を読み込む',
  step1Desc: 'ひな形の Excel に生徒の特性を書き込んで読み込みます。データはブラウザの外に送られません。',
  step1DescGoogle: 'ひな形に生徒の特性を書き込み、Excel または Google スプレッドシートから読み込みます。データはブラウザと Google の間だけでやり取りします。',
  dropTitle: 'Excel ファイルをここに置く',
  dropSub: 'またはクリックして選択（.xlsx）',
  dropAgain: 'クリックして別のファイルを選択',
  googleSheets: 'Google スプレッドシート',
  googleSelect: 'Google アカウントで選択',
  templateExcel: 'Excel ひな形',
  templateDownload: 'ひな形をダウンロード',
  openTemplate: '作成したひな形を開く',
  createTemplate: 'スプレッドシートでひな形を作成',
  trySamples: 'サンプルで試す',
  samplePrefix: 'サンプル: {label}',
  sample1: 'クラス分け（80名・4組）',
  sample2: 'クラス分け（80名・シンプル）',
  sampleGroup: 'グループ分け（30名・6班）',

  step2Title: '条件を調整する',
  step2Desc: '重みが大きい項目ほど優先して均等にします。0 にするとその項目は考えに入れません。',
  studentsLabel: '生徒数',
  openRoster: '名簿を開く',
  personUnit: '名',
  rosterHint: '一覧・絞り込み・編集',
  classCount: 'クラス（グループ）数',
  decrease: '減らす',
  increase: '増やす',
  perClass: '1組あたり {range} 名',
  searchTime: '考える時間',
  quick: '高速',
  standard: '標準',
  thorough: '徹底',
  timeInfo: '{s} 秒かけて考えます',
  colItem: '項目',
  colKind: '種類 / 値',
  colWeight: '重み',
  kindFlag: '該当',
  kindCategory: 'カテゴリ',
  kindNumeric: '数値',
  blankOnly: '（空欄のみ）',
  pairWanted: '同じ組にする',
  pairUnwanted: '別の組にする',
  countItems: '{n} 件',
  noPairsAdd: '指定なし — クリックして追加',

  runTitle: '編成する',
  runDesc: 'たくさんの組み合わせを同時に試して、いちばんバランスの良い案を選びます。',
  searching: 'バランスの良い組み合わせを考えています… {p}%',
  stop: 'やめる',
  runBtn: 'クラスを編成する',
  rerun: 'もう一度編成する',
  lastRun: '前回: {workers} か所で同時に考え、{m}M 通りの組み合わせを試しました',
  discarded: '編成している間に名簿が変わったため、今回の結果は使えませんでした。もう一度編成してください。',
  googleResultTitle: 'クラス編成結果 {date}',
  googleSave: 'スプレッドシートに保存',
  googleWriteBack: '元のシートに書き出す',
  savedToSheet: 'スプレッドシートに書き出しました',
  fileResults: 'クラス編成結果',
  fileRoster: '名簿',
  footer: 'FairClass · クラス編成のお手伝い — MIT License',

  statClasses: 'クラス',
  statClassesSub: '{n} 名を編成',
  statGap: '人数差',
  statGapSub: '{min}〜{max} 名',
  statBalance: 'バランス',
  perfect: '完全',
  balancePerfectSub: '全項目が理想の範囲内',
  balanceSub: '理想の範囲からのずれ（人）',
  statViolations: '守れなかった指定',
  violationsSub: '守れなかったペア指定があります',
  violationsOk: 'ペア指定はすべて守れています',
  tabClasses: 'クラス一覧',
  tabBalance: 'バランスの内訳',
  tabChecks: '指定の確認',
  tabChecksN: '指定の確認 ({n})',
  undoMoves: '手直しを元に戻す',
  saveExcel: 'Excel で保存',
  moveTitle: '{who} の移動先 →',
  boardHintDesktop: '生徒をドラッグするか押すと、別の組へ移せます。',
  boardHintMobile: '左右にスワイプしてクラスを切り替えます。生徒を押すと別の組へ移せます。',
  boardHintTail: '集計もすぐに変わります。',
  classChip: '{cls} {n}名',
  studentsN: '{n} 名',
  wantedBadgeTitle: '同じ組にする指定 {label}',
  unwantedBadgeTitle: '別の組にする指定 {label}',
  unmetSuffix: '（満たせていません）',
  pairings: 'ペア指定',
  pairingsMet: '{ok} / {n} 件を満たしています',
  clickToHighlight: 'クリックでメンバーを強調',
  colorize: '同じ組を色分け',
  weightN: '重み {w}',
  average: '平均値',
  averageLevel: '平均',
  even: '均等',
  offBy: 'ずれ {n}',
  ideal: '理想',
  allMet: 'すべての指定を守れています',
  allMetBody: '同じ組 {w} 件・別の組 {u} 件の指定をすべて反映できました。',
  noPairsBody: 'ペアの指定はありません。',

  rosterEditorAria: '名簿の編集',
  rosterTitle: '名簿',
  tabStudentsList: '生徒一覧',
  tabWanted: '同じ組',
  tabUnwanted: '別の組',
  saveRosterTitle: 'ひな形と同じ形式で保存（あとで読み込み直せます）',
  saveRoster: '名簿を保存',
  saveShort: '保存',
  conflict: '指定が食い違っています（同じ組でつながる生徒が別の組にも指定されています）: ',
  searchPlaceholder: 'NO・名前で検索',
  pairFilter: 'ペア',
  clearFilters: '絞り込みをやめる',
  reapplyTitle: '編集した内容に合わせて、絞り込みと並べ替えをやり直す',
  reapply: '絞り込みをやり直す',
  countAll: '{n} 名',
  countSome: '{shown} / {total} 名',
  newColPlaceholder: '項目名（例: リーダー）',
  kindTitle: '値の種類',
  kindOptFlag: '○ / 空欄',
  kindOptCategory: '段階・カテゴリ',
  kindOptNumeric: '数値（点数など）',
  cancelShort: 'やめる',
  addColumn: '項目',
  addStudent: '生徒',
  selectAllVisible: '表示中をすべて選択',
  noTaken: 'NO {no} は他の生徒が使っています',
  namePlaceholder: '名前を入力',
  confirmDeleteStudent: '{who} を名簿から削除しますか？',
  colNo: 'NO',
  colName: '名前',
  deleteColumnTitle: '「{name}」列を削除',
  confirmDeleteColumn: '「{name}」列を削除しますか？',
  colPair: 'ペア',
  wantedTitleAttr: '同じ組: {names}',
  unwantedTitleAttr: '別の組: {names}',
  noMatch: '条件に合う生徒がいません。',
  selectedN: '{n} 名を選択',
  hiddenSelected: '（非表示の {n} 名は対象外）',
  makeWanted: '同じ組にする',
  makeUnwanted: '別の組にする',
  confirmDeleteN: '{n} 名を名簿から削除しますか？',
  bulkHint: '選択中はセルの変更が選択した全員に反映されます',
  clearSelection: '選択解除',
  pairAll: 'すべて',
  pairAny: '指定あり',
  pairWantedF: '同じ組の指定あり',
  pairUnwantedF: '別の組の指定あり',
  pairNone: '指定なし',
  avg: '平均 {v}',
  notEntered: '未入力',
  newValuePrompt: '新しい値を入力',
  newValueOption: '＋ 新しい値…',
  bulkSet: '項目を一括設定',
  setBlankTitle: '空欄にする',
  blankShort: '空',
  blankLabel: '（空欄）',
  blankName: '空欄',
  filterNo: 'なし',
  filterYes: 'あり',
  filterCount: '{n}件',
  flagOption: '{v}（該当）',
  clearThis: 'この絞り込みをやめる',
  groupsWantedTitle: '同じ組にするグループ',
  groupsUnwantedTitle: '別の組にするグループ',
  groupsWantedDesc: 'グループ内の生徒は必ず同じ組に配置されます。',
  groupsUnwantedDesc: 'グループ内の生徒はできる限り互いに別の組に配置されます（3人以上なら全員が別々）。',
  groupsBulkHint: ' 生徒一覧でチェックして一括作成もできます。',
  newGroup: '新しいグループ',
  newGroupLabel: '新しいグループ（2人以上）',
  create: '作成',
  confirmDeleteGroup: '{label} のグループを削除しますか？',
  deleteGroup: 'グループを削除',
  confirmGroupDissolve: 'メンバーが1人になるため、このグループは削除されます。よろしいですか？',
  noGroups: 'まだ指定はありません',
  noName: '（名前なし）',
  removeMember: '外す',
  addMemberPlaceholder: '＋ NO か名前で追加',
  noInvalid: 'NO は 1 以上の数字で入れてください',
  flagMark: '○',

  googleScriptFailed: '{src} を読み込めませんでした',
  googleAuthFailed: 'Google へのログインに失敗しました: {msg}',
  googleApiError: 'Google とのやり取りでエラーが起きました: {msg}',
  googlePickerTitle: '名簿のスプレッドシートを選択',
  googleTemplateTitle: 'FairClass 名簿ひな形',

  parseRosterMissing: '「{sheet}」シートが見つからないか、データがありません',
  parseNoStudents: '生徒のデータがありません（3行目から下に NO と名前を入れてください）',
  parseNoMissing: '{sheet} {row}行目: 「{name}」の NO が空欄だったため、読み込んでいません',
  parseDuplicateNo: '出席番号 {no} が2人以上に付いています',
  parseUnknownNo: '「{sheet}」{row}行目: 出席番号 {no} は名簿にありません',
  parseClassCountUnknown: '「{sheet}」シートのクラス数が読み取れなかったので、{k} クラスにしました',
  parseMaxTooSmall: '1クラス最大 {max} 人 × {k} クラスでは全員が入りきらないため、最大人数の設定は使いませんでした',
}
