import type { WebCopyKey } from './en'

// 日本語は多言語化の前と一字一句同じ文言にする（既存の利用者の見た目を変えない）
export const JA_COPY: Record<WebCopyKey, string> = {
  docTitle: 'Mosaic — クラス編成最適化',
  metaDescription: 'Mosaic — 生徒の個性をバランスよく配置するクラス編成最適化ツール。データはブラウザ内だけで処理されます。',
  tagline: 'クラス編成オプティマイザー',
  language: '言語',
  close: '閉じる',
  cancel: 'キャンセル',
  delete: '削除',
  edit: '編集',
  add: '追加',

  heroBadge: '焼きなまし法 × 並列マルチスタート',
  heroTitle1: '個性が響き合う、',
  heroTitle2a: 'バランスの良い',
  heroTitle2b: 'クラスを。',
  heroDesc:
    '性別・学力・支援の必要性など、生徒の特性が各クラスに均等に散らばるよう自動で編成します。「同じ組にしたい」「別の組にしたい」組み合わせも考慮。結果はその場で手直しできます。',
  heroLocal: 'データはブラウザ内だけで処理',
  heroFree: '登録・トークン不要、完全無料',
  warningsTitle: '読み込み時の注意',

  step1Title: '名簿を読み込む',
  step1Desc: 'ひな形の Excel に生徒の特性を記入してアップロード。データはブラウザの外に送信されません。',
  step1DescGoogle: 'ひな形に生徒の特性を記入し、Excel または Google スプレッドシートから読み込み。データはブラウザと Google の間でのみやり取りします。',
  dropTitle: 'Excel ファイルをドロップ',
  dropSub: 'またはクリックして選択（.xlsx）',
  dropAgain: 'クリックして別のファイルを選択',
  googleSheets: 'Google スプレッドシート',
  googleSelect: 'Google アカウントで選択',
  templateExcel: 'Excel ひな形',
  templateDownload: 'ひな形をダウンロード',
  openTemplate: '作成したひな形を開く',
  createTemplate: 'スプレッドシートでひな形を作成',
  trySamples: 'サンプルで試す',
  samplePrefix: 'サンプル: {label}',
  sample1: 'クラス分け（80名・4組）',
  sample2: 'クラス分け（80名・シンプル）',
  sampleGroup: 'グループ分け（30名・6班）',

  step2Title: '条件を調整する',
  step2Desc: '重みが大きい項目ほど優先して均等にします。0 にすると無視します。',
  studentsLabel: '生徒数',
  openRoster: '名簿を開く',
  personUnit: '名',
  rosterHint: '一覧・絞り込み・編集',
  classCount: 'クラス（グループ）数',
  decrease: '減らす',
  increase: '増やす',
  perClass: '1組あたり {range} 名',
  searchTime: '探索時間',
  quick: '高速',
  standard: '標準',
  thorough: '徹底',
  timeInfo: '{s} 秒 × 並列探索',
  colItem: '項目',
  colKind: '種類 / 値',
  colWeight: '重み',
  kindFlag: '該当',
  kindCategory: 'カテゴリ',
  kindNumeric: '数値',
  blankOnly: '（空欄のみ）',
  pairWanted: '同じ組にする',
  pairUnwanted: '別の組にする',
  countItems: '{n} 件',
  noPairsAdd: '指定なし — クリックして追加',

  runTitle: '編成する',
  runDesc: '複数の CPU コアで同時に探索し、最もバランスの良い案を採用します。',
  searching: '最適な組み合わせを探索中… {p}%',
  stop: '中止',
  runBtn: 'クラス編成を実行',
  rerun: 'もう一度編成する',
  lastRun: '前回: {workers} 並列 · {m}M 回の探索',
  discarded: '実行中に名簿が変更されたため、結果を破棄しました。もう一度実行してください。',
  googleResultTitle: 'クラス編成結果 {date}',
  googleSave: 'スプレッドシートに保存',
  googleWriteBack: '元のシートに書き出す',
  savedToSheet: 'スプレッドシートに書き出しました',
  fileResults: 'クラス編成結果',
  fileRoster: '名簿',
  footer: 'Mosaic · クラス編成オプティマイザー — MIT License',

  statClasses: 'クラス',
  statClassesSub: '{n} 名を編成',
  statGap: '人数差',
  statGapSub: '{min}〜{max} 名',
  statBalance: 'バランス',
  perfect: '完全',
  balancePerfectSub: '全項目が理想の範囲内',
  balanceSub: '理想範囲からのずれ（人）',
  statViolations: '条件違反',
  violationsSub: 'ペア条件を満たせていません',
  violationsOk: 'ペア条件をすべて満たしています',
  tabClasses: 'クラス一覧',
  tabBalance: 'バランス分析',
  tabChecks: '条件チェック',
  tabChecksN: '条件チェック ({n})',
  undoMoves: '手動変更を戻す',
  saveExcel: 'Excel で保存',
  moveTitle: '{who} を移動 →',
  boardHintDesktop: '生徒をドラッグ、またはクリックして別の組へ移動できます。',
  boardHintMobile: '左右にスワイプしてクラスを切り替え。生徒をタップすると別の組へ移動できます。',
  boardHintTail: '集計は即座に再計算されます。',
  classChip: '{cls} {n}名',
  studentsN: '{n} 名',
  wantedBadgeTitle: '同じ組にする指定 {label}',
  unwantedBadgeTitle: '別の組にする指定 {label}',
  unmetSuffix: '（満たせていません）',
  pairings: 'ペア指定',
  pairingsMet: '{ok} / {n} 件を満たしています',
  clickToHighlight: 'クリックでメンバーを強調',
  colorize: '同じ組を色分け',
  weightN: '重み {w}',
  average: '平均値',
  averageLevel: '平均',
  even: '均等',
  offBy: 'ずれ {n}',
  ideal: '理想',
  allMet: 'すべての条件を満たしています',
  allMetBody: '同じ組 {w} 件・別の組 {u} 件の指定をすべて反映しました。',
  noPairsBody: 'ペアの指定はありません。',

  rosterEditorAria: '名簿エディタ',
  rosterTitle: '名簿',
  tabStudentsList: '生徒一覧',
  tabWanted: '同じ組',
  tabUnwanted: '別の組',
  saveRosterTitle: 'ひな形と同じ形式で保存（再読み込み可能）',
  saveRoster: '名簿を保存',
  saveShort: '保存',
  conflict: '矛盾する指定があります（同じ組でつながる生徒が別の組にも指定）: ',
  searchPlaceholder: 'NO・名前で検索',
  pairFilter: 'ペア',
  clearFilters: '条件をクリア',
  reapplyTitle: '編集内容に合わせて絞り込み・並べ替えをやり直す',
  reapply: '絞り込みを再適用',
  countAll: '{n} 名',
  countSome: '{shown} / {total} 名',
  newColPlaceholder: '項目名（例: リーダー）',
  kindTitle: '値の種類',
  kindOptFlag: '○ / 空欄',
  kindOptCategory: '段階・カテゴリ',
  kindOptNumeric: '数値（点数など）',
  cancelShort: '取消',
  addColumn: '項目',
  addStudent: '生徒',
  selectAllVisible: '表示中をすべて選択',
  noTaken: 'NO {no} は他の生徒が使っています',
  namePlaceholder: '名前を入力',
  confirmDeleteStudent: '{who} を名簿から削除しますか？',
  colNo: 'NO',
  colName: '名前',
  deleteColumnTitle: '「{name}」列を削除',
  confirmDeleteColumn: '「{name}」列を削除しますか？',
  colPair: 'ペア',
  wantedTitleAttr: '同じ組: {names}',
  unwantedTitleAttr: '別の組: {names}',
  noMatch: '条件に合う生徒がいません。',
  selectedN: '{n} 名を選択',
  hiddenSelected: '（非表示の {n} 名は対象外）',
  makeWanted: '同じ組にする',
  makeUnwanted: '別の組にする',
  confirmDeleteN: '{n} 名を名簿から削除しますか？',
  bulkHint: '選択中はセルの変更が選択した全員に反映されます',
  clearSelection: '選択解除',
  pairAll: 'すべて',
  pairAny: '指定あり',
  pairWantedF: '同じ組の指定あり',
  pairUnwantedF: '別の組の指定あり',
  pairNone: '指定なし',
  avg: '平均 {v}',
  notEntered: '未入力',
  newValuePrompt: '新しい値を入力',
  newValueOption: '＋ 新しい値…',
  bulkSet: '項目を一括設定',
  setBlankTitle: '空欄にする',
  blankShort: '空',
  blankLabel: '（空欄）',
  blankName: '空欄',
  filterNo: 'なし',
  filterYes: 'あり',
  filterCount: '{n}件',
  flagOption: '{v}（該当）',
  clearThis: 'この条件をクリア',
  groupsWantedTitle: '同じ組にするグループ',
  groupsUnwantedTitle: '別の組にするグループ',
  groupsWantedDesc: 'グループ内の生徒は必ず同じ組に配置されます。',
  groupsUnwantedDesc: 'グループ内の生徒はできる限り互いに別の組に配置されます（3人以上なら全員が別々）。',
  groupsBulkHint: ' 生徒一覧でチェックして一括作成もできます。',
  newGroup: '新しいグループ',
  newGroupLabel: '新しいグループ（2人以上）',
  create: '作成',
  confirmDeleteGroup: '{label} のグループを削除しますか？',
  deleteGroup: 'グループを削除',
  confirmGroupDissolve: 'メンバーが1人になるため、このグループは削除されます。よろしいですか？',
  noGroups: 'まだ指定はありません',
  noName: '（名前なし）',
  removeMember: '外す',
  addMemberPlaceholder: '＋ NO か名前で追加',
  noInvalid: 'NO は 1 以上の整数で入力してください',
  flagMark: '○',

  googleScriptFailed: '{src} を読み込めませんでした',
  googleAuthFailed: 'Google 認証に失敗しました: {msg}',
  googleApiError: 'Google API エラー: {msg}',
  googlePickerTitle: '名簿のスプレッドシートを選択',
  googleTemplateTitle: 'Mosaic 名簿ひな形',

  parseRosterMissing: '「{sheet}」シートが見つからないか、データがありません',
  parseNoStudents: '生徒データがありません（3行目以降に NO と名前を入力してください）',
  parseNoMissing: '{sheet} {row}行目: 「{name}」の NO が空欄のため読み込みませんでした',
  parseDuplicateNo: '出席番号 {no} が重複しています',
  parseUnknownNo: '「{sheet}」{row}行目: 出席番号 {no} は名簿にありません',
  parseClassCountUnknown: '「{sheet}」シートのクラス数が読み取れないため {k} クラスとしました',
  parseMaxTooSmall: '1クラスの最大人数 {max} × {k} クラスでは全員が収まりません。最大人数を無視します',
}
