import type { WebCopyKey } from './en'

// 합니다체. 용어는 docs/i18n-glossary.md（반 편성・같은 반 배정・분리 배정）
export const KO_COPY: Record<WebCopyKey, string> = {
  docTitle: 'Mosaic — 반 편성 최적화',
  metaDescription: 'Mosaic — 학생의 특성을 각 반에 고르게 나누는 반 편성 최적화 도구. 데이터는 브라우저 안에서만 처리됩니다.',
  tagline: '반 편성 최적화 도구',
  language: '언어',
  close: '닫기',
  cancel: '취소',
  delete: '삭제',
  edit: '편집',
  add: '추가',

  heroBadge: '담금질 기법 × 병렬 다중 시작',
  heroTitle1: '한 명 한 명이 어울리는',
  heroTitle2a: '균형 잡힌',
  heroTitle2b: '반 편성을.',
  heroDesc:
    '성별, 학업, 지원 필요 여부 등 학생의 특성이 각 반에 고르게 나뉘도록 자동으로 편성합니다. "같은 반 배정"과 "분리 배정" 조건도 반영하며, 결과는 바로 고칠 수 있습니다.',
  heroLocal: '데이터는 브라우저 안에서만 처리',
  heroFree: '회원 가입 없이 완전 무료',
  warningsTitle: '불러올 때의 안내',

  step1Title: '명단 불러오기',
  step1Desc: '엑셀 양식에 학생 특성을 입력해 올려 주십시오. 데이터는 브라우저 밖으로 전송되지 않습니다.',
  step1DescGoogle: '양식에 학생 특성을 입력하고 엑셀 또는 Google 스프레드시트에서 불러옵니다. 데이터는 브라우저와 Google 사이에서만 오갑니다.',
  dropTitle: '엑셀 파일을 끌어다 놓기',
  dropSub: '또는 클릭해서 선택(.xlsx)',
  dropAgain: '클릭해서 다른 파일 선택',
  googleSheets: 'Google 스프레드시트',
  googleSelect: 'Google 계정으로 선택',
  templateExcel: '엑셀 양식',
  templateDownload: '양식 내려받기',
  openTemplate: '만든 양식 열기',
  createTemplate: '스프레드시트로 양식 만들기',
  trySamples: '예시로 해 보기',
  samplePrefix: '예시: {label}',
  sample1: '반 편성(학생 80명·4개 반)',
  sample2: '반 편성(학생 80명·간단)',
  sampleGroup: '모둠 편성(30명·6모둠)',

  step2Title: '조건 조정',
  step2Desc: '가중치가 큰 항목일수록 먼저 고르게 나눕니다. 0이면 반영하지 않습니다.',
  studentsLabel: '학생 수',
  openRoster: '명단 열기',
  personUnit: '명',
  rosterHint: '목록·필터·편집',
  classCount: '반(모둠) 수',
  decrease: '줄이기',
  increase: '늘리기',
  perClass: '반마다 {range}명',
  searchTime: '탐색 시간',
  quick: '빠르게',
  standard: '표준',
  thorough: '꼼꼼하게',
  timeInfo: '{s}초 × 병렬 탐색',
  colItem: '항목',
  colKind: '종류 / 값',
  colWeight: '가중치',
  kindFlag: '해당',
  kindCategory: '범주',
  kindNumeric: '숫자',
  blankOnly: '(빈칸만)',
  pairWanted: '같은 반 배정',
  pairUnwanted: '분리 배정',
  countItems: '{n}건',
  noPairsAdd: '조건 없음 — 클릭해서 추가',

  runTitle: '편성하기',
  runDesc: '여러 CPU 코어에서 동시에 탐색해 가장 균형 잡힌 안을 고릅니다.',
  searching: '가장 좋은 조합을 찾는 중… {p}%',
  stop: '중지',
  runBtn: '반 편성 실행',
  rerun: '다시 편성',
  lastRun: '이전: {workers}개 병렬 · {m}M회 탐색',
  discarded: '실행 중에 명단이 바뀌어 결과를 버렸습니다. 다시 실행하십시오.',
  googleResultTitle: '반 편성 결과 {date}',
  googleSave: '스프레드시트에 저장',
  googleWriteBack: '원래 시트에 내보내기',
  savedToSheet: '스프레드시트에 내보냈습니다',
  fileResults: '반편성_결과',
  fileRoster: '명단',
  footer: 'Mosaic · 반 편성 최적화 도구 — MIT License',

  statClasses: '반',
  statClassesSub: '학생 {n}명 편성',
  statGap: '인원 차',
  statGapSub: '{min}~{max}명',
  statBalance: '균형',
  perfect: '완벽',
  balancePerfectSub: '모든 항목이 목표 범위 안',
  balanceSub: '목표 범위를 벗어난 인원',
  statViolations: '충족하지 못한 조건',
  violationsSub: '충족하지 못한 배정 조건이 있습니다',
  violationsOk: '배정 조건을 모두 충족합니다',
  tabClasses: '반별 명단',
  tabBalance: '균형 분석',
  tabChecks: '조건 확인',
  tabChecksN: '조건 확인 ({n})',
  undoMoves: '직접 옮긴 것 되돌리기',
  saveExcel: '엑셀로 저장',
  moveTitle: '{who} 이동 →',
  boardHintDesktop: '학생을 끌어다 놓거나 클릭하면 다른 반으로 옮길 수 있습니다.',
  boardHintMobile: '좌우로 넘겨 반을 바꾸십시오. 학생을 누르면 다른 반으로 옮길 수 있습니다.',
  boardHintTail: ' 집계는 바로 다시 계산됩니다.',
  classChip: '{cls} {n}명',
  studentsN: '{n}명',
  wantedBadgeTitle: '같은 반 배정 {label}',
  unwantedBadgeTitle: '분리 배정 {label}',
  unmetSuffix: '(충족하지 못함)',
  pairings: '배정 조건',
  pairingsMet: '{n}건 중 {ok}건 충족',
  clickToHighlight: '클릭하면 해당 학생을 강조',
  colorize: '같은 반 배정 색 표시',
  weightN: '가중치 {w}',
  average: '평균',
  averageLevel: '평균',
  even: '균등',
  offBy: '차이 {n}',
  ideal: '목표',
  allMet: '모든 조건을 충족합니다',
  allMetBody: '같은 반 배정 {w}건, 분리 배정 {u}건을 모두 반영했습니다.',
  noPairsBody: '배정 조건이 없습니다.',

  rosterEditorAria: '명단 편집기',
  rosterTitle: '명단',
  tabStudentsList: '학생 목록',
  tabWanted: '같은 반',
  tabUnwanted: '분리',
  saveRosterTitle: '양식과 같은 형식으로 저장(다시 불러올 수 있음)',
  saveRoster: '명단 저장',
  saveShort: '저장',
  conflict: '서로 맞지 않는 조건이 있습니다(같은 반 배정으로 이어진 학생이 분리 배정에도 지정됨): ',
  searchPlaceholder: '번호·이름으로 찾기',
  pairFilter: '배정 조건',
  clearFilters: '필터 지우기',
  reapplyTitle: '편집한 내용에 맞춰 필터·정렬을 다시 적용',
  reapply: '필터 다시 적용',
  countAll: '{n}명',
  countSome: '{shown} / {total}명',
  newColPlaceholder: '항목 이름(예: 반장)',
  kindTitle: '값의 종류',
  kindOptFlag: '✓ / 빈칸',
  kindOptCategory: '단계·범주',
  kindOptNumeric: '숫자(점수 등)',
  cancelShort: '취소',
  addColumn: '항목',
  addStudent: '학생',
  selectAllVisible: '표시된 학생 모두 선택',
  noTaken: '번호 {no}은(는) 다른 학생이 사용 중입니다',
  namePlaceholder: '이름 입력',
  confirmDeleteStudent: '{who} 학생을 명단에서 삭제하시겠습니까?',
  colNo: '번호',
  colName: '이름',
  deleteColumnTitle: '"{name}" 열 삭제',
  confirmDeleteColumn: '"{name}" 열을 삭제하시겠습니까?',
  colPair: '배정 조건',
  wantedTitleAttr: '같은 반 배정: {names}',
  unwantedTitleAttr: '분리 배정: {names}',
  noMatch: '필터에 맞는 학생이 없습니다.',
  selectedN: '{n}명 선택',
  hiddenSelected: '(숨겨진 {n}명은 제외)',
  makeWanted: '같은 반 배정',
  makeUnwanted: '분리 배정',
  confirmDeleteN: '{n}명을 명단에서 삭제하시겠습니까?',
  bulkHint: '선택 중에는 셀을 바꾸면 선택한 학생 모두에게 반영됩니다',
  clearSelection: '선택 해제',
  pairAll: '전체',
  pairAny: '조건 있음',
  pairWantedF: '같은 반 배정 있음',
  pairUnwantedF: '분리 배정 있음',
  pairNone: '조건 없음',
  avg: '평균 {v}',
  notEntered: '미입력',
  newValuePrompt: '새 값을 입력하십시오',
  newValueOption: '+ 새 값…',
  bulkSet: '항목 일괄 설정',
  setBlankTitle: '빈칸으로',
  blankShort: '빈칸',
  blankLabel: '(빈칸)',
  blankName: '빈칸',
  filterNo: '없음',
  filterYes: '있음',
  filterCount: '{n}개',
  flagOption: '{v}(해당)',
  clearThis: '이 필터 지우기',
  groupsWantedTitle: '같은 반에 배정할 묶음',
  groupsUnwantedTitle: '분리 배정할 묶음',
  groupsWantedDesc: '묶음 안의 학생은 반드시 같은 반에 배정됩니다.',
  groupsUnwantedDesc: '묶음 안의 학생은 가능한 한 서로 다른 반에 배정됩니다(3명 이상이면 모두 따로).',
  groupsBulkHint: ' 학생 목록에서 선택해 한꺼번에 만들 수도 있습니다.',
  newGroup: '새 묶음',
  newGroupLabel: '새 묶음(2명 이상)',
  create: '만들기',
  confirmDeleteGroup: '{label} 묶음을 삭제하시겠습니까?',
  deleteGroup: '묶음 삭제',
  confirmGroupDissolve: '한 명만 남으므로 이 묶음은 삭제됩니다. 계속하시겠습니까?',
  noGroups: '아직 조건이 없습니다',
  noName: '(이름 없음)',
  removeMember: '빼기',
  addMemberPlaceholder: '+ 번호나 이름으로 추가',
  noInvalid: '번호는 1 이상의 정수로 입력하십시오',
  flagMark: '✓',

  googleScriptFailed: '{src}을(를) 불러오지 못했습니다',
  googleAuthFailed: 'Google 인증에 실패했습니다: {msg}',
  googleApiError: 'Google API 오류: {msg}',
  googlePickerTitle: '명단 스프레드시트 선택',
  googleTemplateTitle: 'Mosaic 명단 양식',

  parseRosterMissing: '"{sheet}" 시트가 없거나 데이터가 없습니다',
  parseNoStudents: '학생 데이터가 없습니다(3행부터 번호와 이름을 입력하십시오)',
  parseNoMissing: '{sheet} {row}행: "{name}" 학생의 번호가 비어 있어 불러오지 않았습니다',
  parseDuplicateNo: '번호 {no}이(가) 중복되었습니다',
  parseUnknownNo: '"{sheet}" {row}행: 번호 {no}은(는) 명단에 없습니다',
  parseClassCountUnknown: '"{sheet}" 시트의 반 수를 읽을 수 없어 {k}개 반으로 정했습니다',
  parseMaxTooSmall: '반별 최대 {max}명 × {k}개 반으로는 모두 들어가지 않아 최대 인원은 무시했습니다',
}
