import type { WebCopyKey } from './en'

// Português do Brasil, tratamento “você”. Termos: docs/i18n-glossary.md（turma, manter juntos, separar）
export const PT_BR_COPY: Record<WebCopyKey, string> = {
  docTitle: 'Mosaic — Enturmação equilibrada',
  metaDescription: 'O Mosaic distribui os alunos em turmas equilibradas de forma automática. Os dados são processados só no seu navegador.',
  tagline: 'Otimizador de enturmação',
  language: 'Idioma',
  close: 'Fechar',
  cancel: 'Cancelar',
  delete: 'Excluir',
  edit: 'Editar',
  add: 'Adicionar',

  heroBadge: 'Recozimento simulado × busca paralela',
  heroTitle1: 'Cada aluno conta:',
  heroTitle2a: 'turmas equilibradas',
  heroTitle2b: 'em segundos.',
  heroDesc:
    'O Mosaic distribui gênero, desempenho, necessidades de apoio e outros critérios de forma equilibrada entre as turmas. Também respeita quem manter juntos ou separar, e você pode ajustar o resultado na hora.',
  heroLocal: 'Os dados são processados só no navegador',
  heroFree: 'Sem cadastro nem conta, totalmente grátis',
  warningsTitle: 'Avisos ao carregar',

  step1Title: 'Carregar a lista de alunos',
  step1Desc: 'Preencha o modelo de Excel com os critérios dos alunos e envie. Os dados não saem do navegador.',
  step1DescGoogle: 'Preencha o modelo e carregue pelo Excel ou pelo Planilhas Google. Os dados só trafegam entre o navegador e o Google.',
  dropTitle: 'Solte um arquivo do Excel',
  dropSub: 'ou clique para escolher (.xlsx)',
  dropAgain: 'Clique para escolher outro arquivo',
  googleSheets: 'Planilhas Google',
  googleSelect: 'Escolher com a conta Google',
  templateExcel: 'Modelo do Excel',
  templateDownload: 'Baixar modelo',
  openTemplate: 'Abrir o modelo criado',
  createTemplate: 'Criar modelo no Planilhas Google',
  trySamples: 'Testar com um exemplo',
  samplePrefix: 'Exemplo: {label}',
  sample1: 'Turmas (80 alunos, 4 turmas)',
  sample2: 'Turmas (80 alunos, simples)',
  sampleGroup: 'Grupos de trabalho (30 alunos, 6 grupos)',

  step2Title: 'Ajustar as condições',
  step2Desc: 'Critérios com peso maior são equilibrados primeiro. Com peso 0 o critério é ignorado.',
  studentsLabel: 'Alunos',
  openRoster: 'Abrir a lista',
  personUnit: 'alunos',
  rosterHint: 'Lista, filtros e edição',
  classCount: 'Número de turmas',
  decrease: 'Diminuir',
  increase: 'Aumentar',
  perClass: '{range} alunos por turma',
  searchTime: 'Tempo de busca',
  quick: 'Rápido',
  standard: 'Padrão',
  thorough: 'Completo',
  timeInfo: '{s} s × busca paralela',
  colItem: 'Critério',
  colKind: 'Tipo / valores',
  colWeight: 'Peso',
  kindFlag: 'Sim/não',
  kindCategory: 'Categoria',
  kindNumeric: 'Número',
  blankOnly: '(só vazios)',
  pairWanted: 'Manter juntos',
  pairUnwanted: 'Separar',
  countItems: '{n}',
  noPairsAdd: 'Nenhuma — clique para adicionar',

  runTitle: 'Montar turmas',
  runDesc: 'Busca em vários núcleos da CPU ao mesmo tempo e fica com a opção mais equilibrada.',
  searching: 'Buscando a melhor combinação… {p}%',
  stop: 'Parar',
  runBtn: 'Montar turmas',
  rerun: 'Montar de novo',
  lastRun: 'Última: {workers} em paralelo · {m} mi iterações',
  discarded: 'A lista mudou durante a busca e o resultado foi descartado. Tente de novo.',
  googleResultTitle: 'Enturmação {date}',
  googleSave: 'Salvar no Planilhas Google',
  googleWriteBack: 'Gravar na planilha original',
  savedToSheet: 'Gravado na planilha',
  fileResults: 'enturmacao',
  fileRoster: 'lista-de-alunos',
  footer: 'Mosaic · otimizador de enturmação — MIT License',

  statClasses: 'Turmas',
  statClassesSub: '{n} alunos distribuídos',
  statGap: 'Diferença de tamanho',
  statGapSub: '{min}–{max} alunos',
  statBalance: 'Equilíbrio',
  perfect: 'Perfeito',
  balancePerfectSub: 'Todos os critérios na faixa ideal',
  balanceSub: 'Alunos fora da faixa ideal',
  statViolations: 'Condições não atendidas',
  violationsSub: 'Algumas condições não foram atendidas',
  violationsOk: 'Todas as condições atendidas',
  tabClasses: 'Turmas',
  tabBalance: 'Equilíbrio',
  tabChecks: 'Verificação',
  tabChecksN: 'Verificação ({n})',
  undoMoves: 'Desfazer mudanças manuais',
  saveExcel: 'Salvar em Excel',
  moveTitle: 'Mover {who} →',
  boardHintDesktop: 'Arraste ou clique em um aluno para movê-lo para outra turma.',
  boardHintMobile: 'Deslize para trocar de turma. Toque em um aluno para movê-lo para outra turma.',
  boardHintTail: ' Os totais são recalculados na hora.',
  classChip: '{cls} · {n}',
  studentsN: '{n} alunos',
  wantedBadgeTitle: 'Manter juntos {label}',
  unwantedBadgeTitle: 'Separar {label}',
  unmetSuffix: ' (não atendida)',
  pairings: 'Condições',
  pairingsMet: '{ok} de {n} atendidas',
  clickToHighlight: 'Clique para destacar os alunos',
  colorize: 'Colorir “juntos”',
  weightN: 'Peso {w}',
  average: 'Média',
  averageLevel: 'Média',
  even: 'Equilibrado',
  offBy: 'Desvio {n}',
  ideal: 'Meta',
  allMet: 'Todas as condições atendidas',
  allMetBody: 'As {w} condições de “manter juntos” e as {u} de “separar” foram aplicadas.',
  noPairsBody: 'Nenhuma condição foi definida.',

  rosterEditorAria: 'Editor da lista de alunos',
  rosterTitle: 'Lista de alunos',
  tabStudentsList: 'Alunos',
  tabWanted: 'Juntos',
  tabUnwanted: 'Separar',
  saveRosterTitle: 'Salvar no formato do modelo (pode ser carregado de novo)',
  saveRoster: 'Salvar lista',
  saveShort: 'Salvar',
  conflict: 'Há condições contraditórias (alunos ligados por “manter juntos” também estão marcados para “separar”): ',
  searchPlaceholder: 'Buscar por nº ou nome',
  pairFilter: 'Condições',
  clearFilters: 'Limpar filtros',
  reapplyTitle: 'Reaplicar filtros e ordenação conforme as edições',
  reapply: 'Reaplicar filtros',
  countAll: '{n} alunos',
  countSome: '{shown} / {total} alunos',
  newColPlaceholder: 'Nome do critério (ex.: Liderança)',
  kindTitle: 'Tipo de valores',
  kindOptFlag: '✓ / vazio',
  kindOptCategory: 'Níveis / categorias',
  kindOptNumeric: 'Número (notas etc.)',
  cancelShort: 'Cancelar',
  addColumn: 'Critério',
  addStudent: 'Aluno',
  selectAllVisible: 'Selecionar todos os visíveis',
  noTaken: 'O nº {no} já é de outro aluno',
  namePlaceholder: 'Digite um nome',
  confirmDeleteStudent: 'Remover {who} da lista?',
  colNo: 'Nº',
  colName: 'Nome',
  deleteColumnTitle: 'Excluir a coluna “{name}”',
  confirmDeleteColumn: 'Excluir a coluna “{name}”?',
  colPair: 'Condições',
  wantedTitleAttr: 'Manter juntos: {names}',
  unwantedTitleAttr: 'Separar: {names}',
  noMatch: 'Nenhum aluno corresponde aos filtros.',
  selectedN: '{n} selecionados',
  hiddenSelected: ' ({n} ocultos não incluídos)',
  makeWanted: 'Manter juntos',
  makeUnwanted: 'Separar',
  confirmDeleteN: 'Remover {n} alunos da lista?',
  bulkHint: 'Com alunos selecionados, a mudança em uma célula vale para todos',
  clearSelection: 'Limpar seleção',
  pairAll: 'Todos',
  pairAny: 'Com condição',
  pairWantedF: 'Com “manter juntos”',
  pairUnwantedF: 'Com “separar”',
  pairNone: 'Sem condição',
  avg: 'Média {v}',
  notEntered: 'Vazio',
  newValuePrompt: 'Digite um novo valor',
  newValueOption: '+ Novo valor…',
  bulkSet: 'Definir critério',
  setBlankTitle: 'Deixar vazio',
  blankShort: 'Vazio',
  blankLabel: '(vazio)',
  blankName: 'vazio',
  filterNo: 'não',
  filterYes: 'sim',
  filterCount: '{n} valores',
  flagOption: '{v} (sim)',
  clearThis: 'Limpar este filtro',
  groupsWantedTitle: 'Alunos que ficam juntos',
  groupsUnwantedTitle: 'Alunos que ficam separados',
  groupsWantedDesc: 'Os alunos de um conjunto sempre ficam na mesma turma.',
  groupsUnwantedDesc: 'Os alunos de um conjunto ficam em turmas diferentes entre si sempre que possível (com 3 ou mais, todos separados).',
  groupsBulkHint: ' Você também pode selecioná-los na lista e criar o conjunto de uma vez.',
  newGroup: 'Novo conjunto',
  newGroupLabel: 'Novo conjunto (2 ou mais alunos)',
  create: 'Criar',
  confirmDeleteGroup: 'Excluir o conjunto {label}?',
  deleteGroup: 'Excluir conjunto',
  confirmGroupDissolve: 'Sobraria só um aluno, então este conjunto será excluído. Continuar?',
  noGroups: 'Ainda não há condições',
  noName: '(sem nome)',
  removeMember: 'Remover',
  addMemberPlaceholder: '+ Adicionar por nº ou nome',
  noInvalid: 'O nº deve ser um número inteiro a partir de 1',
  flagMark: '✓',

  googleScriptFailed: 'Não foi possível carregar {src}',
  googleAuthFailed: 'Falha no login do Google: {msg}',
  googleApiError: 'Erro da API do Google: {msg}',
  googlePickerTitle: 'Escolha a planilha com a lista de alunos',
  googleTemplateTitle: 'Modelo de lista do Mosaic',

  parseRosterMissing: 'A aba “{sheet}” não foi encontrada ou está vazia',
  parseNoStudents: 'Nenhum aluno encontrado (preencha nº e nome a partir da linha 3)',
  parseNoMissing: '{sheet}, linha {row}: “{name}” está sem nº e não foi carregado',
  parseDuplicateNo: 'O nº {no} está repetido',
  parseUnknownNo: '“{sheet}”, linha {row}: o nº {no} não está na lista',
  parseClassCountUnknown: 'Não foi possível ler o número de turmas em “{sheet}”; foram usadas {k} turmas',
  parseMaxTooSmall: 'Com no máximo {max} alunos × {k} turmas não cabem todos, então o máximo foi ignorado',
}
