import type { WebCopyKey } from './en'

// Português do Brasil, tratamento “você”. Termos: docs/i18n-glossary.md（turma, manter juntos, separar）
export const PT_BR_COPY: Record<WebCopyKey, string> = {
  docTitle: 'FairClass — Enturmação equilibrada',
  metaDescription: 'O FairClass ajuda você a distribuir os alunos em turmas equilibradas. Os dados ficam só no seu navegador.',
  tagline: 'Ajuda para montar turmas',
  language: 'Idioma',
  close: 'Fechar',
  cancel: 'Cancelar',
  delete: 'Excluir',
  edit: 'Editar',
  add: 'Adicionar',

  heroBadge: 'A melhor opção entre muitas combinações',
  heroTitle1: 'Cada aluno conta:',
  heroTitle2a: 'turmas equilibradas',
  heroTitle2b: 'em segundos.',
  heroDesc:
    'O FairClass distribui gênero, desempenho, necessidades de apoio e outros critérios de forma equilibrada entre as turmas. Também leva em conta quem manter juntos ou separar, e você pode ajustar o resultado na hora. E não é só no começo do ano: use o ano todo para montar grupos de trabalho, grupos de mesa ou grupos para passeios.',
  heroLocal: 'Os dados ficam só no seu navegador',
  heroFree: 'Sem cadastro nem conta, totalmente grátis',
  warningsTitle: 'Avisos ao carregar',

  step1Title: 'Carregar a lista de alunos',
  step1Desc: 'Preencha o modelo de Excel com os critérios dos alunos e abra aqui. Os dados não saem do navegador.',
  step1DescGoogle: 'Preencha o modelo e carregue pelo Excel ou pelo Planilhas Google. Os dados só trafegam entre o navegador e o Google.',
  dropTitle: 'Solte um arquivo do Excel',
  dropSub: 'ou clique para escolher (.xlsx)',
  googleSheets: 'Planilhas Google',
  googleSelect: 'Escolher com a conta Google',
  templateExcel: 'Modelo do Excel',
  templateDownload: 'Baixar modelo',
  openTemplate: 'Abrir o modelo criado',
  createTemplate: 'Criar modelo no Planilhas Google',
  trySamples: 'Testar com um exemplo',
  samplePrefix: 'Exemplo: {label}',
  sample1: 'Turmas (80 alunos, 4 turmas)',
  sample2: 'Turmas (80 alunos, simples)',
  sampleGroup: 'Grupos de trabalho (30 alunos, 6 grupos)',
  sampleExcelTitle: 'Baixar "{label}" em Excel',
  samplesExcelHint: 'Clique em ⬇ para baixar um exemplo em Excel (grátis). Edite e carregue no quadro acima.',
  currentRoster: 'Lista aberta',
  otherRoster: 'Abrir outra lista',
  backToRoster: 'Cancelar (voltar à lista atual)',
  rosterSummary: '{n} alunos · {cols} critérios · juntos {w} · separar {u}',
  editRoster: 'Editar lista',

  step2Title: 'Ajustar as condições',
  step2Desc: 'Critérios com peso maior são equilibrados primeiro. Com peso 0, o critério não é levado em conta.',
  studentsLabel: 'Alunos',
  openRoster: 'Abrir a lista',
  personUnit: 'alunos',
  rosterHint: 'Lista, filtros e edição',
  classCount: 'Número de turmas',
  decrease: 'Diminuir',
  increase: 'Aumentar',
  perClass: '{range} alunos por turma',
  searchTime: 'Tempo para montar',
  quick: 'Rápido',
  standard: 'Padrão',
  thorough: 'Completo',
  timeInfo: 'Leva {s} segundos',
  colItem: 'Critério',
  colKind: 'Tipo / valores',
  colWeight: 'Peso',
  kindFlag: 'Caixa de seleção',
  kindCategory: 'Lista',
  kindDegree: 'Nível (1–5)',
  kindNumeric: 'Número',
  blankOnly: '(só vazios)',
  pairWanted: 'Manter juntos',
  pairUnwanted: 'Separar',
  countItems: '{n}',
  noPairsAdd: 'Nenhuma — clique para adicionar',

  runTitle: 'Montar turmas',
  runDesc: 'Testa muitas combinações ao mesmo tempo e escolhe a opção mais equilibrada.',
  searching: 'Procurando uma distribuição equilibrada… {p}%',
  stop: 'Parar',
  runBtn: 'Montar turmas',
  rerun: 'Montar de novo',
  lastRun: 'Da última vez: {m} mi combinações testadas, {workers} ao mesmo tempo',
  discarded: 'A lista mudou enquanto as turmas eram montadas, então este resultado não foi usado. Monte de novo.',
  googleResultTitle: 'Enturmação {date}',
  googleSave: 'Salvar no Planilhas Google',
  googleWriteBack: 'Gravar na planilha original',
  savedToSheet: 'Gravado na planilha',
  fileResults: 'enturmacao',
  fileRoster: 'lista-de-alunos',
  footer: 'FairClass · ajuda para montar turmas — MIT License',

  statClasses: 'Turmas',
  statClassesSub: '{n} alunos distribuídos',
  statGap: 'Diferença de tamanho',
  statGapSub: '{min}–{max} alunos',
  statBalance: 'Equilíbrio',
  perfect: 'Perfeito',
  balancePerfectSub: 'Todos os critérios na faixa ideal',
  balanceSub: 'Alunos fora da faixa ideal',
  statViolations: 'Condições não atendidas',
  violationsSub: 'Algumas condições não puderam ser atendidas',
  violationsOk: 'Todas as condições atendidas',
  tabClasses: 'Turmas',
  tabBalance: 'Equilíbrio',
  tabChecks: 'Verificação',
  tabChecksN: 'Verificação ({n})',
  undoMoves: 'Desfazer minhas mudanças',
  saveExcel: 'Salvar em Excel',
  moveTitle: 'Mover {who} →',
  boardHintDesktop: 'Arraste ou clique em um aluno para movê-lo para outra turma.',
  boardHintMobile: 'Deslize para trocar de turma. Toque em um aluno para movê-lo para outra turma.',
  boardHintTail: ' Os totais se atualizam na hora.',
  classChip: '{cls} · {n}',
  studentsN: '{n} alunos',
  wantedBadgeTitle: 'Manter juntos {label}',
  unwantedBadgeTitle: 'Separar {label}',
  unmetSuffix: ' (não atendida)',
  pairings: 'Condições',
  pairingsMet: '{ok} de {n} atendidas',
  clickToHighlight: 'Clique para destacar os alunos',
  colorize: 'Colorir “juntos”',
  weightN: 'Peso {w}',
  average: 'Média',
  averageLevel: 'Média',
  even: 'Equilibrado',
  offBy: 'Desvio {n}',
  ideal: 'Meta',
  allMet: 'Todas as condições atendidas',
  allMetBody: 'As {w} condições de “manter juntos” e as {u} de “separar” foram aplicadas.',
  noPairsBody: 'Nenhuma condição foi definida.',

  rosterEditorAria: 'Editar lista de alunos',
  rosterTitle: 'Lista de alunos',
  tabStudentsList: 'Alunos',
  tabWanted: 'Juntos',
  tabUnwanted: 'Separar',
  saveRosterTitle: 'Salvar no formato do modelo (pode ser carregado de novo)',
  saveRoster: 'Salvar lista',
  saveShort: 'Salvar',
  conflict: 'Há condições contraditórias (alunos ligados por “manter juntos” também estão marcados para “separar”): ',
  searchPlaceholder: 'Buscar por nº ou nome',
  pairFilter: 'Condições',
  clearFilters: 'Limpar filtros',
  reapplyTitle: 'Reaplicar filtros e ordenação conforme as edições',
  reapply: 'Reaplicar filtros',
  countAll: '{n} alunos',
  countSome: '{shown} / {total} alunos',
  newColPlaceholder: 'Nome do critério (ex.: Liderança)',
  kindTitle: 'Tipo de valores',
  kindOptFlag: 'Caixa de seleção (✓ / vazio)',
  kindOptCategory: 'Lista (escolher uma opção)',
  kindOptDegree: 'Nível (1–5)',
  kindOptNumeric: 'Número (notas etc.)',
  cancelShort: 'Cancelar',
  addColumn: 'Critério',
  addStudent: 'Aluno',
  selectAllVisible: 'Selecionar todos os visíveis',
  noTaken: 'O nº {no} já é de outro aluno',
  namePlaceholder: 'Digite um nome',
  confirmDeleteStudent: 'Remover {who} da lista?',
  colNo: 'Nº',
  colName: 'Nome',
  deleteColumnTitle: 'Excluir a coluna “{name}”',
  confirmDeleteColumn: 'Excluir a coluna “{name}”?',
  colPair: 'Condições',
  wantedTitleAttr: 'Manter juntos: {names}',
  unwantedTitleAttr: 'Separar: {names}',
  noMatch: 'Nenhum aluno corresponde aos filtros.',
  selectedN: '{n} selecionados',
  hiddenSelected: ' ({n} ocultos não incluídos)',
  makeWanted: 'Manter juntos',
  makeUnwanted: 'Separar',
  confirmDeleteN: 'Remover {n} alunos da lista?',
  bulkHint: 'Com alunos selecionados, a mudança em uma célula vale para todos',
  clearSelection: 'Limpar seleção',
  pairAll: 'Todos',
  pairAny: 'Com condição',
  pairWantedF: 'Com “manter juntos”',
  pairUnwantedF: 'Com “separar”',
  pairNone: 'Sem condição',
  avg: 'Média {v}',
  notEntered: 'Vazio',
  newOptionPlaceholder: 'Digite uma nova opção e tecle Enter',
  addOption: '+ Adicionar opção',
  listOptions: 'Opções',
  noOptions: 'Ainda não há opções. Adicione uma abaixo.',
  editOption: 'Renomear a opção {v}',
  deleteOption: 'Excluir a opção {v}',
  confirmDeleteOption: 'Excluir "{v}" da lista? Os {n} alunos que a escolheram ficarão vazios.',
  duplicateOption: 'Essa opção já existe',
  listOptionsHint: 'Opções que ninguém escolheu não são mantidas ao salvar em Excel.',
  columnSettings: 'Configurações de “{name}”',
  bulkSet: 'Definir critério',
  setBlankTitle: 'Deixar vazio',
  blankShort: 'Vazio',
  blankLabel: '(vazio)',
  blankName: 'vazio',
  filterNo: 'não',
  filterYes: 'sim',
  filterCount: '{n} valores',
  flagOption: '{v} (sim)',
  clearThis: 'Limpar este filtro',
  groupsWantedTitle: 'Alunos que ficam juntos',
  groupsUnwantedTitle: 'Alunos que ficam separados',
  groupsWantedDesc: 'Os alunos de um conjunto sempre ficam na mesma turma.',
  groupsUnwantedDesc: 'Os alunos de um conjunto ficam em turmas diferentes entre si sempre que possível (com 3 ou mais, todos separados).',
  groupsBulkHint: ' Você também pode selecioná-los na lista e criar o conjunto de uma vez.',
  newGroup: 'Novo conjunto',
  newGroupLabel: 'Novo conjunto (2 ou mais alunos)',
  create: 'Criar',
  confirmDeleteGroup: 'Excluir o conjunto {label}?',
  deleteGroup: 'Excluir conjunto',
  confirmGroupDissolve: 'Sobraria só um aluno, então este conjunto será excluído. Continuar?',
  noGroups: 'Ainda não há condições',
  noName: '(sem nome)',
  removeMember: 'Remover',
  addMemberPlaceholder: '+ Adicionar por nº ou nome',
  noInvalid: 'O nº deve ser um número a partir de 1',
  flagMark: '✓',

  googleScriptFailed: 'Não foi possível carregar {src}',
  googleAuthFailed: 'Falha no login do Google: {msg}',
  googleApiError: 'Houve um problema na comunicação com o Google: {msg}',
  googlePickerTitle: 'Escolha a planilha com a lista de alunos',
  googleTemplateTitle: 'Modelo de lista do FairClass',

  parseRosterMissing: 'A aba “{sheet}” não foi encontrada ou está vazia',
  parseNoStudents: 'Nenhum aluno encontrado (preencha nº e nome a partir da linha 3)',
  parseNoMissing: '{sheet}, linha {row}: “{name}” está sem nº e não foi carregado',
  parseDuplicateNo: 'O nº {no} está repetido',
  parseUnknownNo: '“{sheet}”, linha {row}: o nº {no} não está na lista',
  parseClassCountUnknown: 'Não foi possível ler o número de turmas em “{sheet}”; foram usadas {k} turmas',
  parseMaxTooSmall: 'Com no máximo {max} alunos × {k} turmas não cabem todos, então o máximo não foi aplicado',
}
